### ISSUE TITLE
Use new version of docker provider in ECR module

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-awsx#1010]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Since the new docker.Image resource is faster and better we should use this instead

**Comment by chris-stetter** [comment]
Any plans to release this any time soon? This blocks updating to `pulumi-docker` v4.
