### ISSUE TITLE
awsx classic fargate service taskDefinititionArgs object gives TS error when assigning role.

### ISSUE THREAD

**Issue by jimjoes** [pulumi/pulumi-awsx#1026]
### What happened?

I am getting the following error when creating a fargate service using awsx classic:

`dev/authoringEcsTask.ts(234,21): error TS2741: Property 'roleLastUseds' is missing in type 'import("/Users/jameshunter/src/platform/node_modules/@pulumi/aws/iam/role").Role' but required in type 'import("/Users/jameshunter/src/platform/node_modules/@pulumi/awsx/node_modules/@pulumi/aws/iam/role").Role'.
`
The role is defined as follows:

        const role = new aws.iam.Role(`${process.env["WEBINY_ENV"]}-platform-api-role`, {
            assumeRolePolicy: {
                Version: "2012-10-17",
                Statement: [
                    {
                        Sid: "",
                        Effect: "Allow",
                        Principal: {
                            Service: "ecs-tasks.amazonaws.com"
                        },
                        Action: "sts:AssumeRole"
                    }
                ]
            }
        });

and the fargate service is defined as follows:

        const service = new awsxClassic.ecs.FargateService(
            `${process.env["WEBINY_ENV"]}-authoring-tool-svc`,
            {
                assignPublicIp: true,
                securityGroups: [appSg],
                forceNewDeployment: true,
                taskDefinitionArgs: {
                    executionRole: role, <<< the error is here.
                    containers: {
                {...}

### Expected Behavior

I expect a role created with Pulumi to be able to be assigned to the taskdefinition.

### Steps to reproduce

1. create script using the provided code.
2. attempt to deploy.

### Output of `pulumi about`

`CLI          
Version      3.64.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  13.2.1
Arch     x86_64

This project is written in nodejs: executable='/private/var/folders/gk/knkfm2px1v7_yvv94_wh_1nc0000gn/T/xfs-9838e189/node' version='v14.21.1'

Current Stack: organization/authoring/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::authoring::pulumi:pulumi:Stack::authoring-dev

Found no pending operations associated with dev

Backend        
Name           mac-mini.local
URL            s3://influencemadesimple-pulumi-state/apps/authoring
User           jameshunter
Organizations  `

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @jimjoes, sorry you're running into issues. Something must have gone wrong when setting up your project or environment, there should be no `node_modules` folder inside another. Deleting `node_modules` and the lock file and retrying is probably the easiest fix.

**Comment by thomas11** [comment]
Closing this issue since we didn't receive a response. Feel free to re-open if necessary.
