### ISSUE TITLE
Unable to assign `name`, `appProtocol`, and `containerPortRange` to an ECS Task Definition's `portMappings`

### ISSUE THREAD

**Issue by Tomburgs** [pulumi/pulumi-awsx#1053]
### What happened?

It is not possible to assign a `name`, `appProtocol`, and `containerPortRange` on a `portMappings` value on the `ContainerDefinition` type, which is used by `awsx.ecs.EC2TaskDefinition` and `awsx.ecs.FargateTaskDefinition`.

This prevents users from being able to use ECS Service Connect to allow interservice communication.

- [PortMapping AWS Docs](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PortMapping.html)
- [PortMapping Pulumi Definition](https://github.com/pulumi/pulumi-aws/blob/f787a47a2349b5b9024f9ddf1246668539a648a1/sdk/nodejs/ecs/container.ts#L189)

### Expected Behavior

It should be possible to assign all valid `PortMappings` properties through pulumi for an ECS Task Definition.

### Steps to reproduce

Following code should create an ECS task with a port mapping named 'myContainer' and set app protocol to 'grpc', but instead these values will be omitted from the created resource and typescript will complain about invalid properties.

```typescript
const myTask = new awsx.ecs.EC2TaskDefinition('myTask', {
  container: {
    name: 'myContainerName',
    image: myContainerImageUri,
    portMappings: [{
      containerPort: 4200,
      hostPort: 4200,
      protocol: 'tcp',
      name: 'myContainer',
      appProtocol: 'grpc',
    }],
  }
});
```

### Output of `pulumi about`

CLI
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Host
OS       darwin
Version  13.0
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hi @Tomburgs thanks for reporting this issue! It looks like we're not picking up the latest types available in our upstream dependency [pulumi/pulumi-aws-native](https://github.com/pulumi/pulumi-aws-native) as we're generating our AWSx schema using [v0.13.0 of our AWS Native provider](https://github.com/pulumi/pulumi-awsx/blob/d798487f062748c4bc944c2f178f176fd617f029/schemagen/pkg/gen/schema.go#L31).

We'll need to update this dependency to get the required types! Thanks for identifying and flagging this - we'll be adding this to our backlog to work on.

**Comment by rquitales** [comment]
[v1.0.5](https://github.com/pulumi/pulumi-awsx/releases/tag/v1.0.5) of this provider should now support these assignments.
