### ISSUE TITLE
Add VPC Endpoints to AWSX Classic

### ISSUE THREAD

**Issue by omercnet** [pulumi/pulumi-awsx#1058]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add [VPC Endpoints](https://github.com/pulumi/pulumi-awsx/pull/837) to AWSX Classic

**Comment by omercnet** [comment]
is there a migration guide? I was advised by the pulumi team (last time I checked) there wasn't any

**Comment by guineveresaenger** [comment]
Please see https://github.com/pulumi/pulumi-awsx#migration-from-0x-to-10.

The main difference is that the Classic version is typescript-only, while the maintained current version supports all language SDKs, plus all the nice new features.

If you run into trouble, please reach out to us on https://slack.pulumi.com/; we'll be happy to help.

**Comment by omercnet** [comment]
I'm familiar with that note that says
> **Note**
> The new top-level components (outside the classic namespace) may require additional code changes and resource re-creation.

I have this simple resource
```typescript
const vpc = new awsx.ec2.Vpc(...)
```

can you provide a guide on how to replace it without recreating the vpc ?
