### ISSUE TITLE
Upgrade to pulumi-docker v4

### ISSUE THREAD

**Issue by thomas11** [pulumi/pulumi-awsx#1077]
This was attempted before in #1044 but had to be reverted in #1054 after conversation with @pierskarsenbarg and @lukehoban.

We need to fix the `imageName` vs `repoDigest` issue and get to the bottom of the question about `env` in the first PR.

This will likely be a breaking update, i.e., a new major version, but ideally we can combine it with #1068 in one new version.

**Comment by AaronFriel** [comment]
I don't believe "env" is required anymore, but it will be a breaking change to remove it.

Docker builds cannot use env vars directly, a user must pass a build **arg** which is consumed by the Dockerfile "ARG" statement, that can then be declared as the default value of an env var in the build.

The env input however could control DOCKER_HOST, DOCKER_BUILDKIT, etc. These change Docker engine behavior, and they now respect provider or resource inputs.

**Comment by mjeffryes** [comment]
the latest pinned version of docker is 4.5.0
