### ISSUE TITLE
Import existing components

### ISSUE THREAD

**Issue by blazmrak** [pulumi/pulumi-awsx#1091]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It seems like there is no `import` option on awsx components, which makes it very hard to refactor the projects. I specifically have issue with importing VPC, but I think this is the case with all components.

**Comment by mikhailshilkov** [comment]
Hello @blazmrak thank you for opening this issue. I believe it's a CLI/Core product feature that is tracked in https://github.com/pulumi/pulumi/issues/9146. There's nothing specific to AWSX that we can/need to do, so I'll close it as duplicate. Please upvote the linked issue.

**Comment by blazmrak** [comment]
@mikhailshilkov How does the classic version then have `fromExistingResources` method if this is an issue with CLI/Core?
