### ISSUE TITLE
Dockerfile argument to Image has no effect

### ISSUE THREAD

**Issue by mikeshultz** [pulumi/pulumi-awsx#1109]
### What happened?

I'm trying to setup Pulumi (with Python) to build a docker image for ECR to use with ECS using `pulumi_awsx.ecr.Image` using a Dockerfile with a different filename.

The `dockerfile` argument seems to have no effect, and it always tries to build `Dockerfile`.

### Example

I put together a repository with the simplest testcase:  https://github.com/mikeshultz/pulumi-dockerfile-testcase

Building an image like this:

```python
image = Image(
    "pulumi-dockerfile-testcase",
    repository_url=repository.url,
    # Relative
    #dockerfile="Dockerfile.testcase",
    # Absolute
    dockerfile=Path(__file__).parent.joinpath("Dockerfile.testcase").as_posix(),
)
```

Will throw an error like this:

```
Diagnostics:
  docker:index:Image (image):
    error: could not open dockerfile at relative path Dockerfile: stat Dockerfile: no such file or directory

  pulumi:pulumi:Stack (pulumi-dockerfile-testcase-dev):
    error: Resource monitor has terminated, shutting down
```

This also makes it impossible to build multiple image from different Dockerfiles unless they have different contexts.

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.89.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.6.0
awsx    2.0.2
docker  4.4.3
python  unknown

Host     
OS       arch
Version  
Arch     x86_64

This project is written in python: executable='/home/mike/.venvs/pulumi-testcase/bin/python3' version='3.10.13'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mikeshultz
User           mikeshultz
Organizations  mikeshultz
Token type     personal

Dependencies:
NAME         VERSION
pip          23.0.1
pulumi-awsx  2.0.2
setuptools   65.5.0

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikeshultz** [comment]
For anyone that runs into this, it seems to be possible to get it running using the lower level `pulumi_docker` `Image` construct.  Should look something like this:

```python
from pulumi_docker import DockerBuildArgs, Image, RegistryArgs

image = Image(
    "pulumi-dockerfile-testcase",
    build=DockerBuildArgs(
        context=Path(__file__).parent.as_posix(),
        dockerfile=Path(__file__).parent.joinpath("Dockerfile.testcase").as_posix(),
    ),
    image_name=repository.url.apply(lambda url: f"{url}/pulumi-dockerfile-testcase:latest"),
)
```

**Comment by mikhailshilkov** [comment]
Yeah, we missed passing it in https://github.com/pulumi/pulumi-awsx/blob/fee806add479759db8f82bbbfd51f75523b37f7d/awsx/ecr/image.ts#L66

Let me see if I can fix it with a quick PR.
