### ISSUE TITLE
InvalidSubnet.Range: The CIDR '10.10.1.0/24' is invalid

### ISSUE THREAD

**Issue by jimmydivvy** [pulumi/pulumi-awsx#111]
The `infra.Network` class defaults to creating subnets in the form of `10.10.${i}.0/24`. 

This works fine if using the default VPC CIRD of `10.10.0.0/16`, gowever if the VPC is created with a different CIDR block, subnet creation fails.

Example:

```
const network = new infra.Network("eks-vpc", {
    cidrBlock: "192.168.0.0/16"   
})
```

```
Diagnostics:
  aws:ec2:Subnet (eks-vpc-1):
    error: Plan apply failed: Error creating subnet: InvalidSubnet.Range: The CIDR '10.10.1.0/24' is invalid.
    	status code: 400, request id: 9565998e-ad43-4e05-bf7a-e9e02a0c36ee
 
  aws:ec2:Subnet (eks-vpc-0):
    error: Plan apply failed: Error creating subnet: InvalidSubnet.Range: The CIDR '10.10.0.0/24' is invalid.
    	status code: 400, request id: e49b0042-25a0-4eed-a4b2-ebd5ee82f265

```

**Comment by CyrusNajmabadi** [comment]
@jimmydivvy Sorry for the very long response time on this.  We've introduced a new abstraction to `pulumi/awsx` that might be more useful for you here.  Specifically, it is:

https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/ec2/vpc.ts

This guy allows for a lot more flexibility with vpc/subnets/cidr work, and may make things much easier for your use case.  Could you get back to me if moving over to this type would be a viable approach for you?  I'm also happy to chat at any time in our Slack channel over at https://pulumi-community.slack.com/messages/C84L4E3N1

Feel free to reach out if you have questions about this.

**Comment by CyrusNajmabadi** [comment]
Closing out due to lack of contact.  awsx.ec2.Vpc is the recommended way to go forward here.
