### ISSUE TITLE
Upgrade pulumi-docker to >4.5.0 to pick up a critical bugfix

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-awsx#1160]
pulumi-docker 4.5.0 includes a fix for https://github.com/pulumi/pulumi-docker/pull/843. We should update and release to pick up this fix.

**Comment by thegoldenmule** [comment]
Are there any workarounds for this until awsx updates? The mentioned repo digest issue is happening 100% of the time for us, so it's blocking our ability to use the awsx framework.
