### ISSUE TITLE
ecs task definition port mappings not applying all options

### ISSUE THREAD

**Issue by Tomburgs** [pulumi/pulumi-awsx#1168]
### What happened?

ecs task definitions are not applying most of the port mapping options, such as `name`, `appProtocol`, `containerPortRange`, and [some others](https://github.com/pulumi/pulumi-awsx/blob/master/awsx/schema-types.ts#L951).

### Example

setting port mappings like so on either an EC2 or Fargate task definition will result in an unnamed port definition being created, despite `name` being passed

```typescript
portMappings: [
  {
    name: 'my-port-name',
    containerPort: 80,
  },
],
```

this causes issues with service connect which **needs** port mappings to be named. this makes service connect unusable with pulumi.

### Output of `pulumi about`

CLI
Version      3.94.2
Go Version   go1.21.3
Go Compiler  gc

Host
OS       darwin
Version  14.0
Arch     arm64

### Contributing

seems like these lines here are the culprits: https://github.com/pulumi/pulumi-awsx/blob/9f5b18b7be1b11f99d7d0dc4d1438bfd996bf996/awsx/ecs/containers.ts#L99C1-L108C2

**Comment by mjeffryes** [comment]
Thanks for reporting this @Tomburgs, I agree with your analysis as to the likely cause. I'll add this to our backlog, but feel free to contribute a PR if you'd like as well!
