### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by Tomburgs** [pulumi/pulumi-awsx#1182]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We'd like to ask for a new release (or for an expected date of a new release) of pulumi-awsx. We tried raising this in Slack, but got no reply.

There's currently an important bug fix (#1169) that is preventing us from using service connect and forces us to use some very expensive LBs in the meantime :'(

### Affected area/feature

named port mappings for ecs services.

**Comment by mjeffryes** [comment]
I've started a new release build for you here: https://github.com/pulumi/pulumi-awsx/actions 
v2.4.0 should be published soon.
