### ISSUE TITLE
Deleting rules after VPC throws an error

### ISSUE THREAD

**Issue by VenkatH** [pulumi/pulumi-awsx#1195]
### What happened?

Two custom rules setup in network ACLs for CIDR 0.0.0.0/0, after the VPC is created and when destroying resources the rules get delete after the VPC instead of before which throws an error

```
 -   ├─ awsx:ec2:Vpc                               dbricks-mwsbypulumi-vpc                                                                                                                               
 -   ├─ aws:ec2:NetworkAclRule                     Creating the tcp traffic egress rule 
 -   └─ aws:ec2:NetworkAclRule                     Creating the tcp egress rule     
```

### Example

- Create VPC using awsx and then get the network ACLs id. 
- Set egress rule for CIDR block 0.0.0.0/0 for that id

### Output of `pulumi about`

v3.100.0 on Mac(Sonoma 14.1.2)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenkatH** [comment]
Was able to solve by adding dependency on the VPC, not sure its right way to fix the issue

**Comment by mjeffryes** [comment]
@VenkatH Yes, adding the VPC as a dependency is the right way to indicate that the NetworkAclRule resource you added needs to be created after and destroyed before the VPC resource.
