### ISSUE TITLE
Add dev container

### ISSUE THREAD

**Issue by dhilgarth** [pulumi/pulumi-awsx#1200]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would help first time contributors tremendously, if there would be a dev container in the repo. pulumi-tf-provider-boilerplate already has this

### Affected area/feature

Contributing

**Comment by mjeffryes** [comment]
Thanks for the suggestion @dhilgarth; we've started rolling out devcontainers to some providers, but as you can see we've not quite finished the job. Glad to hear that they've been useful and we'll work on finishing the roll out!
