### ISSUE TITLE
Custom image tags with awsx.ecr.Image

### ISSUE THREAD

**Issue by kennethlynne** [pulumi/pulumi-awsx#1224]
## Hello!
I am dumbfounded by awsx.Image. 
have been struggling for a while with some rather lacking examples and documentation (or my own misunderstanding of it). I have difficulty understanding how to move from a "hello world" example to something robust and production-ready with ECS and ECR.
I could not figure out how to set the image tags properly with any documentation, and eventually, I found [this implementation](https://github.com/pulumi/pulumi-awsx/blob/5586b5776d22c437044f2e20b23a1768d786fb97/awsx/ecr/image.ts#L109) 

This implementation simply pushes cryptic `abc123-container`. Have I misunderstood something about the intended use? Is this the best practice?

I'd like to be able to push both 'latest' and 'v1.33.7', for example, to make it easy to use it for cache or pull the image, but NOPE, it must be fetched by using pulumi outputs, and I have no idea about what version anything is and have to rely on timestamps, and I even lack a way to override it.
I can help out with a PR if need be. 

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

**Comment by kennethlynne** [comment]
Something like this is simply not working as expected:
```
 const image = new awsx.ecr.Image(
      `${version}`,
      {
        repositoryUrl: this.repositoryUrl,
        context: monorepoRootDir,
        dockerfile: dockerfilePath,
        platform: 'linux/amd64',
        args: {
          BUILDKIT_INLINE_CACHE: '1',
          VERSION: version,
        },
        cacheFrom: [pulumi.interpolate`${this.repositoryUrl}:${version}`],
      },
      { parent: this },
    );
    this.image = image.imageUri;
```

**Comment by larrywax** [comment]
Stuck on the same thing, it's a bit silly that we cannot specify the image version with resource args...
I'll try to open a PR to fix this

**Comment by mjeffryes** [comment]
Thanks @kennethlynne for the bug report and @larrywax for the PR. We'll try to take a look at the PR soon to get this working for you all!

**Comment by larrywax** [comment]
Hi, any update on this? I saw the PR has been merged, do you have any ETA of a release? 
Thank you

**Comment by mjeffryes** [comment]
I've kicked off a release here: https://github.com/pulumi/pulumi-awsx/actions/runs/8255432424 sorry for the delay!

**Comment by larrywax** [comment]
Sorry to bother you again @mjeffryes, but the release build failed :(

**Comment by gbolo** [comment]
hoping to get this soon. in the meantime I been using `pulumi_docker` which allows image tags and everything else. But it requires wiring up `aws.ecr.get_authorization_token` with docker auth

**Comment by mjeffryes** [comment]
Looks like just a flaky test on the release build. I re-ran it and looks like v2.6.0 is now published. Sorry about the delay!
