### ISSUE TITLE
Impossible to provide timeout settings to service connect

### ISSUE THREAD

**Issue by Tomburgs** [pulumi/pulumi-awsx#1237]
### What happened?

It's currently not possible to provide [timeout](https://www.pulumi.com/registry/packages/aws/api-docs/ecs/service/#serviceserviceconnectconfigurationservicetimeout) to a `FargateService` due to outdated `@pulumi/aws` dependency.

### Example

We wish to be able to provide custom timeout to our fargate services like so

```typescript
new awsx.ecs.FargateService(
  'fargate-service',
  {
    name: 'fargate-service',
    serviceConnectConfiguration: {
      services: [
        {
          timeout: { perRequestTimeoutSeconds: ourCustomTimeout }
          ...
```

### Output of `pulumi about`

```
CLI
Version      3.94.2
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.25.1
aws     6.12.0
awsx    2.5.0
docker  4.5.0
nodejs  unknown

Host
OS       darwin
Version  14.0
Arch     arm64
```

### Additional context

In theory it should be possible to just update the types, but I'm not sure how much work this would actually be.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Hey, this should now be fixed in: https://github.com/pulumi/pulumi-awsx/releases/tag/v2.9.0
