### ISSUE TITLE
`forceNewDeployment` for `awsx.ecs.FargateService` seems to have no effect

### ISSUE THREAD

**Issue by markalexander** [pulumi/pulumi-awsx#1249]
### What happened?

When specifying an `awsx.ecs.FargateService` resource, I'm trying to pass in `forceNewDeployment: true` to force a deploy of the service on every `pulumi up`.  However, my plan always comes back with no changes unless I alter the args, image tag, etc.

### Example

A simple cluster and service:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const cluster = new aws.ecs.Cluster("cluster", {});

new awsx.ecs.FargateService("service", {
  cluster: cluster.arn,
  assignPublicIp: true,
  desiredCount: 1,
  taskDefinitionArgs: {
    container: {
      name: "service-task",
      image: "docker.io/memcached",
      cpu: 128,
      memory: 512,
      essential: true,
    },
  },
  forceNewDeployment: true,
});
```

Deploy once with e.g. `pulumi up`, then immediately run `pulumi up` again.  This gives:

```
[...]

Resources:
    11 unchanged

[...]
```

Whereas I would expect the service update to be there because of the `forceNewDeployment` setting.

### Output of `pulumi about`

```
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  14.1.2
Arch     arm64

This project is written in nodejs: executable='/Users/[...]/.asdf/shims/node' version='v16.15.1'

[...]

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/[...]
User           [...]
Organizations  [...]
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/aws     6.28.1
@pulumi/awsx    2.6.0
@pulumi/pulumi  3.112.0
@types/node     18.19.26

Pulumi locates its logs in /var/folders/q3/mk2vg8h90lxdvblf8xs__w9c0000gq/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by corymhall** [comment]
@markalexander thanks for raising this issue! It looks like this is an issue with the underlying aws provider which we are tracking here https://github.com/pulumi/pulumi-aws/issues/2266.
