### ISSUE TITLE
Updating awsx means EIPs aren't tagged

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-awsx#1281]
### What happened?

No code changes, I simply update the package to the latest version

### Example

```
~ aws:ec2/eip:Eip: (update)
                    [id=eipalloc-04f9bc3e66ba35d6c]
                    [urn=urn:pulumi:production::vpc::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/eip:Eip::vpc-production-1]
                    [provider: urn:pulumi:production::vpc::pulumi:providers:aws::default_6_32_0::436489a4-ee2e-4663-b298-79b34110f21f => urn:pulumi:production::vpc::pulumi:providers:aws::default_6_9_0::output<string>]
                  - tags   : {
                      - Name       : "vpc-production-1"
                      - environment: "production"
                      - project    : "vpc"
                    }
```

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by flostadler** [comment]
Thank for bringing this up @jaxxstorm! What version of the provider were you running before?

**Comment by flostadler** [comment]
This line here `[provider: urn:pulumi:production::vpc::pulumi:providers:aws::default_6_32_0::436489a4-ee2e-4663-b298-79b34110f21f => urn:pulumi:production::vpc::pulumi:providers:aws::default_6_9_0::output<string>]` makes me think the provider actually got downgraded.

Which could explain why the tags got removed. The VPC tags weren't propagated to the EIPs prior to version 2.4.0 (fixed here: https://github.com/pulumi/pulumi-awsx/commit/9f5b18b7be1b11f99d7d0dc4d1438bfd996bf996).

**Comment by jaxxstorm** [comment]
That makes sense, thanks
