### ISSUE TITLE
add security group option for network load balancer

### ISSUE THREAD

**Issue by w0aw** [pulumi/pulumi-awsx#1282]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

i have an k3s cluster running on private subnet. with 2 k3s master nodes behind an NLB and now if i try to join a new worker node using NLB dns then it fails. like the dns resolves to some private ips which are not reachable and curretly i am using a single master node's private ip join new worker nodes. if somehow i can add a security group (that allow all ingress traffic from same vpc) then this issue can be solved. 

### Affected area/feature

thank you. i hope i am on right place

**Comment by flostadler** [comment]
Hey @w0aw, thanks for bringing this up! I assume you're referring to the `NetworkLoadBalancer` component resource, right?

You're correct that it (and the ALB resource) is lacking a way to configure security groups for the NLB right now. I'm gonna work on prioritizing this.

As a workaround you could use transformations (https://www.pulumi.com/docs/concepts/options/transformations/) to inject the `securityGroups` parameter on the underlying `aws:lb/loadBalancer:LoadBalancer` resource while we work on adding exposing the parameter here.

**Comment by w0aw** [comment]
hi @flostadler, thanks for resolving this issue. can you please confirm how long it will take to get merged and npm release?
