### ISSUE TITLE
Bump @pulumi/aws to at least v6.42.1 to fix ECS task def diff issue

### ISSUE THREAD

**Issue by smsunarto** [pulumi/pulumi-awsx#1347]
### What happened?

Prior to @pulumi/aws@v6.42.1 there is an upstream issue that is causing ECS task definition to be stuck in a permanent diff state due to normalization issue. This issue have been resolved in v6.42.1 and AWSx should be bump to resolve this.

### Example

See https://github.com/pulumi/pulumi-aws/issues/1738

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Thanks @smsunarto excellent point.
