### ISSUE TITLE
Expose subnets and NAT creation on Vpc

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-awsx#139]
The `Vpc` object makes working with newly created VPCs easy -- you get to specify the number of public/private/isolated subnets and automatically have NAT and/or Internet gateways automatically created. My use case requires us to work within an **existing** VPC so we do not have access to all those niceties provided by the `Vpc` object -- they are only available when creating a **new** `Vpc`.

My suggestion is to expose the subnet, NAT gateway, and Internet gateway creation as methods on the `Vpc` object. For example: 

```typescript
const vpc = infra.ec2.Vpc.fromExistingIds("my-vpc", {
    vpcId: myExistingVpcId,
    publicSubnetIds: mySubnets,
});

vpc.addSubnet()
vpc.subnets[0].withNatGateway()
vpc.addNatGatewayToPrivateSubnets
vpc.addInternetGateway
```

**Comment by CyrusNajmabadi** [comment]
Great idea!

**Comment by CyrusNajmabadi** [comment]
Note: `vpc.addSubnet()` would be harder to do as we compute the cidr breakdown up front.  All the rest would likely be things we could do hopefully simply.
