### ISSUE TITLE
Add support for API keys to awsx.apigateway.API

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#155]
API keys are one of a few features of API Gateway that are not exposed yet in the higher-level `API` component. We should expose a way to use these (and other features), ideally in such a way that we do not need to duplicate much/any functionality that is already available from API gateway.

**Comment by CyrusNajmabadi** [comment]
Tracked in https://github.com/pulumi/pulumi-awsx/issues/184.
