### ISSUE TITLE
Creating vpc with ec2.Vpc is not properly tagging resources

### ISSUE THREAD

**Issue by Incisive** [pulumi/pulumi-awsx#161]
When creating a VPC with the `awsx.ec2.Vpc` class, the resulting resources are not receiving the `Name` tag.  Previously the `awsx.Network` class was creating these tags, which is why I'm curious if this functionality was changed.

Below is the example statement I'm using when creating a VPC:

```js
const vpc = new awsx.ec2.Vpc(
    `secrets-scanner-${env}`,
    {
        cidrBlock: '10.10.0.0/16',
        numberOfAvailabilityZones: 2,
    },
    { protect: true }
);

```

And here are the versions of the Pulumi libraries I'm using in my package.json:

```json

"dependencies": {
    "@pulumi/aws": "latest",
    "@pulumi/awsx": "^0.16.4",
    "@pulumi/cloud": "^0.16.2",
    "@pulumi/cloud-aws": "^0.16.2",
    "@pulumi/pulumi": "latest"
  }
```

**Comment by stack72** [comment]
@jkodroff i believe we now create the Name tag by default on the resources as part of our recent rewrite, correct?

**Comment by lukehoban** [comment]
> i believe we now create the Name tag by default on the resources as part of our recent rewrite, correct?

Confirmed that we do with the 1.0.0-beta releases.
