### ISSUE TITLE
Support additional areas

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#167]
Some additional areas we would like to add additional high level components:

* [ ] IAM roles/policies
* [ ]  Service Discovery
* [x]  Metrics.  https://github.com/pulumi/pulumi-awsx/pull/214
* [x]  Alarms.  https://github.com/pulumi/pulumi-awsx/pull/214
* [x] Scaling policies.  https://github.com/pulumi/pulumi-awsx/pull/240 and https://github.com/pulumi/pulumi-awsx/pull/232
* [x]  Dashboard.  https://github.com/pulumi/pulumi-awsx/pull/217
* [ ]  RDS/Aurora

**Comment by CyrusNajmabadi** [comment]
Luke, i'm going to close this out for m22 and open individual issues tracking the remainder.
