### ISSUE TITLE
Further improvements to awsx-apigateway

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#184]
Here's the list of low hanging areas we need to investigate and can potentially improve our apigateway efforts with:

- [x] Add an appropriate README.md that walks people through working with apigateway (similar to what we have in our other modues, like https://github.com/pulumi/pulumi-awsx/tree/master/nodejs/awsx/ec2)
- [x] [Request Validation](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-request-validation.html).  This allows someone to set up simple validation that AWS can perform before it even calls through to the final endpoint.  Good examples of how you use this found here: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-method-request-validation.html.  
- [ ] [Client Certificates](https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-client-side-ssl-authentication.html#configure-api)
- [x] [Authorizors](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html).  We can *really* excel here as authorizors allow you to hook up lambdas to control the authorization control flow, and we would allow you to literally just inline the strongly-typed lambdas here right in your single pulumi definition.
- [x] Support for Cognito User Pool Authorizer
- [x] [Api Keys](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-setup-api-key-with-restapi.html).  Note this may not really need much work on our end at all given the primitives in the aws package.  But we should still make sure this works, and see if we can expose cleanly through awsx.
- [x] [Usage Plans](https://aws.amazon.com/blogs/aws/new-usage-plans-for-amazon-api-gateway/).  This also ties into APIKeys.   And, similar to API Keys, this may be trivial to support.  But we should verify it's got a good experience around it and feels natural from the AWSX layer.  
- [ ] [Custom Domains and Base Path Mappings](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html).  Some useful information here: https://datanextsolutions.com/blog/setup-custom-domain-for-an-api-in-aws-api-gateway/
- [x] Remove `aws.apigateway.x.API` which is a duplicate of the functionality here (I believe it is currently deprecated).
- [ ] Implement the `IntegrationRouteTargetProvider` interface for some resources and add examples to the doc
- [x] Expose the resulting lambdas in some sort of object to allow users to access them for metrics (and potentially other use cases)
- [ ] More standardized responses for failing API Keys and such. Most failing authorizers / apikeys return a 403 which is not correct. refer to: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#Client_error_responses
- [ ] Add request validation, api keys, and authorizers for raw data routes -- which allow users to write raw Swagger. These 3 features require changes at the route level as well as the API level. We need to think about this a bit as it will get tricky to figure out how to blend the raw swagger coming in for routes plus the Swagger object we create.

**Comment by CyrusNajmabadi** [comment]
Tagging @ekrengel

**Comment by ekrengel** [comment]
I have a PR for Lambda Authorizers. We also will want to support Cognito User Pools.

- [ ] Support for Cognito User Pool Authorizers

**Comment by ekrengel** [comment]
Looks like removing `aws.apigateway.x.API` was completed as part of 0.18.0 (Released March 28th, 2019).

**Comment by ekrengel** [comment]
I believe there is currently an issue w/ Integration Routes. This simple example returns a 500 b/c there are no output mappings. 

```ts
const api = new awsx.apigateway.API("myapi", {
    routes: [{
        path: "/c",
        target: {
            type: "http",
            uri: "https://www.google.com",
        },
    }],
});
```

The console test shows these logs:

```
Tue Apr 09 03:48:23 UTC 2019 : Execution failed due to configuration error: Output mapping refers to an invalid method response: 200
Tue Apr 09 03:48:23 UTC 2019 : Method completed with status: 500
```

**Comment by ekrengel** [comment]
Work Completed during M22:
- Add Readme
- request validation for parameters
- Lambda and cognito authorizers
- api keys + usage plans 
- expose resulting lambda for metrics
 

We will leave this open for M23 for further improvements.

**Comment by cmtoomey** [comment]
Would it also be possible to allow for the selection of API deployment types
- Regional
- Edge-optimized
- Private

The use-case is that a user may want some flexibility in how their APIs are deployed (public consumption vs internal consumption).

**Comment by rarous** [comment]
It would be nice to have some way to set `restApi.minimumCompressionSize`.

**Comment by naineel** [comment]
Adding the ability to add resource policies would also be nice. https://docs.aws.amazon.com/en_pv/apigateway/latest/developerguide/apigateway-resource-policies.html

**Comment by RichiCoder1** [comment]
Not sure if this should be it's own ticket, but the ability to set cache control headers on Static Routes would be great. Either as a callback or as a glob map

**Comment by vmachacek** [comment]
Hello, I'm trying to use `IntegrationRouteTargetProvider` for Lambda with Alias but still can't figure it out, some documentation / example would be nice.

**Comment by rarous** [comment]
It would be nice to have ability to intercept generated swagger, so i can add/change stuff like `x-amazon-apigateway-integration` attributes. In my case I need to set `cacheKeyParameters`.

**Comment by danielrbradley** [comment]
Closing as this appears to be a now-stale planning ticket.
