### ISSUE TITLE
vpc: Error creating EIP tags: InvalidID: The ID '...' is not valid

### ISSUE THREAD

**Issue by ggilmore** [pulumi/pulumi-awsx#187]
Hello, 

I am trying to create an EKS cluster mostly following this example:  https://github.com/pulumi/examples/tree/master/aws-ts-eks. 

However, I want to create a cluster with a VPC that has both a public and private subnet in each AZ (following the best practices as described in the "Networking" section of https://blog.aquasec.com/first-steps-creating-and-securing-an-eks-cluster). 

I am using the `awsx.ec2.VPC` component provided by this package in order to create that kind of VPC since the example in the Readme looks like exactly what I need: https://github.com/pulumi/pulumi-awsx/blame/a4b32654466961f77de68c4f5ed90a0cbc747514/nodejs/awsx/ec2/README.md#L66

--- 

I've created a repository that has the exact configuration that I'm trying to use: https://github.com/ggilmore/pulumi-eip-repro

I keep getting the following error whenever I run `pulumi up` in https://github.com/ggilmore/pulumi-eip-repro:

```
Diagnostics:
  aws:ec2:Eip (eksNetwork-0):

    error: Plan apply failed: 1 error occurred:
    * creating urn:pulumi:dev::eks-cluster::awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::eksNetwork-0: Error creating EIP tags: InvalidID: The ID '54.245.84.217' is not valid
        status code: 400, request id: 1fc802a4-c586-4700-9ee2-553d53a4ecd6
  aws:ec2:Eip (eksNetwork-1):

    error: Plan apply failed: 1 error occurred:
    * creating urn:pulumi:dev::eks-cluster::awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::eksNetwork-1: Error creating EIP tags: InvalidID: The ID '50.112.109.185' is not valid
        status code: 400, request id: 7dc40f73-2a75-4e12-87de-8fddfa48b406
```

Full `pulumi up` output:

<details>
<pre>
Previewing update (dev):

     Type                                    Name                             Plan       Info
 +   pulumi:pulumi:Stack                     eks-cluster-dev                  create     Method handler diffConfig for /pulumirpc.ResourceProvider/
 +   ├─ eks:index:Cluster                    cluster                          create
 +   │  ├─ eks:index:ServiceRole             cluster-eksRole                  create
 +   │  │  ├─ aws:iam:Role                   cluster-eksRole-role             create
 +   │  │  ├─ aws:iam:RolePolicyAttachment   cluster-eksRole-4b490823         create
 +   │  │  └─ aws:iam:RolePolicyAttachment         cluster-eksRole-90eb1c99         create
 +   │  ├─ eks:index:ServiceRole                   cluster-instanceRole             create
 +   │  │  ├─ aws:iam:Role                         cluster-instanceRole-role        create
 +   │  │  ├─ aws:iam:RolePolicyAttachment         cluster-instanceRole-3eb088f2    create
 +   │  │  ├─ aws:iam:RolePolicyAttachment         cluster-instanceRole-03516f97    create
 +   │  │  └─ aws:iam:RolePolicyAttachment         cluster-instanceRole-e1b295bd    create
 +   │  ├─ kubernetes:yaml:ConfigGroup             cluster-dashboard                create
 +   │  ├─ pulumi-nodejs:dynamic:Resource          cluster-cfnStackName             create
 +   │  ├─ pulumi-nodejs:dynamic:Resource          cluster-cfnStackName             create
 +   │  ├─ aws:ec2:SecurityGroup                   cluster-eksClusterSecurityGroup  create
 +   │  ├─ aws:ec2:SecurityGroup                                cluster-eksClusterSecurityGroup           create
 +   │  ├─ aws:ec2:SecurityGroup                                cluster-eksClusterSecurityGroup           create
 +   │  ├─ aws:eks:Cluster                                          cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                          cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   │  ├─ aws:eks:Cluster                                             cluster-eksCluster                        create
 +   pulumi:pulumi:Stack                                               eks-cluster-dev                           create     2 messages
 +   │  ├─ pulumi:providers:kubernetes                                 cluster-eks-k8s                           create
 +   │  ├─ pulumi-nodejs:dynamic:Resource                              cluster-vpc-cni                           create
 +   │  ├─ aws:ec2:SecurityGroup                                       cluster-nodeSecurityGroup                 create
 +   │  ├─ kubernetes:storage.k8s.io:StorageClass                      cluster-gp2                               create
 +   │  ├─ kubernetes:core:ConfigMap                                   cluster-nodeAccess                        create
 +   │  ├─ aws:ec2:SecurityGroupRule                                   cluster-eksClusterIngressRule             create
 +   │  ├─ aws:ec2:LaunchConfiguration                                 cluster-nodeLaunchConfiguration           create
 +   │  ├─ aws:cloudformation:Stack                                    cluster-nodes                             create
 +   │  ├─ pulumi:providers:kubernetes                                 cluster-provider                          create
 +   │  ├─ kubernetes:core:ServiceAccount                              cluster-eks-admin                         create
 +   │  └─ kubernetes:rbac.authorization.k8s.io:ClusterRoleBinding     cluster-eks-admin                         create
 +   ├─ awsx:x:ec2:Vpc                                                 eksNetwork                                create
 +   │  ├─ awsx:x:ec2:Subnet                                           eksNetwork-public-0                       create
 +   │  │  ├─ aws:ec2:RouteTable                                       eksNetwork-public-0                       create
 +   │  │  ├─ aws:ec2:Subnet                                           eksNetwork-public-0                       create
 +   │  │  └─ aws:ec2:RouteTableAssociation                            eksNetwork-public-0                       create
 +   │  ├─ awsx:x:ec2:Subnet                                           eksNetwork-public-1                       create
 +   │  │  ├─ aws:ec2:RouteTable                                       eksNetwork-public-1                       create
 +   │  │  ├─ aws:ec2:Subnet                                           eksNetwork-public-1                       create
 +   │  │  └─ aws:ec2:RouteTableAssociation                            eksNetwork-public-1                       create
 +   │  ├─ awsx:x:ec2:Subnet                                           eksNetwork-private-0                      create
 +   │  │  ├─ aws:ec2:RouteTable                                       eksNetwork-private-0                      create
 +   │  │  ├─ aws:ec2:Subnet                                           eksNetwork-private-0                      create
 +   │  │  └─ aws:ec2:RouteTableAssociation                            eksNetwork-private-0                      create
 +   │  ├─ awsx:x:ec2:Subnet                                           eksNetwork-private-1                      create
 +   │  │  ├─ aws:ec2:RouteTable                                       eksNetwork-private-1                      create
 +   │  │  ├─ aws:ec2:Subnet                                           eksNetwork-private-1                      create
 +   │  │  └─ aws:ec2:RouteTableAssociation                            eksNetwork-private-1                      create
 +   │  └─ awsx:x:ec2:InternetGateway                                  eksNetwork                                create
 +   │     └─ aws:ec2:InternetGateway                                  eksNetwork                                create
 +   ├─ awsx:x:ec2:NatGateway                                          eksNetwork-1                              create
 +   │  ├─ aws:ec2:Eip                                                 eksNetwork-1                              create
 +   │  └─ aws:ec2:NatGateway                                          eksNetwork-1                              create
 +   ├─ awsx:x:ec2:NatGateway                                          eksNetwork-0                              create
 +   │  ├─ aws:ec2:Eip                                                 eksNetwork-0                              create
 +   │  └─ aws:ec2:NatGateway                                          eksNetwork-0                              create
 +   ├─ aws:ec2:Vpc                                                    eksNetwork                                create
 +   ├─ aws:ec2:Route                                                  eksNetwork-public-0-ig                    create
 +   ├─ aws:ec2:Route                                                  eksNetwork-public-1-ig                    create
 +   ├─ aws:ec2:Route                                                  eksNetwork-private-0-nat-0                create
 +   └─ aws:ec2:Route                                                  eksNetwork-private-1-nat-1                create

Diagnostics:
  pulumi:pulumi:Stack (eks-cluster-dev):
    Method handler checkConfig for /pulumirpc.ResourceProvider/CheckConfig expected but not provided
    Method handler diffConfig for /pulumirpc.ResourceProvider/DiffConfig expected but not provided

Resources:
    + 69 to create

Do you want to perform this update? yes
Updating (dev):

     Type                              Name                  Status                  Info
 +   pulumi:pulumi:Stack               eks-cluster-dev       created                 2 messages
 +   ├─ awsx:x:ec2:NatGateway          eksNetwork-0          created
 +   │  └─ aws:ec2:Eip                 eksNetwork-0          **creating failed**     1 error
 +   ├─ awsx:x:ec2:NatGateway          eksNetwork-1          created
 +   │  └─ aws:ec2:Eip                 eksNetwork-1          **creating failed**     1 error
 +   ├─ awsx:x:ec2:Vpc                 eksNetwork            created
 +   │  ├─ awsx:x:ec2:Subnet           eksNetwork-public-0   created
 +   │  ├─ awsx:x:ec2:Subnet           eksNetwork-private-1  created
 +   │  ├─ awsx:x:ec2:Subnet           eksNetwork-public-1   created
 +   │  ├─ awsx:x:ec2:InternetGateway  eksNetwork            created
 +   │  └─ awsx:x:ec2:Subnet           eksNetwork-private-0  created
 +   ├─ eks:index:Cluster              cluster               created
 +   └─ aws:ec2:Vpc                    eksNetwork            created

Diagnostics:
  aws:ec2:Eip (eksNetwork-0):
    error: Plan apply failed: 1 error occurred:

    * creating urn:pulumi:dev::eks-cluster::awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::eksNetwork-0: Error creating EIP tags: InvalidID: The ID '54.245.84.217' is not valid
    	status code: 400, request id: 1fc802a4-c586-4700-9ee2-553d53a4ecd6

  aws:ec2:Eip (eksNetwork-1):
    error: Plan apply failed: 1 error occurred:

    * creating urn:pulumi:dev::eks-cluster::awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::eksNetwork-1: Error creating EIP tags: InvalidID: The ID '50.112.109.185' is not valid
    	status code: 400, request id: 7dc40f73-2a75-4e12-87de-8fddfa48b406

  pulumi:pulumi:Stack (eks-cluster-dev):
    Method handler checkConfig for /pulumirpc.ResourceProvider/CheckConfig expected but not provided
    Method handler diffConfig for /pulumirpc.ResourceProvider/DiffConfig expected but not provided

Resources:
    + 11 created

Duration: 7s

Permalink: https://app.pulumi.com/ggilmore/eks-cluster/dev/updates/3
error: update failed
</pre>
</details>

Can someone tell me if there is something wrong with the way that I declared the VPC resource in https://github.com/ggilmore/pulumi-eip-repro ?

**Comment by CyrusNajmabadi** [comment]
This is definitely strange.  I haven't worked with EKS before, so i tried just reproing this with this section commented out:

```
// Create an EKS cluster with the given configuration.
const cluster = new eks.Cluster("cluster", {
  vpcId: vpc.id,
  subnetIds: vpc.id.apply(id => getSubnetIds(id)),
  instanceType: instanceType,
  desiredCapacity: desiredCapacity,
  minSize: minSize,
  maxSize: maxSize,
  storageClasses: storageClass,
  deployDashboard: deployDashboard
});
```

Can we first try that with you and see if you can get that working?  If so, that will help isolate this to being EKS specific or not.  Thanks!

**Comment by ggilmore** [comment]
Hello @CyrusNajmabadi,

After commenting out the eks section in https://github.com/ggilmore/pulumi-eip-repro/commit/d2ab30c4c4d6d1eb040964b79bca58cdc91126e5, I was still able to reproduce the issue:


`pulumi up` output:

```
Previewing update (dev):

     Type                                    Name                    Plan
 +   pulumi:pulumi:Stack                     eks-cluster-dev             create
 +   ├─ awsx:x:ec2:NatGateway                eksNetwork-0                create
 +   │  ├─ aws:ec2:Eip                       eksNetwork-0                create
 +   │  └─ aws:ec2:NatGateway                eksNetwork-0                create
 +   ├─ awsx:x:ec2:Vpc                       eksNetwork                  create
 +   │  ├─ awsx:x:ec2:Subnet                 eksNetwork-private-0        create
 +   │  │  ├─ aws:ec2:RouteTable             eksNetwork-private-0        create
 +   │  │  ├─ aws:ec2:Subnet                 eksNetwork-private-0        create
 +   │  │  └─ aws:ec2:RouteTableAssociation  eksNetwork-private-0        create
 +   │  ├─ awsx:x:ec2:Subnet                 eksNetwork-public-1         create
 +   │  │  ├─ aws:ec2:RouteTable             eksNetwork-public-1         create
 +   │  │  ├─ aws:ec2:Subnet                 eksNetwork-public-1         create
 +   │  │  └─ aws:ec2:RouteTableAssociation  eksNetwork-public-1         create
 +   │  ├─ awsx:x:ec2:Subnet                 eksNetwork-public-0         create
 +   │  │  ├─ aws:ec2:RouteTable             eksNetwork-public-0         create
 +   │  │  ├─ aws:ec2:Subnet                 eksNetwork-public-0         create
 +   │  │  └─ aws:ec2:RouteTableAssociation  eksNetwork-public-0         create
 +   │  ├─ awsx:x:ec2:Subnet                 eksNetwork-private-1        create
 +   │  │  ├─ aws:ec2:RouteTable             eksNetwork-private-1        create
 +   │  │  ├─ aws:ec2:Subnet                 eksNetwork-private-1        create
 +   │  │  └─ aws:ec2:RouteTableAssociation  eksNetwork-private-1        create
 +   │  └─ awsx:x:ec2:InternetGateway        eksNetwork                  create
 +   │     └─ aws:ec2:InternetGateway        eksNetwork                  create
 +   ├─ awsx:x:ec2:NatGateway                eksNetwork-1                create
 +   │  ├─ aws:ec2:Eip                       eksNetwork-1                create
 +   │  └─ aws:ec2:NatGateway                eksNetwork-1                create
 +   ├─ aws:ec2:Vpc                          eksNetwork                  create
 +   ├─ aws:ec2:Route                        eksNetwork-public-0-ig      create
 +   ├─ aws:ec2:Route                        eksNetwork-public-1-ig      create
 +   ├─ aws:ec2:Route                        eksNetwork-private-0-nat-0  create
 +   └─ aws:ec2:Route                        eksNetwork-private-1-nat-1  create

Resources:
    + 31 to create

Do you want to perform this update? yes
Updating (dev):

     Type                              Name                  Status                  Info
 +   pulumi:pulumi:Stack               eks-cluster-dev       created
 +   ├─ awsx:x:ec2:NatGateway          eksNetwork-0          created
 +   │  └─ aws:ec2:Eip                 eksNetwork-0          **creating failed**     1 error
 +   ├─ awsx:x:ec2:NatGateway          eksNetwork-1          created
 +   │  └─ aws:ec2:Eip                 eksNetwork-1          **creating failed**     1 error
 +   ├─ awsx:x:ec2:Vpc                 eksNetwork            created
 +   │  ├─ awsx:x:ec2:Subnet           eksNetwork-private-1  created
 +   │  ├─ awsx:x:ec2:Subnet           eksNetwork-public-1   created
 +   │  ├─ awsx:x:ec2:InternetGateway  eksNetwork            created
 +   │  ├─ awsx:x:ec2:Subnet           eksNetwork-private-0  created
 +   │  └─ awsx:x:ec2:Subnet           eksNetwork-public-0   created
 +   └─ aws:ec2:Vpc                    eksNetwork            created

Diagnostics:
  aws:ec2:Eip (eksNetwork-0):
    error: Plan apply failed: 1 error occurred:

    * creating urn:pulumi:dev::eks-cluster::awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::eksNetwork-0: Error creating EIP tags: InvalidID: The ID '54.244.113.158' is not valid
    	status code: 400, request id: 4decbdac-c1cf-4b76-851d-4a9b4dd6b9c3

  aws:ec2:Eip (eksNetwork-1):
    error: Plan apply failed: 1 error occurred:

    * creating urn:pulumi:dev::eks-cluster::awsx:x:ec2:NatGateway$aws:ec2/eip:Eip::eksNetwork-1: Error creating EIP tags: InvalidID: The ID '54.214.49.61' is not valid
    	status code: 400, request id: 5a75e1e4-6523-450a-8767-65c0e44863c3

Resources:
    + 10 created

Duration: 9s

Permalink: https://app.pulumi.com/ggilmore/eks-cluster/dev/updates/5
error: update failed
```

**Comment by CyrusNajmabadi** [comment]
Hey @ggilmore That's not good!  But at least we've eliminated EKS from things.  Would you be willing to join pulumi-community.slack.com so we could try to figure this out together?

Thanks!

**Comment by ggilmore** [comment]
Resolved over slack and fixed in https://github.com/pulumi/pulumi-awsx/commit/1af41131523966f1e25275082b891f85a29d2431. Thanks!
