### ISSUE TITLE
External Listener not changing security group rules on ALB security group

### ISSUE THREAD

**Issue by Blitz2145** [pulumi/pulumi-awsx#197]
On an external ALB, the following code, does not modify the ALB security group rules, but the docs suggest it should.
```
  const myListener = myTargetGroup.createListener(
    "my_redirect",
    {
      port: 80,
      external: true,
      protocol: "HTTP",
      defaultAction: {
        type: "redirect",
        redirect: {
          port: "443",
          protocol: "HTTPS",
          statusCode: "HTTP_301"
        }
      }
    }
  );
```

package.json
```
{
  "name": "typescript",
  "devDependencies": {
    "@types/node": "10.14.3"
  },
  "dependencies": {
    "@pulumi/aws": "0.17.1",
    "@pulumi/awsx": "0.17.3",
    "@pulumi/pulumi": "0.17.2"
  }
}
```
NOTE: Still happens on 0.18 releases of aws/awsx, just tried them out just in case.

**Comment by Blitz2145** [comment]
Looked some more into this, this line seems to be the problem, https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/elasticloadbalancingv2/loadBalancer.ts#L35 . ALBs will get created with the default VPC security group, if you pass `[]` which is the case when no securityGroups are passed as args. But Pulumi then never tracks this resource and so the createListener method never has a securityGroup to append ingress/egress rules to. Testing a fix to possibly PR but not sure if I'll get to it.

**Comment by CyrusNajmabadi** [comment]
hey @Blitz2145 I have a fix for this here: https://github.com/pulumi/pulumi-awsx/pull/202.

Note: in the meantime, you should be able to workaround the issue by creating/importing and providing a SecurityGroup when creating your ALB.

**Comment by Blitz2145** [comment]
@CyrusNajmabadi Thanks for the fix. The workaround doesn't work, because even if I pass in a securitygroup as such:
```
  const albSecurityGroup = new aws.ec2.SecurityGroup("blah_load_balancer_security_group", {
    description: `Default security group for ALB`,
  });

  // Create an elastic network listener to listen for requests and route them to the container.
  const networkLoadBalancer = new awsx.elasticloadbalancingv2.ApplicationLoadBalancer(
    "blah_load_balancer",
    {
      external: true,
      securityGroups: [
          albSecurityGroup.id
      ]
    }
  );

```
The egress rules for the `albSecurityGroup` are not added to it. I was able to workaround that by specifying an egress rule allowing all outbound traffic, after which everything worked. So there's probably some more logic missing to add egress rules for external ALBs by default.

**Comment by CyrusNajmabadi** [comment]
>The egress rules for the albSecurityGroup are not added to it. I was able to workaround that by specifying an egress rule allowing all outbound traffic, after which everything worked. So there's probably some more logic missing to add egress rules for external ALBs by default.

@Blitz2145 I would say that's by design.  I don't think we intend to make egress rules here on your behalf.  We only make ingress rules so that the target is reachable from the outside.

Note that our docs do try to say this (though one sentence is mangled and needs to be fixed up):

```ts
    /**
     * If the listener should be available externally.  If this is [true] and the LoadBalancer for
     * this Listener is [external=true], then this listener is available to the entire internet.  If
     * this is [true] and the LoadBalancer is [external=false], then this listener is available to
     * everything in the LoadBalancer's VPC.
     *
     * If this is [false] then access will controlled entirely by the egress an ingress rules of the
     * security groups of the LoadBalancer.
     *
     * Defaults to [true].
     */
    external?: boolean;
```

**Comment by CyrusNajmabadi** [comment]
@Blitz2145 I think we're in a good space with #202 .   We will at least make sure you have a SecGroup.  And things will open properly so that your target is reachable from outside.  You will have to open up the reverse direction if you want.
