### ISSUE TITLE
ApiGateway should allow you to specify bucket parameters when defining static routes.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#253]
There is a wealth of bucket options that are necessary to set for PWA purposes.  For example:

```ts
    readonly website?: pulumi.Input<{
        errorDocument?: pulumi.Input<string>;
        indexDocument?: pulumi.Input<string>;
        redirectAllRequestsTo?: pulumi.Input<string>;
        routingRules?: pulumi.Input<string>;
    }>;
```

Right now we hide the bucket creation and don't give the user any facility to tweak these values.  We should make these options optionally available to the user when they create the apigateway.

**Comment by CyrusNajmabadi** [comment]
Brought to our attention by @aydrian

**Comment by aydrian** [comment]
This mostly affects the ability to hosts Single Page Apps (SPAs).

**Comment by CyrusNajmabadi** [comment]
@aydrian This has been done and will be in the next release.
