### ISSUE TITLE
Cluster should auto-scale

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#26]
_From @lukehoban on November 12, 2017 18:49_

Our `Cluster` primitive doesn't currently autoscale.  It's uses an ASG just as a way to template out VMs, but doesn't have any dynamic scaling policy applied.

We should presumably set some scaling policy (and potentially allow high-level parameterization of that).  At the very least, scaling on memory reservation seems natural, as we will hard fail to launch new containers if we don't scale with load on that metric.  

_Copied from original issue: pulumi/pulumi-cloud#209_

**Comment by lukehoban** [comment]
We'll focus on Fargate support first #410.

**Comment by lukehoban** [comment]
@CyrusNajmabadi I assume this is addressed now with the newly available primitives?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I assume this is addressed now with the newly available primitives?

Unfortunately, not really.  What we'd really want is a simple way to create auto scaling policies for an ASG.  The group is easy to make (with simple control over min/max stuff).  But, beyond that (i.e. scaling on a schedule, or in response to resource utilization) is still non-trivial..

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi-awsx/pull/229, https://github.com/pulumi/pulumi-awsx/pull/232 and https://github.com/pulumi/pulumi-awsx/pull/240

Note: this is for the new awsx.autoscaling.AutoScalingGroup and awsx.ecs.Cluster.  It doesn't work for awsx.Cluster.
