### ISSUE TITLE
Target type "lambda" missing from LB target group types

### ISSUE THREAD

**Issue by melbourne2991** [pulumi/pulumi-awsx#266]
Target type "lambda" is a valid target type that is missing from `targetGroup.d.ts` :

```
    targetType?: pulumi.Input<"instance" | "ip">;
```

Terraform reference:
https://www.terraform.io/docs/providers/aws/r/lb_target_group.html

EDIT: it seems to only be missing from awsx - you can probably close this

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi-awsx/pull/330
