### ISSUE TITLE
Support tags on all ECS services

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-awsx#271]
According to the [AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-using-tags.html#tag-resources), you should be able to tag services and task definitions. The awsx ECS resources do not have support for those right now. I believe this would require adding the `tags` property to the following interfaces: 

- `FargateService`
- `FargateTaskDefinitionArgs`

**Comment by ellismg** [comment]
I suspect we would also want to make this change to the `EC2` flavors of these interfaces.
