### ISSUE TITLE
Document which methods create resources versus re-use existing resources

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-awsx#272]
Feedback from a community member:

> However documentation awsx.ec2.Vpc.fromExistingIds for could be expanded. I am guessing that if I add my existing vpc to my stack, even if i delete my stack the vpc will be left alone? I really don't want to risk deleting our current vpc.  
> https://pulumi.io/reference/pkg/nodejs/@pulumi/awsx/ec2/#Vpc-fromExistingIds

Without going into the code the behavior of this (and similar) methods is not obvious. We should document these methods, or maybe centrally the naming/usage pattern of methods that create resources versus use existing resources as _read-only_.

**Comment by CyrusNajmabadi** [comment]
That makes sense.
