### ISSUE TITLE
Rename elasticloadbalancingv2 namespace to just elb?

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-awsx#274]
Most of our module/namespaces are the shortened abbreviation, like `ebs`, `ecr`, `ecs`, and so on. The one that sticks out here, however, is `elasticloadbalancingv2` which is very long. Should we instead call this `elbv2` or, since AFAIK v1 is "deprecated" and shouldn't be used (something the more forward-looking AWSX package can take advantage of), just `elb`?

**Comment by CyrusNajmabadi** [comment]
Good question.  This was named to match our aws resource.  But we could certainly rename the core aws resource as well.  @lukehoban Any reasons you'd be strongly opposed to this?  I certainly resonate with this feeling like an unnecessary mouthful.

**Comment by jen20** [comment]
I think I would name this `lb` rather than `elb` (which is generally used to refer to the first-generation elastic load balancers. 100% on renaming it to something that isn't so long though.

**Comment by CyrusNajmabadi** [comment]
This was fixed in https://github.com/pulumi/pulumi-awsx/pull/378
