### ISSUE TITLE
LoadBalancers seem to default to external = true

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-awsx#291]
Unless I'm missing something, it appears that LoadBalancers default `external` to `true`, despite the documentation saying that they default to `false`.

If I create one simply as

```
new awsx.elasticloadbalancingv2.NetworkLoadBalancer("web-traffic");
```

and then do an update

```
new awsx.elasticloadbalancingv2.NetworkLoadBalancer("web-traffic", { external: true });
```

there is no change to the underlying resource configs.

If I instead then change it to

```
new awsx.elasticloadbalancingv2.NetworkLoadBalancer("web-traffic", { external: false });
```

a number of things get changed in the update.

**Comment by joeduffy** [comment]
Also, a related, but slightly different question. Is it intentional that ApplicationLoadBalancers automatically open the right ports in the SecurityGroup

https://github.com/pulumi/pulumi-awsx/blob/4136dd6fbd0539b1069553a7147f0d4b92e33a4e/nodejs/awsx/elasticloadbalancingv2/application.ts#L206-L217

but NetworkLoadBalancers don't offer this same option?

**Comment by CyrusNajmabadi** [comment]
> Unless I'm missing something, it appears that LoadBalancers default external to true, despite the documentation saying that they default to false.

Docs for LoadBalancerArgs say this for me:

```
    /**
     * Whether or not the load balancer is exposed to the internet. Defaults to `true` if
     * unspecified.
     */
    external?: boolean;
```

Unfortunately, looks like that didn't copy over properly into the ALBArgs or NetworkArgs.  I can fixup the docs there, but likely we can't change the actual default due to that breaking people who just want to upgrade.

> but NetworkLoadBalancers don't offer this same option?

My understanding is that NLBs don't have security groups.  See this comment on the forums:

https://forums.aws.amazon.com/thread.jspa?threadID=263245

> As far as I understand, the NLB itself doesn't have any security group. Instead, you control access using the security groups(s) attached to the EC2 instances. The source IP address is preserved, so you work with security group configuration (and other firewalls so to speak) as if the client had connected directly to your machine. The load balancer is kind of more transparent than in the ELB/ALB case. 

Note that this is likely an area we can try to excel at making easier.  It just hasn't been done yet :)

**Comment by CyrusNajmabadi** [comment]
More docs on this here: https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-register-targets.html

> Network Load Balancers do not have associated security groups. Therefore, the security groups for your targets must use IP addresses to allow traffic from the load balancer. You cannot allow traffic from clients to targets through the load balancer using the security groups for the clients in the security groups for the targets. Use the client CIDR blocks in the target security groups instead.

**Comment by joeduffy** [comment]
Ahhh, ok. Yeah, I was reading the ALB/NLB docs, not the LB directly, which said default `false`.

The README's code sample is also a bit misleading; see https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/elasticloadbalancingv2/README.md#network-load-balancer: 

"Pass 'external: true' to make the NLB externally accessible"

**Comment by joeduffy** [comment]
@CyrusNajmabadi wrt the security group thing, I will make sure to document this gotcha. It's definitely a weird asymmetry between NLBs and ALBs that we should tell people about.

In particular, for this case, I am using the same security group used by the ALB to open up web traffic for my EC2 instance. Simply changing this to an NLB will not work, because it means the security group I'm using doesn't have that port opened up by the load balancer code, like it does with ALB.

This may actually be a problem. The security group *isn't* just about the load balancer, it's also about whatever the load balancer is targeting, and often you're trying to share the same group.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi wrt the security group thing, I will make sure to document this gotcha.

Thanks.  That's appreciated.  this is definitely a complex area, and having as many docs to help explain things is valuable.

Do you have a recommendation on how to make this stuff clearer?
