### ISSUE TITLE
why does awsx.elasticloadbalancingv2.loadbalancer use as hash for the name?

### ISSUE THREAD

**Issue by keen99** [pulumi/pulumi-awsx#296]
https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/elasticloadbalancingv2/loadBalancer.ts#L30-L38

when awsx is used to create a loadbalancer, the `name` is hashed into `shortName` and passed to aws.elasticloadbalancingv2.LoadBalancer as `name`.   

this leads to human friendly names like `371ba2bf-6d27008` and urls like `371ba2bf-6771c8d-1928391563.us-east-1.elb.amazonaws.com`

similar happens with targetGroup.

speculation would be that this is an attempt to force a url-friendly and elb-allowed name, or something on the tf side, since a pure string could exceed those limits..... but honestly I'd rather just see a failure than a gibberish URL.    This behavior basically means I can't use awsx resources in my environment.

I looked into doing a PR for this, but couldn't grok the local development environment (not to mention that I didnt look at the other language flavors) - maybe awsx needs a CONTRIBUTING.md.....      

For backwards compat, it seems like this should probably be an optional change, so something like `useNameForLbName = true` or something.   or perhaps just allow `shortName` to be passed as an override - `elbName` or something.

looking closer at aws.elb2, the autogen terraform wrapper suggests `name` is ending up at `namePrefix`.    when I pass name as name, I get `net-lb-dev-71c9ccf`  - suggesting the namearg  is ending up as namePrefix, and name is unset (hence a random suffix).   I'm not clear on the path of why that's happening though.

**Comment by CyrusNajmabadi** [comment]
Working on fix.  Sorry about this.  it's an unfortunate holdover from some code we copied over from a previous version of the library.

**Comment by CyrusNajmabadi** [comment]
> I looked into doing a PR for this, but couldn't grok the local development environment (not to mention that I didnt look at the other language flavors) - maybe awsx needs a CONTRIBUTING.md.....

I'll open a bug to help track this.  https://github.com/pulumi/pulumi/blob/master/CONTRIBUTING.md  is a starting point.  But individual repos need to point back to this, as well as add any particular specific info relevant to them.

> For backwards compat, it seems like this should probably be an optional change, so something like useNameForLbName = true or something. or perhaps just allow shortName to be passed as an override - elbName or something

Yup.  Unfortunately back-compat does mean we can't change this behavior by default.  However, my PR allows you to now be explicit about the `name:` arg passed to a LoadBalancer/TargetGroup/Listener.  We'll then respect that name as the one passed to aws unmarred.

Thanks for the issue!

**Comment by keen99** [comment]
thanks, much appreciated!

**Comment by CyrusNajmabadi** [comment]
@keen99 This has been merged in and should be in our next update of this package!  If you don't want to wait, you'll be able to reference the latest dev npm package shortly once it is built and pushed.
