### ISSUE TITLE
Deprecate and help people move off of awsx.Network

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#298]
VPC is the much richer and easier to use resource now (also with less bugs to boot).  We should deprecate `Network`, ensuring that 100% of our docs and examples now use VPC and that `Network` and our docs/readmes have enough information to help people move over.

Note that we won't remove Network.  So that existing programs continue to run.  But this will gently suggest that people move off it at a time they're comfortable with.

**Comment by lukehoban** [comment]
@CyrusNajmabadi What's the plan on this one?  I believe we have deprecated, but is there any other work remaining?

**Comment by CyrusNajmabadi** [comment]
Ideally we can at least have some of hte following:

1. have some small amount of documentation saying how to move from the old system to the new.
2. potentially make this easy programatically.  i.e. allow someone to export the data from an awsx.Network that can then be used by Vpc.fromExistingIds.

Note: 2' 'is similar to what we're discussing around the current Vpc and making it easy to move to 0.19 Vpc changes that we're thinking about.

**Comment by CyrusNajmabadi** [comment]
Closing out for now.
