### ISSUE TITLE
ECS fargate service and td timeouts

### ISSUE THREAD

**Issue by keen99** [pulumi/pulumi-awsx#300]
awsx.ecs seems to trigger the 10m timeout pretty frequently (ie, all the time for me).  a second run always self-resolves.

on new stack creation it will timeout, and when a change that requires the task definition to be replace it will also timeout.   

new creation:
``` 
+      └─ aws:ecs:Service                                     cms-dev-use2-fgservice      **creating faile    

Diagnostics:
  aws:ecs:Service (cms-dev-use2-fgservice):
    error: Plan apply failed: 1 error occurred:
    	* creating urn:pulumi:cms-dev-use2::ecs_fargate::awsx:x:ecs:FargateService$aws:ecs/service:Service::cms-dev-use2-fgservice: timeout while waiting for state to become 'true' (last state: 'false', timeout: 10m0s)
```

task update:
```
     └─ awsx:x:ecs:FargateService                              cms-dev-use2-fgservice
 ~      └─ aws:ecs:Service                                     cms-dev-use2-fgservice    **updating failed*

Diagnostics:
  aws:ecs:Service (cms-dev-use2-fgservice):
    error: Plan apply failed: 1 error occurred:
    	* updating urn:pulumi:cms-dev-use2::ecs_fargate::awsx:x:ecs:FargateService$aws:ecs/service:Service::cms-dev-use2-fgservice: timeout while waiting for state to become 'true' (last state: 'false', timeout: 10m0s)
```

```
const appService = new awsx.ecs.FargateService(namePrefix+"fgservice", {
    cluster,
    //changing a TD requires creating new and deleting old.
    //currently this WILL timeout at 10 minutes.
    taskDefinitionArgs: {
        container: {
            // image: img,
            // image: "3001app-img-" + stack_name,
            // image: "ecr-test-repo-" + stack_name,
            // image: repository.repository.name,
            image: ECRrepositoryName,
            cpu: +config.containerCpu!, /* CPU Units */
            memory: +config.containerMemory!, /* MB */
            portMappings: [ https ],
        },
    },
    desiredCount: +config.containerCount!
});
```

**Comment by crucialfelix** [comment]
For dev work you can increment a number to the end of the service:

"fgservice2" 

and it will delete and create. Faster than destroy/up.

**Comment by michaelharrisonroth** [comment]
I am having this issue as well - an increment is an option but it's not a very ideal workaround. Even if it doesn't time out, this appears to slow our builds down by 8+ minutes.

**Comment by nachomazzara** [comment]
still having this issue!

**Comment by lukehoban** [comment]
This appears to be the same issue tracked in https://github.com/pulumi/pulumi-awsx/issues/354, and that issue has more details, so I'm going to close this one out.  Note two things:
1. We have increased the timeout to `15` minutes recently, which should address some cases where this leads to failrues
2. You can pass `waitForSteadyState: false` to not wait for ECS to validate that the service update is healthy.  The endpoint for the service may not yet be serving from the new tasks immediately after the update completes in this case - but for many development use-cases that may be preferable.
3. Lastly, the fundamental source of the delays is in the design of how ECS and ALB/NLB coordinate for health checks and the defaults they use - you can adjust these to be "faster" - for example pass `deregistrationDelay: 0` on the `Target` (or a number smaller than the default `300`), and/or set `healthCheck` on the `Target` and `healthCheckGracePeriodSeconds` on the `FargateService` to allow it to register as healthy more quickly (if possible for your container). These are more complex, but have the benefit of actually speeding up how long it takes.
