### ISSUE TITLE
Consider automatic load balancing for ECS Services

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-awsx#303]
For simple ECS scenarios, I often need a stanza at the top of my program that creates a load balancer source/target. For example:

```typescript
import * as awsx from "@pulumi/awsx";

// Create a load balancer on port 80 and spin up two instances of Nginx.
const lb = new awsx.elasticloadbalancingv2.ApplicationListener("nginx", { port: 80 });
const nginx = new awsx.ecs.FargateService("nginx", {
    taskDefinitionArgs: {
        containers: {
            nginx: {
                image: "nginx",
                memory: 128,
                portMappings: [ lb ],
            },
        },
    },
    desiredCount: 2,
});

// Export the load balancer's address so that it's easy to access.
export const url = lb.endpoint.hostname;
```

It's great to have full control over such powerful building blocks -- particularly when I want to use a custom VPC, etc -- however, for the basic scenarios, the load balancer concepts can feel foreign. Similar to Kubernetes services, which often provision load balancers explicitly, we could offer a mode where we create the load balancer on behalf of the user:

```typescript
import * as awsx from "@pulumi/awsx";

// Spin up two instances of Nginx, listening on port 80.
const nginx = new awsx.ecs.FargateService("nginx", {
    taskDefinitionArgs: {
        containers: {
            nginx: {
                image: "nginx",
                memory: 128,
                loadBalancedPorts: [ 80 ],
            },
        },
    },
    desiredCount: 2,
});

// Export the load balancer's address so that it's easy to access.
export const url = nginx.loadBalancers[0].hostname;
````

Now, even in this simple example, we see some of the challenges with such an idea: how do we get the resulting load balancer's hostname? How do we make something only internal, rather than external? How do we use a custom VPC?

At the end of the day, the answer for many such questions would be "use the building blocks directly," but we can probably offer simple experiences for some of the common cases.

**Comment by CyrusNajmabadi** [comment]
Note: i think we'd need more than `loadBalancedPorts: [ 80 ],` if only to figure out if this should be an ApplicationLoadBalancer versus a NetworkLoadBalancer.  But i agree that we def need something there.  

We also have an open question on how we'd expose these resources.  They seem odd to expose directly off of Service.  In this case, i do think subclassing might be teh right way to go.  Then we'd have a component that can naturally be discoverd and also expose these sub-resources.

**Comment by joeduffy** [comment]
I agree we could support that, although I do think choosing ALB by default is a safe choice.

**Comment by CyrusNajmabadi** [comment]
How about applicationLoadBalancedPorts and networkLoadBalancedPorts?

**Comment by joeduffy** [comment]
works for me!

**Comment by crucialfelix** [comment]
Terraform also has load_balancer as a param block on ecs_service. https://www.terraform.io/docs/providers/aws/r/ecs_service.html#load_balancer-1

They note that ECS can only support one load balancer per service.

**Comment by CyrusNajmabadi** [comment]
We also have that param on our Service.  But it's slightly different in how it works.  We actually fill in that information from the data passed into the container.
