### ISSUE TITLE
Update tests to smoke-test provider-handling.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#317]
From: https://github.com/pulumi/pulumi-awsx/pull/316

> For testing this - I’d suggest we make all tests use 1st class providers and set an invalid aws:region for the default provider. That will ensure that we see immediate failures if providers are not being passed through correctly.

**Comment by lukehoban** [comment]
Not needed - lots of changes to test approach since this was opened.
