### ISSUE TITLE
Add an option to `NetworkArgs` to allow the user to specify exact AZs

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-awsx#32]
i.e. rather than just specifying a count, allow the user to specify `[ "us-east-1b", "us-east-1c" ]` or similar.

**Comment by CyrusNajmabadi** [comment]
This is supported in the new Vpc abstraction.  When you define your VpcSubnetLocation you can specify either an availabilityZone or an availableZoneId. i.e.

```ts
new Vpc("name", {
  subnets: [{
    type: "public",
    location: {
      availabilityZone: "us-east-1b",
      cidrBlock: ...
    }],
});
```

**Comment by CyrusNajmabadi** [comment]
I updated this to no longer reference 'Network'.  'Network' is deprecated and will be removed from 1.0
