### ISSUE TITLE
awsx.ec2.Vpc - "adding" private subnets to an existing subnet results in failure

### ISSUE THREAD

**Issue by keen99** [pulumi/pulumi-awsx#321]
awsx 0.18.4

"adding" private subnets to an existing vpc results in failure for duplicate subnets - order of operations issue, or failure to detect/know about existing?:

first state:
```
import * as awsx from "@pulumi/awsx";
const vpc = new awsx.ec2.Vpc("custom", {
    cidrBlock: "10.118.0.0/16",
    numberOfAvailabilityZones: 2,
    assignGeneratedIpv6CidrBlock: true,
    subnets: [{ type: "public" }],
    tags: { Name: "custom_name"},
});
```

second state:
```
import * as awsx from "@pulumi/awsx";
const vpc = new awsx.ec2.Vpc("custom", {
    cidrBlock: "10.118.0.0/16",
    numberOfAvailabilityZones: 2,
    assignGeneratedIpv6CidrBlock: true,
    subnets: [{ type: "public" }, { type: "private" }],
    tags: { Name: "custom_name"},
});
```

```
Diagnostics:
  aws:ec2:Subnet (custom-public-1):
    error: Plan apply failed: Error creating subnet: InvalidSubnet.Conflict: The CIDR '10.118.64.0/18' conflicts with another subnet
    	status code: 400, request id: 9d9dee96-6280-41c3-925c-c18820c8e416

  pulumi:pulumi:Stack (test_vpc_create-test-vpc1):
    error: update failed

  aws:ec2:Subnet (custom-public-0):
    error: Plan apply failed: Error creating subnet: InvalidSubnet.Conflict: The CIDR '10.118.0.0/18' conflicts with another subnet
    	status code: 400, request id: 860c82e0-b70f-4a1f-922f-461f31cad79f
```

a destroy/up successfully creates the public+private

**Comment by ellismg** [comment]
What is your expectation on what the above would end up doing @keen99? When creating the initial VPC, we would have assigned all the address space across the two public subsets we created (one per AZ), so making a change here would force us to change the number of addresses in each public subnet (as we need to "make room" for the addresses that will be allocated for the private subnets).

I can imagine the fact that we are computing this topology ourselves without leaving any additional room is bad, but I'm interested in hearing what you think here.  Do you find the initial behavior surprising?

**Comment by lukehoban** [comment]
See also https://github.com/pulumi/pulumi-awsx/issues/350.

**Comment by keen99** [comment]
I'd probably expect -anything- other than to have a change silent ignored. :)

the "right" thing to do, and the big reason there's a plan and review stage (imo), would be to create a state transition that produces the codified result - wipe the subnets (and everything that requires them) and recreate the world.    you're going to get a very large state change to review....

the ugly shortcut would be to complain and bail about an unsupported state change. :)   or warn, but that would require another level of interaction (changing the code again to add a force, or something).     requiring a destroy/up might be apropos.

**Comment by keen99** [comment]
(sorry, it's not actually a silent ignore and proceed - except at the review stage.  it does error.   so maybe a more friendly handling of the error case, ideally at the review stage...)

**Comment by CyrusNajmabadi** [comment]
> the "right" thing to do, and the big reason there's a plan and review stage (imo), would be to create a state transition that produces the codified result - wipe the subnets (and everything that requires them) and recreate the world. you're going to get a very large state change to review....

Note: an easy way to support this for your stack would simply be to rename the vpc.  That will cause complete destruction of the current vpc (and the downstream components), and the creation of the entirely new vpc.

**Comment by keen99** [comment]
sure, but it require fore-knowledge of the behavior of the code internals.

there are a ton of ways -around- it, but I was simply pointing out
unexpected behaviors.   changing from 1 working set of code to another
working set of code, the expectation is for it to change state and work. :)

**Comment by matthiassb** [comment]
I'd like to see this as well, all resources depending on it torn down and rebuilt

**Comment by seivan** [comment]
What's the status on this issue? 
Can you currently not add new subnets to a VPC without tearing everything down and up again? 
How would that mesh with RDS and EKS clusters? 

```ts
new awsx.ec2.Vpc("prod", {
    subnets: [
        { type: "public"},
        { type: "private"},
        { type: "isolated", name: "db"},
    ],
}, providerOpts);
```

What would happen if I added 
` { type: "isolated", name: "redis"},`? 

Sounds kinda dangerous?

**Comment by defyjoy** [comment]
```
`export const vpc_main = new awsx.ec2.Vpc("EKS-VPC", {
  cidrBlock: "10.15.0.0/16",
  subnets: [
    { type: "public", mapPublicIpOnLaunch: false },
    {
      type: "private",
      mapPublicIpOnLaunch: false,
      tags: {
        "kubernetes.io/role/internal-elb": "1",
        "kubernetes.io/cluster/PULUMI-EKS-CLUSTER-01": "shared"
      }
    },
    { type: "isolated", name: "db", mapPublicIpOnLaunch: false },
    { type: "isolated", name: "redis", mapPublicIpOnLaunch: false },
  ],

  numberOfNatGateways: 1,
  tags: {
    Name: "EKS-VPC"
  }
});


const vpcEksCidr = new aws.ec2.VpcIpv4CidrBlockAssociation("VPC-EKS-CIDR", {
  vpcId: vpc_main.id,
  cidrBlock: "100.64.0.0/16",
});`
```

Now the question is I added a new cidrBlock to existing VPC . How do I add new subnets here now ?
