### ISSUE TITLE
request:  awsx.ec2.Vpc set Name: tag by default (and on created resources)

### ISSUE THREAD

**Issue by keen99** [pulumi/pulumi-awsx#322]
awsx 0.18.4

by default, `awsx.ec2.Vpc` doesnt set the Name: tag on the vpc.   I'd love to see that done by default instead of having to pass `tags: { Name: "custom_name"},` explicitly.

similarly, some resources created don't set Name tags at all, and one can't (apparently?) be passed from creation - IGW, DHCP option sets, route tables, ACL,

subnets, NGW, and EIPs, however, do get a Name tag created. :)

simple repro code:
```
import * as awsx from "@pulumi/awsx";
const vpc = new awsx.ec2.Vpc("custom", {
    cidrBlock: "10.118.0.0/16",
    numberOfAvailabilityZones: 2,
    assignGeneratedIpv6CidrBlock: true,
    subnets: [{ type: "public" }, { type: "private" }],
});```

**Comment by lukehoban** [comment]
Related: https://github.com/pulumi/pulumi-awsx/issues/306.

**Comment by stack72** [comment]
@jkodroff i believe we now create the Name tag by default on the resources as part of our recent rewrite, correct?

**Comment by lukehoban** [comment]
> i believe we now create the Name tag by default on the resources as part of our recent rewrite, correct?

Confirmed that we do with the 1.0.0-beta releases.
