### ISSUE TITLE
Document component design decisions.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#334]
This is just a draft issue for now to keep track of things until there is time to actually go flesh this all in.

1. any functions that call .get must accept a 'name' in order ot ensure that duplicate reads don't cause name collisions.
2. all child resources created by a component (or created using an instance method of a component) should be parented by default by that component.  This ensures proper provider-passing.

**Comment by lukehoban** [comment]
We can track this in https://github.com/pulumi/home/issues/146.
