### ISSUE TITLE
User-facing APIs which call `.get` internally must accept a `name` parameter

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#335]
A user wrote code like this:

```ts
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

export const vpcs: any = {};
for (const profile of ["bf-root", "bf-dev1"]) {
  const provider = new aws.Provider(`provider-${profile}`,
    { region: "eu-central-1", profile: profile });

  const vpc = awsx.ec2.Vpc.getDefault({ provider: provider });

  // Export a few interesting fields to make them easy to use:
  vpcs[profile] = {
    vpcId: vpc.id, vpcPrivateSubnetIds: vpc.privateSubnetIds,
    vpcPublicSubnetIds: vpc.publicSubnetIds
  }
}
```

The call to `awsx.ec2.Vpc.getDefault({ provider: provider })` leads to `Duplicate resource URN 'urn:pulumi:main::aws-infra::awsx:x:ec2:Vpc::default-vpc'; try giving it a unique name`.

This is because `getDefault` internally calls `.get()` with a fixed name.  Which means it cannot correctly be called multiple times (technically, it does some caching to try to address this today - but that cannot work with multiple different providers as intentded here).

We already have a rule that any API which creates resources must accept a required `name` parameter that it derives names for resources it creates from.  We should also have a rule that any API which calls `.get()` similarly accepts a required `name` parameter.

For this specific case - to avoid a breaking change here - we could provide two overloads - `()` and `(name: string, opts?: ResourceOptions)`.

**Comment by CyrusNajmabadi** [comment]
Have audited awsx and fixed all issues here in https://github.com/pulumi/pulumi-awsx/pull/347.

Note: we believe that Vpc.getDefault should be slightly different.  It doesn't actually take a name.  Rather, we can figure out the name it should have by virtue of getting the real name of the default vpc in that region.  We then just give the Vpc that name.  This also has the benefit of allowing us to return the same Vpc instance after successive calls.
