### ISSUE TITLE
ECS task definition defaults (logs, taskRole)

### ISSUE THREAD

**Issue by Igorbek** [pulumi/pulumi-awsx#344]
Hi,

It seems there're some cases when certain parameters allowed to be omitted in ECS task definitions but Pulumi still creates default resources.

For example, `container.logConfiguration` is allowed to be 'none', but Pulumi does not allow this value in its type (provider). To work this around I use `null!` (damn-operator) as a value.

While `logConfiguration` can be worked around, it seems I cannot create `awsx.ecs.TaskDefinition` without assigned IAM role (`taskRole`). It always tries to create one.
However, AWS totally allows to have task definitions without role assigned.

I understand the values should be omitted to opt in to default values and best practices. I suggest having some way to insist on 'empty' value, by using `null` and allowing it to be a valid type:

```ts
new awsx.ecs.EC2TaskDefinition('task', {
    taskRole: null, // allow null and do not create default iam role
    container: {
        logConfiguration: null // allow to not have logging
    }
})
```

**Comment by CyrusNajmabadi** [comment]
This is definitely something we can support.  However, it has some interesting implications for later things like python support.  It's unclear how python (or any other language) could indicate "i want the default" vs. "i want nothing".  Will have to noodle on this some more...

**Comment by Igorbek** [comment]
In the meantime, before the decision on that, do you have any advice on how to address this right now with `taskRole`? Is it possible to skip creation a default one?

**Comment by CyrusNajmabadi** [comment]
Yes.  it's a little dirty, but just pass in `{}`.  If TS complains, just do something like `<aws.iam.Role>{}` or `<aws.iam.Role><any>{}`. That will get us to not actually create anything, and it will pass along nothing to the underlying TaskDefinition whne creating it.

**Comment by Igorbek** [comment]
Thanks, that worked for IAM roles.
It seems it doesn't work for `logConfiguration`. I passed `{}` and `{ logDriver: 'none' }` and `{ logDriver: null! }`. In all cases it creates `aws:cloudwatch:LogGroup` resource for the task definition.

**Comment by CyrusNajmabadi** [comment]
For your specific containers, you need to pass `logConfiguration: {}` to not have our default behavior.

**Comment by Igorbek** [comment]
Thank you @CyrusNajmabadi 
Actually `{}` did not work, as validation failed (`logDriver` is missing). So I passed `{ logDriver: 'none' as any }`.
Also I used `logGroup: {}` for task definition itself.

**Comment by CyrusNajmabadi** [comment]
Glad it worked out for you :)

**Comment by Igorbek** [comment]
Should we keep the issue open for tracking the feature request to explicitly have ability to specify 'none' instead of 'default' behavior?

**Comment by CyrusNajmabadi** [comment]
Yup. I think we need an answer here :)  it may be as simple as something like `pulumi.none` where that's defined as `export const none: any = { __isPulumiNone: true };`   You could then pass that in in specific areas and we would check for it.

**Comment by Igorbek** [comment]
@CyrusNajmabadi I'm not sure if something changed, but it seems passing `logGroup: {} as any` doesn't work, and produces an exception:

```
TypeError: res.getProvider is not a function
    at Object.getRegion (./node_modules/@pulumi/utils.ts:125:38)
    at Object.computeContainerDefinition (./node_modules/@pulumi/ecs/container.ts:37:26)
    at computeContainerDefinitions (./node_modules/@pulumi/ecs/taskDefinition.ts:258:25)
    at new TaskDefinition (./node_modules/@pulumi/ecs/taskDefinition.ts:75:38)
    at new EC2TaskDefinition (./node_modules/@pulumi/ecs/ec2Service.ts:41:9)
    at Object.<anonymous> (./index.ts:27:24)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module.m._compile (./node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.require.extensions.<computed> [as .ts] (./node_modules/ts-node/src/index.ts:442:12)
```

it seems `logGroup` is being created unconditionally. You either have to have it or it's gonna create it.

**Comment by CyrusNajmabadi** [comment]
Yup!  I can see why that would not work now.  Will see if i can find a way to fix this.
