### ISSUE TITLE
1.0 Work for @pulumi/awsx

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#366]
Tracking bug for all the v1.0 work for awsx:

- [ ] Update `Vpc` to not consume entire cidr block: https://github.com/pulumi/pulumi-awsx/issues/350
- [ ] Update `Vpc` to follow more of aws defaults/best practices: https://github.com/pulumi/pulumi-awsx/issues/350
- [ ] Remove `Network`/`Cluster` entirely.  Consider docs on how to try to migrate from them to current abstractions.  https://github.com/pulumi/pulumi-awsx/pull/371
- [ ] Review `apigateway.Api` for current awsx patterns.  ensure it is extensible enough (i.e. you are not blocked when you need to go past our defaults).  Add support (or make sure users have some mechanism) to implement all (or the most popular) aws integrations (like kinesis).
- [x] rename `elasticloadbalancingv2` to one of `elb`, `lb` or `elbv2`.  Use aliases to keep things from breaking.
- [x] Decide on pattern (and implement through awsx) to allow users to opt out of defaults.  i.e. passing `null` instead of `undefined` to say: "don't do anything here, not even your default helpful behavior".
- [ ] Decide on a consistent set of default tags we should try to apply uniformly to all awsx resources.  
- [ ] Clean up autoscaling group.  Right now we leak out far too much of our underlying dependence on cloudformation.  We should try to make that internal as much as possible.  

Issues to consider for 1.0.  To review with team:

1. https://github.com/pulumi/pulumi-awsx/issues/361 - Allow full control of security groups for ApplicationListener
2. https://github.com/pulumi/pulumi-awsx/issues/303 - Consider automatic load balancing for ECS Services
3. https://github.com/pulumi/pulumi-awsx/issues/286 - Allow configuring DHCP Options on awsx.ec2.Vpc
4. https://github.com/pulumi/pulumi-awsx/issues/285 - Allow adding VPC Endpoints to awsx.ec2.Vpc

**Comment by CyrusNajmabadi** [comment]
Tagging @ellismg @pgavlin for visibility.

**Comment by CyrusNajmabadi** [comment]
I think all of the above could fit apprx. into a sprint's worth of time.

**Comment by lukehoban** [comment]
Let's focus on non-breaking correctness work here for 1.0.  The more significant API design changes (or enhancements) can be 1.1 or 2.0.

**Comment by CyrusNajmabadi** [comment]
Agreed.

**Comment by lukehoban** [comment]
Closing this out for now - the key pieces of work are tracked by separate issues.
