### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by unthought** [pulumi/pulumi-awsx#369]
https://github.com/pulumi/pulumi-awsx/blob/25320b1d6e8c54eb4e9b674b2ca1450a222849a0/nodejs/awsx/ec2/securityGroup.ts#L26

Shouldn't this be EgressSecurityGroupRule?

**Comment by CyrusNajmabadi** [comment]
THanks.  Fixed back in https://github.com/pulumi/pulumi-awsx/pull/468
