### ISSUE TITLE
Travis tests failing

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#384]
We're seeing new failures in master - apparently related to a new `us-west-2d` region.  We'll need to update test cases.

```
[ odejs/examples/alb/ec2Instance ]     error: Plan apply failed: Error launching source instance: Unsupported: Your requested instance type (t2.micro) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c.
```

**Comment by stack72** [comment]
Yeah this is exactly as I was thinking - t2.micro doesn't work in us-west-2d

<img width="1676" alt="Screenshot 2019-08-13 at 14 14 06" src="https://user-images.githubusercontent.com/227823/62937227-ab875400-bdd4-11e9-98e4-0ce4b0be500f.png">
