### ISSUE TITLE
awsx.ec2.AnyIPv6Location has bad ipv6CidrBlocks

### ISSUE THREAD

**Issue by jonburs** [pulumi/pulumi-awsx#387]
The block should be "::/0" instead of "::0/0". This causes planning to fail for any security group rule that makes use of AnyIPv6Location.

error: aws:ec2/securityGroupRule:SecurityGroupRule resource 'redacted' has a problem: "ipv6_cidr_blocks.0" must contain a valid network CIDR, got "::0/0"

```
export class AnyIPv6Location implements SecurityGroupRuleLocation {
    public readonly ipv6CidrBlocks = ["::0/0"];
}
```

**Comment by CyrusNajmabadi** [comment]
Thanks for letting us know @jonburs! In the meantime, you should be able to pretty easily workaround this by just passing along `{ ipv6CidrBlocks: ["::/0"] }` in place of `new AnyIPv6Location()`.

**Comment by CyrusNajmabadi** [comment]
Thanks for the report @jonburs .  this will be included in an upcoming `@pulumi/awsx` release!
