### ISSUE TITLE
Expose CloudWatch logging and endpointConfiguration on awsx.apigateway

### ISSUE THREAD

**Issue by loganb** [pulumi/pulumi-awsx#417]
Hello, 

I'm attempting to expose a Lambda-based API using Pulumi's `awsx.apigateway`. I've run into two limitations in the exposed API: 

- There's no way to enable CloudWatch logging
- There's no way to select `REGIONAL` for the endpoint configuration

I tried lower my code to the stock `aws.apigateway` APIs, but they are complex enough that it's not easy for a relatively inexperienced developer to user them since (AFAICT) one has to learn about Swagger to build routes.

**Comment by CyrusNajmabadi** [comment]
In https://github.com/pulumi/pulumi-awsx/pull/419 i'm fixing

> 2. There's no way to select REGIONAL for the endpoint configuration

For> There's no way to enable CloudWatch logging

I'd like to get some more information from you.  In terms of logging can you not set things up like so:

```ts
// first, make your awsx.apigateway.API
const api = ...

// Now, enable logging:
 const methodSettings = new aws.apigateway.MethodSettings("settings", {
      methodPath: ...,
      restApi: api.restApi.id,
      settings: {
          loggingLevel: "INFO",
          metricsEnabled: true,
      },
      stageName: api.stage.stageName,
 });
```

Cheers!

**Comment by CyrusNajmabadi** [comment]
Fixed with https://github.com/pulumi/pulumi-awsx/pull/419

**Comment by loganb** [comment]
Thank you!

**Comment by lukehoban** [comment]
>  There's no way to enable CloudWatch logging

Note that you do also need to set an account-wide setting to provide an IAM role for API Gateway to use to write logs to CloudWatch before you can use the `MethodSettings` @CyrusNajmabadi includes above.  This is a very strange design choice from AWS to have this account-wide setting - and makes it a little less friendly to automation - but can be manage by Pulumi as well if desired using `aws.apigateway.Account` and the `cloudwatchRoleArn` property.  See also https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-logging.html#set-up-access-logging-permissions.
