### ISSUE TITLE
Support for `valueFrom` in ECSService environment

### ISSUE THREAD

**Issue by leifdalan** [pulumi/pulumi-awsx#422]
It appears as if `valueFrom` is not an accepted property on a container definition's `environment`. 

https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/ecs/container.ts#L172
https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/ecs/container.ts#L153-L160

It would be great to be able to support this to manage environment variables in containers as ASM or SSM values, specified by the AWS docs here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

**Comment by CyrusNajmabadi** [comment]
Thanks! I've opened a PR to help out here.

**Comment by CyrusNajmabadi** [comment]
@leifdalan In the meantime, you can just add the `secrets: [ ... ]` property to your container definition.  TS may complain, but teh core pulumi runtime will be fine with this and will pass the values along.
