### ISSUE TITLE
awsx.ecs.FargateTaskDefinition always creates a new log group even when container.logConfiguration is specified

### ISSUE THREAD

**Issue by praneetloke** [pulumi/pulumi-awsx#435]
I am actually not sure if this is an intended behavior or an actual issue, but I couldn't find anything  that recommends to use the `logGroup` property on the task definition instead of specifying the `logConfiguration` on the container itself. So if for some reason I wanted to specify individual log groups for each container that is in my task definition, I wouldn't be able to.

```ts
const logGroup = new aws.cloudwatch.LogGroup("loggroup");
const myTaskDefinition = new awsx.ecs.FargateTaskDefinition(`MyTask-${pulumi.getStack()}`, {
    containers: {
        "abc": {
            image: ....,
            memoryReservation: 256,
            // Specifying this has no effect. Pulumi still creates a new log group
            // automatically using the container name as the log prefix.
            logConfiguration: pulumi.all([logGroup.id]).apply(([logGroupId]) => {
                return {
                    logDriver: "awslogs",
                    options: {
                        "awslogs-region": aws.config.region,
                        "awslogs-group": logGroupId,
                        "awslogs-stream-prefix": "mylogprefix",
                    },
                } as aws.ecs.LogConfiguration;
            }),
        },
    },
    logGroup: logGroup, // This works, though.
});
```
Also on a side note, I think the `options` property values should take `pulumi.Output<string>` instead of just `string`. It would be more convenient. (I can open a separate issue for it if you'd like.)

**Comment by CyrusNajmabadi** [comment]
hey @praneetloke from the docs:

```ts
    /**
     * Log group for logging information related to the service.  If `undefined` a default instance
     * with a one-day retention policy will be created.  If `null`, no log group will be created.
     */
```

Does that approach not work for you?

**Comment by CyrusNajmabadi** [comment]
> Also on a side note, I think the options property values should take pulumi.Output<string> instead of just string. It would be more convenient. (I can open a separate issue for it if you'd like.)

Yup, that would be a good issue for pulumi/aws.  It should basically say that ContainerDefinition should be 'input-ized'.

**Comment by praneetloke** [comment]
> Does that approach not work for you?

Using the `logGroup` property on the task definition worked just fine for me. I guess I am not sure if there is a use case for wanting to specify the `logConfiguration` individually for each container definition in a task definition? It just seems that if I am allowed to set that property, then the container should use that log configuration and not the `logGroup` of the task definition., whatever the reason the user might have for doing that.

**Comment by praneetloke** [comment]
> Yup, that would be a good issue for pulumi/aws. It should basically say that ContainerDefinition should be 'input-ized'.

Hmm I think the problem is actually with the `LogConfiguration` interface, no?

https://github.com/pulumi/pulumi-aws/blob/94fac5e77078be7aaff7a64d4fe1dad409dfc7af/sdk/nodejs/ecs/container.ts#L149-L153

**Comment by CyrusNajmabadi** [comment]
> Hmm I think the problem is actually with the LogConfiguration interface, no?

'Inputizing' ContainerDefinition would transitively impact LogConfiguration :)   My point is we'd want to do it all, not just that particular property.

**Comment by praneetloke** [comment]
> 'Inputizing' ContainerDefinition would transitively impact LogConfiguration :) My point is we'd want to do it all, not just that particular property.

Ah roger that. I'll open an issue there.

**Comment by lukehoban** [comment]
This was addressed as part of overall inputizing container definitions.
