### ISSUE TITLE
Latest version not published to NPM

### ISSUE THREAD

**Issue by Blitz2145** [pulumi/pulumi-awsx#436]
v0.18.12 is the last version on npm, but changelog has v0.18.13 , perhaps it could be published.

https://github.com/pulumi/pulumi-awsx/blob/master/CHANGELOG.md#01813-2019-10-15

**Comment by CyrusNajmabadi** [comment]
Looks like the build to push this to npm failed.  Rerunning.

**Comment by CyrusNajmabadi** [comment]
Build is no available here: https://www.npmjs.com/package/@pulumi/awsx/v/0.18.13

Thanks for letting us know!

**Comment by ericrudder** [comment]
*now available ...
