### ISSUE TITLE
awsx.ecs.EC2TaskDefinition has still no `family` field

### ISSUE THREAD

**Issue by yuichiro12** [pulumi/pulumi-awsx#439]
related to #432 

Hi. Thanks to you, we can now pass `family` field to `awsx.ecs.TaskDefinition`.
It's better to be able to pass `family` field also to `awsx.ecs.EC2TaskDefinition`.
My suggestion is adding `family` field here.
https://github.com/pulumi/pulumi-awsx/blob/fb583dbd078692706681884a4ebe5e7212049962/nodejs/awsx/ecs/ec2Service.ts#L123-L192

**Comment by yuichiro12** [comment]
Seemingly constructor can be as it is, since `EC2TaskDefinition` extends `TaskDefinition` and in `EC2TaskDefinition` constructor, `EC2TaskDefinitionArgs` is copied and is passed to parent's constructor directly here.
https://github.com/pulumi/pulumi-awsx/blob/d927a06d731321240842b4f1eeccb806b6ec90c5/nodejs/awsx/ecs/ec2Service.ts#L32-L41

**Comment by stack72** [comment]
Hi @yuichiro12 

Are you saying that all you want is:

```
diff --git a/nodejs/awsx/ecs/ec2Service.ts b/nodejs/awsx/ecs/ec2Service.ts
index b404d64..3e6b86b 100644
--- a/nodejs/awsx/ecs/ec2Service.ts
+++ b/nodejs/awsx/ecs/ec2Service.ts
@@ -154,6 +154,11 @@ export interface EC2TaskDefinitionArgs {
      */
     taskRole?: aws.iam.Role;

+    /**
+     * An optional family name for the Task Definition. If not specified, then a suitable default will be created.
+     */
+    family?: pulumi.Input<string>;
+
     /**
      * The execution role that the Amazon ECS container agent and the Docker daemon can assume.
      *
(END)
```

and that would satisfy your needs as we pass the args to the TaskDefinition?

Paul

**Comment by yuichiro12** [comment]
@stack72 
Exactly.

**Comment by yuichiro12** [comment]
Thank you.

**Comment by stack72** [comment]
@yuichiro12 I will speak to the rest of the team and see if we can cut a release of this tonight :)

**Comment by yuichiro12** [comment]
I’d love that! You Pulumi developer team always do excellent job😆
