### ISSUE TITLE
AWSX ECS resources don't support repositoryCredentials

### ISSUE THREAD

**Issue by lukemundy-vgw** [pulumi/pulumi-awsx#443]
it's currently not possible to create an ECS service using AWS Crosswalk if the Docker image for your service resides in a private registry.

The interface for `Container` in the base [AWS library](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/aws/ecs/#RepositoryCredentials) has a `repositoryCredentials` property which allows you to supply a path to a Secrets Manager path containing credentials for authenticating with a private container registry as per the [AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html).

However, there is no reference to this property anywhere in the AWS Crosswalk source code and I've been unable to find an easy way to add it myself. It appears the only option for creating ECS services using container images in private registries is to forgo using AWS Crosswalk and using the base resources in the AWS provider library.

**Comment by stack72** [comment]
Hi 

So, we currently do have support for this but it doesn't look like it's so straightforward to see in our docs:

* ecs.TaskDefinition has a parameter called `Containers` of type ecs.Containers

as part of that `Containers` parameter, there is an input called `repositoryCredentials` which is of type `aws.ecs.RepositoryCredentials`

That should get you what you want to do? 

Paul

**Comment by lukemundy-vgw** [comment]
Yes, it's possible to create a task definition with `repositoryCredentials` using the resources defined by the AWS provider, but not from the AWS Crosswalk resources. 

AWS Crosswalk, as far as I can tell, doesn't support the `repositoryCredentials` option in any resources it defines.

`aws.ecs.TaskDefinition` _does_ support `repositoryCredentials`

however,

`awsx.ecs.TaskDefinition` does not. Although it contains an instance of `aws.ecs.TaskDefinition`, it is a readonly property (in typescript, at least) and the only way to customise it on creation is through the `awsx.ecs.TaskDefinitionArgs` type, which does not contain a `repositoryCredentials` property.

I think the fix would just be to extend the `awsx.ecs.TaskDefinitionArgs` type to include that property and pass it into the underlying `aws.ecs.TaskDefinition`, however I'm not really sure how to go about doing that.

**Comment by stack72** [comment]
Hi @lukemundy-vgw 

Can you show me what you think the code would look like for this? I am trying to get my head around the API that you are looking at

thanks

Paul

**Comment by CyrusNajmabadi** [comment]
> However, there is no reference to this property anywhere in the AWS Crosswalk source code

I'm a little confused by that statement.  We have: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/#Container-repositoryCredentials

Isn't that what you're looking for?  Thanks! :)

**Comment by lukemundy-vgw** [comment]
> I'm a little confused by that statement. We have: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/#Container-repositoryCredentials
> 
> Isn't that what you're looking for? Thanks! :)

Yes, thats exactly it! I was very confused for a bit too though, because I distinctly remember searching the AWSX docs for this and not finding it. I also remember running `grep -ir repositoryCredentials` over `node_modules/@pulumi/awsx` which returned nothing...

So I ran the grep again just now, still nothing (i've got v0.18.13 installed). Still scratching my head, I then followed the link from the docs to the source code and had a look at [the git blame](https://github.com/pulumi/pulumi-awsx/blame/5b247e093ed7e8a789c4a34663a5ef8a3a5acef3/nodejs/awsx/ecs/container.ts#L605) for that line and it looks like @lukehoban added it a couple days after I opened this issue ([commit 560193239](https://github.com/pulumi/pulumi-awsx/commit/560193239d3ba2dabc5bf45060debc3d4740f1f5)) for v0.18.14 - mystery solved 😅 

So looks like this issue has already been fixed and creating this issue was just unfortunate timing. Thanks for your help! Sorry if I wasted any of your time. 👍

**Comment by lukehoban** [comment]
Great to hear - sorry I missed closing out this issue when we made that fix - will close it out now!

**Comment by CyrusNajmabadi** [comment]
> Yes, thats exactly it! I was very confused for a bit too though, because I distinctly remember searching the AWSX docs for this and not finding it. I also remember running grep -ir repositoryCredentials over node_modules/@pulumi/awsx which returned nothing...

Ah... so here's why you saw nothing:  We have  model where we basically don't try to *re-specify* all the data fields at each "layer".  i.e. unless awsx does something *special* with this field, you won't see it show up.  This happens because we simply copy all the data over verbatim with code like `{ ...args, otherVal: x, otherVal2: y }`.  So doing a direct search won't necessary find these things.

In this case, `repositoryCredentials` is defined at the `aws` (not `awsx`) layer, so it shows up there, but is just passed along untouched in the awsx layer. 

I can def see how that could be confusing when trying to directly look for something.  Glad we could get this cleared up!

**Comment by lukehoban** [comment]
> In this case, repositoryCredentials is defined at the aws (not awsx) layer, so it shows up there, but is just passed along untouched in the awsx layer.

Interestingly (and perhaps unfortunately) this is not quite true - I needed to add this in both the AWS and AWSX layers.  See https://github.com/pulumi/pulumi-awsx/blob/560193239d3ba2dabc5bf45060debc3d4740f1f5/nodejs/awsx/ecs/container.ts#L605.
