### ISSUE TITLE
[awsx.ecs.Cluster] cannot pass `securityGroups` to createAutoScalingGroup

### ISSUE THREAD

**Issue by yuichiro12** [pulumi/pulumi-awsx#444]
Hi, while I'm creating AutoScalingGroup from awsx.ecs.Cluster, I noticed that  no securityGroups are attached to it. My failure case is below. I tried passing `awsx.ec2.SecurityGroup` and security group id (string), but both of them failed.
Instead, a default security group are created and attached.

```index.ts
   // cluster is `awsx.ecs.Cluster`
    cluster.createAutoScalingGroup(`asg-${this.name}-${this.stack.project}-${this.appEnv}`, {
      vpc: this.stack.vpc,
      subnetIds: this.stack.vpc.publicSubnetIds,
      templateParameters: {
        minSize: 1,
        maxSize: 3,
      },
      targetGroups: [targetGroup],
      launchConfigurationArgs: {
        // none of these security groups will be attached
        securityGroups: [
          awsx.ec2.SecurityGroup.fromExistingId("vpc-base", "sg-XXXXXXX", {vpc: this.stack.vpc}),
          "sg-YYYYYYY",
        ],
        imageId: "ami-00ade003160e0a784",
        instanceType: "t2.medium",
        rootBlockDevice: {
          volumeSize: 30,
        },
        keyName: this.stack.keyPairName,
        ebsBlockDevices: [],
      },
    });
  }
```

Any Idea?

**Comment by yuichiro12** [comment]
FYI: 
Current workaround for this is simply create `awsx.autoscaling.AutoScalingLaunchConfiguration` separately.

**Comment by yuichiro12** [comment]
From my observation, `awsx.ecs.Cluster`'s Security Group are used and `securityGroups` passed here are completely ignored. Is it possible to merge these Security Groups?

**Comment by CyrusNajmabadi** [comment]
Yes.  This is a bug.  If you provide security groups, we should not be overriding them.  i'll fix.

**Comment by CyrusNajmabadi** [comment]
@yuichiro12 This should be addressed in the next release of `@pulumi/awsx`.  In that release we will respect any security groups you provide in the launchConfigurationArgs.  

Thanks for reporting this!

**Comment by yuichiro12** [comment]
@CyrusNajmabadi 
Today I upgraded `@pulumi/awsx` and I found my ASG created with given SecurityGroup. This is so impressive. Thank you so much.

**Comment by yuichiro12** [comment]
not merge but overwrite. that's pretty fine
