### ISSUE TITLE
Add support for ECR EventBridge events

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-awsx#451]
See https://aws.amazon.com/about-aws/whats-new/2019/11/ecr-events-now-published-to-eventbridge/

Also, should we rename the module to `eventbridge`, now that CloudWatch Events has been rebranded to EventBridge?

**Comment by jamesholmes-linktree** [comment]
There's also the bigger issue of missing Eventbridge buses as a construct, unless I'm mistaken. Shall I add an issue?

**Comment by lukehoban** [comment]
Note that this is already support in `@pulumi/aws`, via:

```ts
import * as aws from "@pulumi/aws";

const repo = new aws.ecr.Repository("foo", {});

const rule = new aws.cloudwatch.EventRule("rule", {
    eventPattern: JSON.stringify({
        source: ["aws.ecr"],
        "detail-type": ["ECR Image Action"],
    }),
});
const subscription = rule.onEvent("onECRImageAction", (ev, ctx) => console.log(JSON.stringify(ev)));

export const repoUrl = repo.repositoryUrl;
```

Pushing to the repo will now trigger the function defined above as can be seen in `pulumi logs`.

There are not strongly typed event detail types for the 171 specific built-in AWS event types, but users can easily define these types themselves from the types in the AWS docs of the EventBrdige schema registry.  The generic callback event payload for EventBridge is available for `ev` above - by with a generically typed `detail` field that must be processed in an event specific way.  While we might be able to to some TypeScript tricks to be helpful here, a multi-language solution will likely need to be at about the same level of richness as the current support.

> Also, should we rename the module to eventbridge, now that CloudWatch Events has been rebranded to EventBridge?

The types involved are still in the `cloudwatch` module in the `@pulumi/aws` package.  The corresponding resources are in the `awsnative.events.Rule` module in the AWS Native provider.

**Comment by lukehoban** [comment]
After some more thought, going to close this out based on the above notes.  The stronger typing might make sense to add separately, but is definitely not necessary to use this, and isn't a "simple" extension of what `@pulumi/aws` or `@pulumi/awsx` do today.  The renaming of the package is something I don't expect we'll do proactively in `@pulumi/aws` - and it is already "correctly" named in AWS Native.
