### ISSUE TITLE
Design patterns for aws-infra components

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#47]
For tuesday design meeting.

Ideas with examples.  When creating a component that enhances an AWS resource, subclassing provides a mechanism to augment and improve on the resource.  This is the approach we took for CallbackFunction (which is-a LambdaFunction).  For example:

```ts
export declare abstract class ClusterTaskDefinition extends aws.ecs.TaskDefinition {
    readonly cluster: module.Cluster;
    readonly logGroup: aws.cloudwatch.LogGroup;
    readonly containers: Record<string, module.ContainerDefinition>;
    readonly taskRole: aws.iam.Role;
    readonly executionRole: aws.iam.Role;
```

Benefits: 
1. Instances follow an is-a relationship.  Code that needs to take an aws.ecs.Cluster can take instances of the subtype.
2. No extra pulumi resource needed to wrap raw AWS resource.  Ancillary benefit of this is no need to do things like have code that does `cluster.cluster`.  
3. All expected Output properties can be easily accessed off the instance.
4. Rich auxiliary resources can be easily exposed. 

Cons: 
1. parenting relationship can be confusing.  For example, when creating a rich component that needs to create other resources up front, parenting of these resources is not associated with the expected resource.

--

Construction of one of these subtypes happens by feeding in an args type that is created with the following pattern:

```ts
export declare type ClusterTaskDefinitionArgs = utils.Overwrite<aws.ecs.TaskDefinitionArgs, {
    ...
```

Just as the component type subclasses the AWS type, the argument type is related to the AWS argument type.  We use 'Overwrite' to both add new properties, change existing properties, or remove properties altogether.  For example:

```ts
export declare type ClusterTaskDefinitionArgs = utils.Overwrite<aws.ecs.TaskDefinitionArgs, {
    /** Not used.  The pulumi resource name will be used for this. */
    family?: never;
    /** Not used.  Provide  [containers] instead. */
    containerDefinitions?: never;
```

'never' properties are how we remove properties that should not longer be provided.  These are often for properties we can provide entirely ourselves (like passing `launchType: "FARGATE"` for FargateServices), or where we can provide a better a better shaped programming model.  For example, `containerDefinitions` is an `Input<string>`.  we want to give a strong type there.

Adding new properties can be done simply like so:

```ts
export declare type ClusterTaskDefinitionArgs = utils.Overwrite<aws.ecs.TaskDefinitionArgs, {
...
    /**
     * All the containers to make a ClusterTaskDefinition from.  Useful when creating a
     * ClusterService that will contain many containers within.
     */
    containers: Record<string, module.ContainerDefinition>;
```

Properties should be changed to be optional if we can provide a sensible default.  For example:
```ts 
export type ClusterAutoScalingLaunchConfigurationArgs = Overwrite<aws.ec2.LaunchConfigurationArgs, {
    ...
    /** The size of instance to launch.  Defaults to t2.micro if unspecified. */
    instanceType?: pulumi.Input<aws.ec2.InstanceType>;
```

In LaunchConfigurationArgs, 'instanceType' is required.  But we can supply something sensible, so we make the property optional.   How this is handled in code is shown in the next post.

--

When possible, if the implementation needs a resource that it can create, it should also take an optional input parameters to allow the caller to pass it in.  For example:

```ts
export declare type ClusterTaskDefinitionArgs = utils.Overwrite<aws.ecs.TaskDefinitionArgs, {
...
    /**
     * Log group for logging information related to the service.  If not provided a default instance
     * with a one-day retention policy will be created.for no log group.
     */
    logGroup?: aws.cloudwatch.LogGroup;
```

If an implementation may end up creating resources, it should expose those child resources on itself.  Using the 'logGroup' example above, this resource would be exposed as:

```ts
export declare abstract class ClusterTaskDefinition extends aws.ecs.TaskDefinition {
    ...
    readonly logGroup: aws.cloudwatch.LogGroup;
```

This ensures clients can always get at resources created under the covers.

--

When there are a set of resource properties that need to be provided/kept-in-sync, this is a good candidate for additional subclasses.  For example, users can make fargate task-definitions and ec2 task-definitions.  Each of these places additional constraints on properties.  This can be exposed like so (using the above rules):

```ts
export declare type FargateTaskDefinitionArgs = utils.Overwrite<module.ClusterTaskDefinitionArgs, {
    /** Not provided.  Defaults automatically to ["FARGATE"] */
    requiresCompatibilities?: never;
    /** Not provided.  Defaults automatically to "awsvpc" */
    networkMode?: never;
...
}>;

export declare class FargateTaskDefinition extends module.ClusterTaskDefinition {
    ...
}
```

When appropriate, these resources should expose relevant inside/outside instance APIs for consumers.  For example:

```ts
export declare class FargateTaskDefinition extends module.ClusterTaskDefinition {
...
     /** Deployment time api. Creates a service with this as its task definition.  */
    createService(name: string, args: module.FargateServiceArgs, opts?: pulumi.ResourceOptions): module.FargateService;

    /** Runtime api. Runs this task definition in this cluster once. */
    run(options?: TaskRunOptions): Promise<void>;
}
```

These instance methods both allow for powerful functionality, but they also help one easily compose powerful constructs in a simple manner.  For example, using this pattern in more locations, one can write:

```ts
    const service = awsinfra.Network.getDefault()
                                    .createCluster("mycluster2", { ... })
                                    .createFargateService("examples-nginx2", { ...
```

When creating APIs that need to consume other APIs, providing these instance methods helps with discovery.  Alternatively once can write:

```ts
    const network = awsinfra.Network.getDefault();
    const cluster = new x.Cluster("mycluster", { network: network, ... });
    const service = new x.FargateService("nginx", { cluster: cluster, ... });
```

This requires more explicit passing of data, but works well as well.

**Comment by CyrusNajmabadi** [comment]
tagging @lukehoban

**Comment by CyrusNajmabadi** [comment]
On the implementation side, the above approach leads to certain patterns that have worked well in my experiments.

First, because we are subclassing, we must call super, passing along the right shape the base type expects.  Because of this, code follows the form:

```ts
export abstract class ClusterTaskDefinition extends aws.ecs.TaskDefinition {
...
    constructor(name: string, args; ClusterTaskDefinitionArgs) {
        const logGroup = args.logGroup || new aws.cloudwatch.LogGroup(name, {
            retentionInDays: 1,
        }, opts);

        const taskRole = args.taskRole || createTaskRole(opts);
        const executionRole = args.executionRole || createExecutionRole(opts);

        const containers = args.containers;
        const exposedPortOpt = getExposedPort(name, cluster, containers);

        const containerDefinitions = computeContainerDefinitions(
            name, cluster, args, exposedPortOpt, logGroup);

        super(name, {
            ...args,
            family:  name,
            taskRoleArn: taskRole.arn,
            executionRoleArn: executionRole.arn,
            containerDefinitions: containerDefinitions.apply(JSON.stringify),
        }, opts);
```

Here we see several things of interesting:

1. The constructor can make resources, but it also will allow those resources to be passed in instead.  this allows clients to have control over those resources if they don't like our defaults.
2.  constructor calls 'super', passing in `...args`.  This allows clients to pass in all acceptable terraform/aws values for the resource.  
3. values we totally control are written at the end, ensuring the stuff we are in control of wins out.

There are cases where we want to allow clients to pass in a value, but we will also provide a default if tey do not.  For that, we use the following pattern:

```ts
        // simplified for explanation purposes:
        super(name, {
            ...args,
            instanceType: pulumi.output(args.instanceType).apply(t => t || "t2.micro"),
            rootBlockDevice: pulumi.output(args.rootBlockDevice).apply(d => d || defaultRootBlockDevice),
            ebsBlockDevices: pulumi.output(args.ebsBlockDevices).apply(d => d || defaultEbsBlockDevices),
        }, opts);
```

In these cases, we'll use the value provided by the argument, but we'll supply our own reasonable default if none is given.

**Comment by CyrusNajmabadi** [comment]
When components create defaults using complex configuration, we should also expose that configuration.  For example, many services use a default set of policies for roles they create on demand.  We should expose copies of those defaults so that others can easily call augment those defaults.   For example, TaskDefinitions have a default set of policies for their TaskRole and ExecutionRole.  We can expose this as:

```ts
// returns a copy

aws-infra.TaskDefinition.getDefaultRolePolicies(): string[]
```

this way a consumer can call in to create a TAskDefinition getting that list of policies, but augmenting by adding any more that they need.

**Comment by damned** [comment]
Hi really interested in pulumi am watching with interest :)

I do think this sort of thinking is critical to your success as the quality of your abstractions and the ability of people to easily use them is going to be really important.

Obviously i'm going to be glossing over stuff you know well, and probs missing the point, but a couple of things jumped out at me maybe worth checking out:

1) [Composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance)

I've personally used inheritance in "simple", limited depth hierarchies and seen it used to much greater depths. I'd advise some caution or vigilance as the detrimental effects (which i would summarise as lack of encapsulation reducing obviousness and leading to accidental complexity and) often seem to grow exponentially with increased depth and age of codebase.

Personally where i've used it for my own projects, I usually get to a point i wish i'd stuck to composition :)

2)  Builder pattern might be useful

I've used builder pattern a lot in setup for mid-level integration or functional tests - which i think suits the pulumi / infra component level really well.  From a quick search [this article seems to summarise its use well](http://www.ostia.be/blog/2013/06/06/using-the-builder-pattern-for-test-fixtures/).

The setup that we're always doing in those tests is about really easily creating setups with sensible defaults and then creating a myriad of overrides or compositions to test different cases, often leveraging the majority default behaviour.  I feel this is really analogous to your use case.

The `Network.getDefault().createCluster(...` snippet shows a similar pattern and i can see from other comments that composability is a concern.

One concern i have about the provide-all-at-constructor pattern is that it tends to force user code to follow a similar pattern.  Maybe even the low-level resources, being constructor-configured are leading the components to the same pattern.  However, if you consider the use of your components within a user's codebase, their still-higher-level components will require tracking of mutable state to enable options before final construction, (maybe resulting in _their_ need to follow a builder-like pattern) whereas a more builder-oriented approach gives lowest friction re-use / composition.

**Comment by melbourne2991** [comment]
@damned Just experimenting with this myself - building my own small utils library for my own use cases atm, the builder pattern does indeed feel like a really natural fit for this kind of thing. 

Take for instance the example in the readme of creating security groups:

```
const sg = new awsx.ec2.SecurityGroup(`sg`, { vpc });
SecurityGroupRule.ingress("https-access", sg,
   new awsx.ec2.AnyIPv4Location(),
   new awsx.ec2.TcpPorts(443),
   "allow https access");
SecurityGroupRule.ingress("ssd-access", sg,
   new awsx.ec2.AnyIPv4Location(),
   new awsx.ec2.TcpPorts(22),
   "allow ssh access");
```

You could instead have an api that looks like this (not that there's anything horribly wrong with the current API it's perfectly fine but to me at least the below feels more ergonomic):

```
SecurityGroupBuiilder
  .forVpc(vpc)
  .withIngressSSHFromAnyIp()
  .withIngressHttpsFromAnyIp()
  .build();
```

The beauty of the builder pattern is the implementation can still be very clear whilst also allowing for a wide range of abstractions at different levels. The implementation would look something like this:

```
withIngress(ruleName: string, args:  Omit<SecurityGroupRuleArgs, "type" | "securityGroupId">) {
  new SecurityGroupRule(ruleName, {
    securityGroupId: this.securityGroup.id,
    type: "ingress",
    ...args
  });
}

withIngressTCP(ruleName: string, args:  Omit<SecurityGroupRuleArgs, "type" | "securityGroupId" | "protocol">) {
  new SecurityGroupRule(ruleName, {
    securityGroupId: this.securityGroup.id,
    type: "ingress",
    ...args
  });
}

withIngressSSH(ruleName: string, args:  Omit<SecurityGroupRuleArgs, "type" | "securityGroupId" | "fromPort" | "toPort" | "protocol">) {
  return this.withIngressTCP(ruleName, {
    fromPort: 22,
    toPort: 22
  });
}

withIngressSSHFromAnyIp(ruleName: string, args:  Omit<SecurityGroupRuleArgs, "type" | "securityGroupId" | "fromPort" | "toPort" | "cidr_block">) {
  return this.withIngressSSH(ruleName, {
    cidr_block: ["0.0.0/0"]
  });
}
```

I find this kind of API to be really IDE friendly, as you type "wi" and immediately get a list of common use cases and if what you need isn't a common use case you fall back to a "lower level" builder method like withIngress and specify the granular details yourself.

It also makes composing different pieces of configuration dead straightforward eg:

```
withIngressWeb() {
  return this.withIngressAnyIp({
    fromPort: 80,
    toPort: 80
  }).withIngressAnyIp({
    fromPort: 443,
    toPort: 443
  })
}
```

You can take the same pattern and apply it to vpcs, roles etc quite easily eg (withSubnet, withPublicSubnet, withPolicy) etc.

**Comment by CyrusNajmabadi** [comment]
> Take for instance the example in the readme of creating security groups:
> 
> ```ts
> const sg = new awsx.ec2.SecurityGroup(`sg`, { vpc });
> SecurityGroupRule.ingress("https-access", sg,
>    new awsx.ec2.AnyIPv4Location(),
>    new awsx.ec2.TcpPorts(443),
>    "allow https access");
> ```

Note: this is slightly out of date.  You can just write `sg.createIngressRule(...)`

**Comment by CyrusNajmabadi** [comment]
I'm def intrigued by this.  The main concern i have is that there's no great way to add all the invariable methods people may want.  i.e. if you want `withIngressWeb` and we dont' have it, then you're somewhat SOL.  I thhink builders/fluent can be great.  But they don't necessarily seem to have to be part of the core programming model that we would have to support/expand ad-infinitum.

**Comment by melbourne2991** [comment]
@CyrusNajmabadi definitely true - it will never be possible to cover every use case, however if custom methods are needed you can just extend the builder:

```
export class MyCompanySecurityGroupBuilder extends SecurityGroupBuilder {
  constructor(name: stringType, args: SecurityGroupArgs) {
    super(name, args);
  }

  withIngressWeb(name: string) {
    return this.withIngress('http', {
      protocol: "tcp",
      fromPort: 80,
      toPort: 80
    }).withIngress('https', {
      protocol: "tcp",
      fromPort: 443,
      toPort: 443
    });
  }
}

const builderOutput = new MyCompanySecurityGroupBuilder("my-sec-group", {
  description: 'Security!'
})
.withIngressWeb('web-rule')
.build()
```

This is nice because if you want to contribute these methods back to Pulumi, it's literally just a copy paste away. But you're right that this doesn't _have_ to be part of the core, it could just as easily be a third party library that wraps Pulumi's core libs but I thought it was worth flagging the benefits anyway.
