### ISSUE TITLE
Travis failures in `examples`

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#482]
We saw 7 failures in our `examples` [cron job](https://travis-ci.com/pulumi/examples/jobs/275647114) on the `latest-packages` leg along the lines of:

```
[ s-thumbnailer-machine-learning ]     TypeError: Cannot read property 'getDefault' of undefined
[ s-thumbnailer-machine-learning ]         at Object.getOrCreateNetwork (/tmp/p-it-travis-job-cloud-js-t-9d28b939-461652537/node_modules/@pulumi/shared.ts:128:40)
[ s-thumbnailer-machine-learning ]         at new Task (/tmp/p-it-travis-job-cloud-js-t-9d28b939-461652537/node_modules/@pulumi/service.ts:877:25)
```

This appears to be due to https://github.com/pulumi/pulumi-awsx/pull/371.  We will likely need to lock versions used by `cloud` or update `cloud` to continue to work with new versions of this package.

We should also almost certainly only ship that breaking change in at least a minor version bump (as opposed to `0.18.5` which appears to be in progress to ship).

**Comment by CyrusNajmabadi** [comment]
Should be fixed with https://github.com/pulumi/pulumi-cloud/pull/758
