### ISSUE TITLE
Look over numberOfAvailabilityZones on ec2.vpc

### ISSUE THREAD

**Issue by seivan** [pulumi/pulumi-awsx#493]
[This](https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/ec2/vpc.ts#L330) is potentially dangerous as it could fetch different zones each time and mutate an existing VPC.

**Comment by mnlumi** [comment]
The code this links to is no longer available. There's also a reference to a merged PR that may have resolved the issue. I'm to close this as complete, but please feel to re-open if needed.
