### ISSUE TITLE
awsx.ec2.Vpc.fromExistingIds throws "TypeError: this.getData is not a function"

### ISSUE THREAD

**Issue by KonstantinRyazantsev** [pulumi/pulumi-awsx#495]
Hi all. I getting this error:

```
TypeError: this.getData is not a function
        at new Vpc (C:\projects\infra\node_modules\@pulumi\ec2\vpc.ts:276:27)
        at Function.fromExistingIds (C:\projects\infra\node_modules\@pulumi\ec2\vpc.ts:367:16)
```

```typescript
 trying to execute const vpc = awsx.ec2.Vpc.fromExistingIds("primary-vpc", { vpcId: "vpc-xxx" }, { provider: provider });
```

package.json is:
```
{
  "name": "aws-typescript",
  "devDependencies": {
    "@types/node": "^12.12.25"
  },
  "dependencies": {
    "@pulumi/aws": "1.18.0",
    "@pulumi/awsx": "0.19.0",
    "@pulumi/pulumi": "1.8.1"
  }
}
```

node version `v12.14.1`
pulumi version `v1.9.0`

I've find out that the latest stable version of awsx on which the methods works is `0.18.14` on `0.19.x` it doesn't work.

**Comment by CyrusNajmabadi** [comment]
Hrmm.   `getData` was added in v1.9.1.  Can you try that to see if it resolves things for you?  I can put that as an explicit dependency of this version of awsx as well.

**Comment by KonstantinRyazantsev** [comment]
package.json:

```javascript
{
    "name": "aws-typescript",
    "devDependencies": {
        "@types/node": "12.12.25"
    },
  "dependencies": {
    "@pulumi/aws": "1.18.0",
    "@pulumi/awsx": "0.19.1",
    "@pulumi/pulumi": "1.9.1"
  }
}
```

Still get this error:

```
error: Running program 'C:\projects\infra' failed with an unhandled exception:
    TypeError: this.getData is not a function
        at new Vpc (C:\projects\infra\node_modules\@pulumi\ec2\vpc.ts:276:27)
        at Function.fromExistingIds (C:\projects\infra\node_modules\@pulumi\ec2\vpc.ts:367:16)
        at Object.<anonymous> (C:\projects\infra\core.ts:42:36)
        at Generator.next (<anonymous>)
        at C:\projects\infra\core.ts:8:71
        at new Promise (<anonymous>)
        at __awaiter (C:\projects\infra\core.ts:4:12)
        at Object.define (C:\projects\infra\core.ts:18:12)
        at C:\projects\infra\index.ts:26:37
        at Generator.next (<anonymous>)
```

**Comment by CyrusNajmabadi** [comment]
So i do not repro this myself.  I used your package.json and just had a simple pulumi app of:

```ts
import * as awsx from "@pulumi/awsx";

const vpc = awsx.ec2.Vpc.fromExistingIds("primary-vpc", { vpcId: "our-id" });
```

And i got:

![image](https://user-images.githubusercontent.com/4564579/73318363-062f3380-41ee-11ea-9391-e882d286a0dc.png)

Is it possible you have some stale node_modules folder?  Perhaps a stale npm or yarn lockfile that is pulling in older versions of Pulumi?  

Can you try clearing those culprits and trying again.  If you still run into this, it would be helpful if you could potentially upload your node_modules somewhere so i could try them out.

**Comment by KonstantinRyazantsev** [comment]
I've executed `yarn cache clean`, removed `node_modules` and `yarn.lock` then tried `yarn` and `pulumi up` again and it worked without any errors. Thanks @CyrusNajmabadi
