### ISSUE TITLE
Service memory strings are missing suffixes

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-awsx#497]
For ECS, we [automatically convert](https://github.com/pulumi/pulumi-awsx/blob/b33b80cbdef77444f70fdcab5ac6164283e615e2/nodejs/awsx/ecs/fargateService.ts#L125) from [number-based container memory properties](https://github.com/pulumi/pulumi-awsx/blob/b33b80cbdef77444f70fdcab5ac6164283e615e2/nodejs/awsx/ecs/container.ts#L527) to [string-based service memory properties](https://github.com/pulumi/pulumi-awsx/blob/b33b80cbdef77444f70fdcab5ac6164283e615e2/nodejs/awsx/ecs/fargateService.ts#L312). Unless I'm missing something, however, we fail to add the proper suffix (e.g., `GB`), which means we perpetually encounter diffs for any services stood up using AWSX that also specify memory settings on them (required for Fargate); I'm not sure if CPU suffers from the same issue.

For example, if I make no edits, a `memory: 512` property perpetually shows me that the memory specification has changed from `"0.5"` to `"0.5GB"`, as in [this example program](https://github.com/pulumi/examples/tree/master/aws-ts-hello-fargate).

**Comment by lukehoban** [comment]
Strange - at least at some point not long ago we "fixed" this by partially going the other direction: https://github.com/pulumi/pulumi-awsx/pull/326.  Looks like perhaps AWS changed its own normalization since then?

**Comment by CyrusNajmabadi** [comment]
Sorry for the delay on this.  i haven't been able to repro this at all.  I get no diffs at all when using that example.   Investigating further to see if i can make something trigger.

**Comment by CyrusNajmabadi** [comment]
Even when i make an actual change, the diff is always in units i expect:

![image](https://user-images.githubusercontent.com/4564579/73992205-36b85100-4903-11ea-8b19-9c1fb35b05ed.png)

Joe, are you able to repro this?  Could this be some sort of issue with a particular region?
