### ISSUE TITLE
apigateway.API use nodejs8.10 as Lambda runtime which is no longer supported

### ISSUE THREAD

**Issue by yuichiro12** [pulumi/pulumi-awsx#498]
Hi, I create serverless api with `awsx.apigateway.API` like this:

```
new awsx.apigateway.API(`some-api`, {
    routes: [
      {
        path: "/some-path",
        method: "GET",
        eventHandler: async (req) => {
          ...
        }
      },
    ]
})
```

then I got this error:
```
Diagnostics:
  aws:lambda:Function (some-api):
    error: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.
```

Is there any option to choose runtime for `apigateway.API`?
I'm also happy about the default runtime to be changed to "nodejs12.x".

**Comment by stack72** [comment]
Hi @yuichiro12 

Please can you tell me what version of awsx you are using?

Thanks

Paul

**Comment by yuichiro12** [comment]
It was 0.18.14. I will try latest version.

**Comment by yuichiro12** [comment]
upgrading @pulumi/awsx to v1.9.1 cause another error around Vpc:

```
Running program failed with an unhandled exception:
    TypeError: this.getData is not a function
        at new Vpc (.../node_modules/@pulumi/ec2/vpc.ts:276:27)
        at Function.fromExistingIds (.../node_modules/@pulumi/ec2/vpc.ts:367:16)
```

any idea?

**Comment by lukehoban** [comment]
@yuichiro12 Did you update everything? (could you share `package-lock.json`)?

Per https://github.com/pulumi/pulumi-awsx/issues/495, if you are up to date, you should not see that error.

**Comment by yuichiro12** [comment]
↑ `yarn upgrade` solved this. After all I'm using these versions.
```
@pulumi/pulumi@1.9.1
@pulumi/aws@1.19.0
@pulumi/awsx@0.19.1
typescript@3.7.5
```
Now `apigateway.API` successfully created.

**Comment by yuichiro12** [comment]
Anyway,
```
yarn upgrade @pulumi/awsx --latest
```
didn't fix the problem.

dependency tree was like this.
```
├─ @pulumi/awsx@0.19.1
│  ├─ @pulumi/aws@^1.0.0
│  ├─ @pulumi/docker@^1.0.0
│  ├─ @pulumi/pulumi@^1.0.0
│  ├─ @types/aws-lambda@^8.10.23
│  └─ mime@^2.0.0
```
It's better to have appropriate version dependency for pulumi/awsx.

**Comment by lukehoban** [comment]
> It's better to have appropriate version dependency for pulumi/awsx. 

Agreed!  This was fixed in https://github.com/pulumi/pulumi-awsx/pull/496, and will go out with the next release of this package to address this exact issue.

**Comment by yuichiro12** [comment]
Thank you. I'm waiting for the next release.

**Comment by stack72** [comment]
@yuichiro12 Are we good to close this original issue out?

Paul

**Comment by lukehoban** [comment]
This is released now with: https://www.npmjs.com/package/@pulumi/awsx/v/0.19.2
