### ISSUE TITLE
Unable to create API gateway with "lambda integration" route (aws_proxy)

### ISSUE THREAD

**Issue by estyrke** [pulumi/pulumi-awsx#523]
I'm trying to create an aws_proxy route in an API gateway, but it fails with the message "Integrations of type 'AWS_PROXY' currently only supports Lambda function and Firehose stream invocations.". Here is my code (backendFn is a lambda.Function):

```
  // Define the API Gateway
  const api = new awsx.apigateway.API("backend", {
    stageName: pulumi.getStack(),
    routes: [
      {
        path: "/",
        target: {
          type: "aws_proxy",
          uri: backendFn.invokeArn
        }
      }
    ]
  });
```

The problem seems to be that the uri in the generated swagger spec gets `/` and `/{proxy}` (for the two different generated routes) appended to them. If I modify the code (createSwaggerOperationForProxy in apigateway/api.js) to use the passed uri (invokeArn) without any suffix, it seems to work.

The next snag is that the lambda function needs a POST method for the proxied request, but `httpMethod` in the generated integration route is hardcoded to "ANY".

Am I doing this all wrong, or is there one or two bugs here? It would have been nice with an example of how to do this in the documentation (but in light of the issues above, maybe nobody has ever tried it?)

**Comment by leezen** [comment]
Since you already have the lambda.Function, it might be easiest to rewrite your code as:

```
path: "/",
method: "POST",
eventHandler: backendFn
```

As you observed, currently, integration routes are hardcoded to 'ANY'
If you need to use the proxy integration, you may want to just use the raw API Gateway resource itself instead of trying to do this via `awsx` --  https://www.pulumi.com/docs/reference/pkg/aws/apigateway/integration/

**Comment by estyrke** [comment]
@leezen Thanks. I should mention what I'm trying to accomplish. I'm totally unfamiliar with API gateway previously, so I'm fumbling in the dark, but I want requests for all paths (not just the root) to be passed on to the lambda to be routed there. I was under the impression that your example would require me to explicitly put all my routes both in the API gateway and in the lambda, and that an AWS_PROXY integration route was there for the use case I have.

Is the aws_proxy integration type simply not supported in awsx yet, or are there other use cases where the current implementation is useful?

I guess I could also just extract the generated swagger text I get with my current approach, modify it to be correct, and then use that directly in the API constructor.

**Comment by leezen** [comment]
If that's what you're trying to do, you'll want to do something like the following:

https://github.com/pulumi/pulumi-cloud/blob/master/aws/httpServer.ts#L57

You'll see that it setups the routes to the same lambda function and the `{proxy+}` indicator is a 'greedy' match for anything.

Reference: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-set-up-simple-proxy.html

**Comment by estyrke** [comment]
Oh, that looks exactly like what I'm after! Thanks for the pointer! I guess I'll close this issue since there is no need for me to create an integration route explicitly anymore.
