### ISSUE TITLE
Unable to use TypeScript + unit testing on awsx.ec2.Vpc

### ISSUE THREAD

**Issue by tenwit** [pulumi/pulumi-awsx#531]
Extending the example from [the unit testing docs](https://www.pulumi.com/docs/guides/testing/unit/) slightly, I am able to get Pulumi to error out when working with the Vpc object.  Working MCVE:

```
import * as pulumi from "@pulumi/pulumi"
import * as aws from "@pulumi/aws"
import * as awsx from "@pulumi/awsx"

pulumi.runtime.setMocks({
  newResource: function (type: string, name: string, inputs: any): { id: string, state: any } {
    return {
      id: inputs.name + "_id",
      state: inputs,
    };
  },
  call: function (token: string, args: any, provider?: string) {
    return args;
  },
});

import "mocha";

describe('Vpc', function () {
  it('should contain tags', function (done) {
    const vpc = new aws.ec2.Vpc("VPC", {
      "cidrBlock": "10.10.10.10/20",
      "tags": { "name": "steve" }
    });
    pulumi.output(vpc.tags).apply((tags) => {
      console.log(tags); // Displayed on console.
      done();  // Test passes
    });
  });
});

describe('VpcX', function () {
  it('should contain tags', function (done) {
    const vpc = new awsx.ec2.Vpc("VPC", {
      "cidrBlock": "10.10.10.10/20",
      "tags": { "name": "steve" }
    });
    pulumi.output(vpc.vpc.tags).apply((tags) => {
      console.log(tags);  // Not displayed.
      done(); // Test errors.
    });
  });
});
```
The second test ("VpcX") produces this error:
```
     Error: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
      at requireTestModeEnabled (node_modules/@pulumi/awsx/node_modules/@pulumi/pulumi/runtime/settings.js:90:15)
      at Object.getMonitor (node_modules/@pulumi/awsx/node_modules/@pulumi/pulumi/runtime/settings.js:171:13)
      at Object.registerResource (node_modules/@pulumi/awsx/node_modules/@pulumi/pulumi/runtime/resource.js:109:32)
      at new Resource (node_modules/@pulumi/awsx/node_modules/@pulumi/pulumi/resource.js:204:24)
      at new ComponentResource (node_modules/@pulumi/awsx/node_modules/@pulumi/pulumi/resource.js:372:9)
      at new Vpc (node_modules/@pulumi/ec2/vpc.ts:55:9)
      at Context.<anonymous> (Example.spec.ts:32:21)
      at processImmediate (internal/timers.js:456:21)

```

I expect the two tests to behave identically.

**Comment by leezen** [comment]
I could not get this to repro. 

I was even able to make it pass by mocking out the getAvailabilityZones call that the `awsx` package makes:

```
import * as pulumi from "@pulumi/pulumi"
import * as aws from "@pulumi/aws"
import * as awsx from "@pulumi/awsx"

pulumi.runtime.setMocks({
  newResource: function (type: string, name: string, inputs: any): { id: string, state: any } {
    return {
      id: inputs.name + "_id",
      state: inputs,
    };
  },
  call: function (token: string, args: any, provider?: string) {
    switch(token) {
        case "aws:index/getAvailabilityZones:getAvailabilityZones":
            return {
                names: ["us-west-2a", "us-west-2b"],
                zoneIds: ["west2a", "west2b"],
            };
    }
    return args;
  },
});

import "mocha";

describe('Vpc', function () {
  it('should contain tags', function (done) {
    const vpc = new aws.ec2.Vpc("VPC", {
      "cidrBlock": "10.10.10.10/20",
      "tags": { "name": "steve" }
    });
    pulumi.output(vpc.tags).apply((tags) => {
      console.log(tags); // Displayed on console.
      done();  // Test passes
    });
  });
});

describe('VpcX', function () {
  it('should contain tags', function (done) {
    const vpc = new awsx.ec2.Vpc("VPC", {
      "cidrBlock": "10.10.10.10/20",
      "tags": { "name": "steve" }
    });
    pulumi.output(vpc.vpc.tags).apply((tags) => {
      console.log(tags);  // Not displayed.
      done(); // Test errors.
    });
  });
});
```

I'm invoking the test in the same way per the unit testing documentation: `$(npm bin)/mocha -r ts-node/register aws-test.ts` -- are you doing the same thing?

**Comment by tenwit** [comment]
I have done it several ways.
- That way.
- Same, but without the file name.
- `npm test`, with `"test": "mocha"` in the scripts section of my package.json.

I use this as my .mocharc.json:
```
{
  "extension": [
    "ts"
  ],
  "spec": "**/*.spec.ts",
  "require": "ts-node/register"
}
```

I'm guessing that I've done something wrong with my dependencies or devDependencies. Hopefully nothing with my Docker setup is relevant (I run everything from a slightly-enhanced pulumi/pulumi image, with my development directory bind-mounted in).

**Comment by tenwit** [comment]
Whee, progress made. I updated (a snippet of) my package.json from
```
    "dependencies": {
        "typescript": "^3.8.3",
        "@pulumi/aws": "^2.0.0",
        "@pulumi/policy": "^1.1.0",
        "@pulumi/pulumi": "^2.1.0"
        "@pulumi/awsx": "^0.18.10"
    }
```
to
```
    "dependencies": {
        "typescript": "^3.8.3",
        "@pulumi/awsx": "^0.18.10"
    },
    "peerDependencies": {
        "@pulumi/aws": "^2.0.0",
        "@pulumi/policy": "^1.1.0",
        "@pulumi/pulumi": "^2.1.0"
    }
```
And now it works. Thanks for your `getAvailabilityZones` stub, I also have my test passing :)

So: is my change to use peerDependencies necessary, or a side effect of an earlier mistake I have unknowingly made? If it is necessary, should I update this issue or maybe create a new one, since it probably should be in the docs somewhere, and done automatically by `pulumi new`?

**Comment by leezen** [comment]
No, the peerDependencies should not be necessary at all. I see what might have happened now that you've provided the full `dependencies` listing. You have an awsx from pre-2.0, which can result in https://github.com/pulumi/pulumi/issues/4298 -- that's why you see `node_modules/@pulumi/awsx/node_modules/@pulumi/pulumi` -- nice catch spotting that.

`awsx` since version `0.20.0` has `@pulumi/pulumi` as a `peerDependency` so you shouldn't need to resort doing what you've done. In your above setup, you are relying on the `@pulumi/pulumi` and `@pulumi/aws` that `awsx` brings in. I would not recommend that setup and instead switch to using `awsx` at `0.20.0` if possible. Alternatively, you could use the `resolutions` logic outlined in https://github.com/pulumi/pulumi/issues/4298 if you cannot upgrade for whatever reason.
