### ISSUE TITLE
CORS Documentation

### ISSUE THREAD

**Issue by riongull** [pulumi/pulumi-awsx#533]
I can't find documentation for configuring a `new awsx.apigateway.API` to support CORS.  The closest I found was this:

```
(property) APIArgs.gatewayResponses?: Record<string, awsx.apigateway.SwaggerGatewayResponse> | undefined
Define custom gateway responses for the API. This can be used to properly enable CORS for Lambda Authorizers.
```

Apparently if you want to configure CORS, you would do so in this property, but I'm not sure exactly _how_ to set that up.  Any help or examples (I couldn't find any) would be appreciated.  

If it's relevant, I'm using a ` new aws.lambda.CallbackFunction` for `routes.eventHandler`, like so:

```
const myApi = new awsx.apigateway.API("my-api", {
  routes: [{
    path: "/",
    method: "GET",
    eventHandler: new aws.lambda.CallbackFunction("event-handler", {
      runtime: "nodejs10.x",
      memorySize: 256,
      callback: myCallback,
    });
  }],
  gatewayResponses: THE_BIG_MYSTERY_TO_GET_CORS_WORKING
});
```

What value of THE_BIG_MYSTERY_TO_GET_CORS_WORKING would get my API to be CORS supported so people outside of my own domain can, you know, get data from my API - i.e. the purpose of an API.

Thanks in advance!

**Comment by leezen** [comment]
I don't think you should need to touch `gatewayResponses`. You should basically just follow https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html and set that up.

Since you're using an eventHandler with the Lambda callback integration, you need to include the `Access-Control-Allow-Origin` header in your callback. Separately, you'll also want to have an integration route (mock) for `OPTIONS` that returns the appropriate headers.

**Comment by chrismcleod** [comment]
@riongull 
The top level keys correspond to this list: 
https://docs.aws.amazon.com/apigateway/api-reference/resource/gateway-response/#responseType

From that list, I used the following keys, each with the same shape:

- DEFAULT_4XX
- DEFAULT_5XX
- UNAUTHORIZED
- AUTHORIZER_FAILURE

You can go to the API Gateway Console > Your Api > Gateway Responses and select one of the radio buttons to see if
it affected the right one in the right way.

This is how to use the property for CORS
```javascript
const api = new awsx.apigateway.API('myapi', {
  stageName: 'dev',
  gatewayResponses: {
    DEFAULT_4XX: {
      statusCode: 400,
      responseTemplates: {
        'application/json': '{"message":$context.error.messageString}',
      },
      responseParameters: {
        'gatewayresponse.header.Access-Control-Allow-Origin': "'*'",
        'gatewayresponse.header.Access-Control-Allow-Headers': "'*'",
        'gatewayresponse.header.Access-Control-Allow-Methods': "'*'",
        'gatewayresponse.header.Access-Control-Allow-Credentials': "'*'",
      },
    },
...
```

**Comment by leezen** [comment]
Thanks for the additional details @chrismcleod 

Closing as there doesn't seem to be an issue here.

**Comment by allroundexperts** [comment]
> I don't think you should need to touch `gatewayResponses`. You should basically just follow https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html and set that up.
> 
> Since you're using an eventHandler with the Lambda callback integration, you need to include the `Access-Control-Allow-Origin` header in your callback. Separately, you'll also want to have an integration route (mock) for `OPTIONS` that returns the appropriate headers.

How can I achieve that?
It seems that the `target` requires `uri` as a required parameter. However, for mock integrations, I can't see any value for that parameter. I also could not find anything on how to setup header mappings for the mock request. Another issue that I am facing is that there is no way to specify multiple methods on a single path (eg POST and OPTIONS for /pet path).

Your help will be greatly appreciated!

Thanks

**Comment by leezen** [comment]
For those still looking at this issue, I published a video for a simple Lambda-based way of setting up CORS: https://www.youtube.com/watch?v=typ-AJQGKKI

I'll try to spend next week's episode on setting up the mock integration style that doesn't use a Lambda on the `OPTIONS` method.

**Comment by chrismcleod** [comment]
@leezen it seems there are circumstances where the CORS approach in your video is not enough.  For example if your API has an authorizer, and that authorizer fails, you only get a failed CORS response and not the failure response.  The gateway responses give you a way to ensure CORS is returned for all responses from the API gateway.  Perhaps I'm missing something.

**Comment by leezen** [comment]
@chrismcleod Sorry -- I wasn't trying to say the Lambda approach supplants anything else. I was just leaving it in the issue since it seemed like the topic of how to get CORS running on API Gateway was a potentially confusing issue for folks and I wanted to show a quick and easy way to get something running.

**Comment by allroundexperts** [comment]
> @leezen it seems there are circumstances where the CORS approach in your video is not enough. For example if your API has an authorizer, and that authorizer fails, you only get a failed CORS response and not the failure response. The gateway responses give you a way to ensure CORS is returned for all responses from the API gateway. Perhaps I'm missing something.

Hi @chrismcleod!
Setting gateway responses will hide all of your response status (even if it is a legitimate failure). I agree with @leezen that it should not be touched.

**Comment by allroundexperts** [comment]
Anyone looking into this, can also see this:
https://github.com/pulumi/pulumi-awsx/issues/545

**Comment by oscarmeanwell** [comment]
I added this to my API routes to solve the issue. `/{proxy+}` means all endpoints

```
 {
    path: '/{proxy+}',
    method: 'OPTIONS',
    eventHandler: async () => {
      return {
        body: '',
        statusCode: 200,
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Credentials': 'true',
          'Access-Control-Allow-Methods':
          'GET, POST, OPTIONS, PUT, PATCH, DELETE',
          'Access-Control-Allow-Headers':
          'Origin, X-Requested-With, Content-Type, Accept, Authorization',
       },
      }
    },
},
```
