### ISSUE TITLE
Cannot get existing load balancer. New instance created

### ISSUE THREAD

**Issue by benmccann** [pulumi/pulumi-awsx#556]
https://github.com/pulumi/pulumi-awsx/pull/548 doesn't work because `opts.id` is `undefined` when we call

https://github.com/pulumi/pulumi-awsx/blob/ac937595322bf1560b67598a612b4374253cd6aa/nodejs/awsx/lb/loadBalancer.ts#L31

which causes a new resource to be created. It looks like I was too trusting in starting off from https://github.com/pulumi/pulumi-awsx/pull/541 and assuming that it had been tested.

What is the expected type of `opts.id`? Is it `string` or `Input<string>`?

**Comment by leezen** [comment]
It's an `Input<ID>` (so yes, string): https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/resource.ts#L463
I should've noticed this as well when reviewing

**Comment by benmccann** [comment]
Thanks for the clarification. I was confused by the output of `pulumi up` / `pulumi preview`
