### ISSUE TITLE
awsx.ecr.buildAndPushImage is not tagging properly docker image on ECR

### ISSUE THREAD

**Issue by albertocorrales** [pulumi/pulumi-awsx#585]
I'm trying to build and publish a new image with awsx.ecr.buildAndPushImage(...) command but I can't use version as custom tag.

My current pulumi code is:

```
    const repository = aws.ecr.Repository.get(
      `my-repository`,
      ecrRepositoryName
    );
    this.image = awsx.ecr.buildAndPushImage(`my-image:1.0.0`, "./app", {
      repository: repository,
    });
```

### Expected behaviour
tag "1.0.0" is used when I publish my docker image

### Current behaviour
As tags are being used the image id and latest, but no the custom version. For example, in ECR I see tags like:

24986177d6391ea6f72e793a59427a47e029af1f947ad6b50edbb010bcd0cd65, latest

### Packages version

"@pulumi/aws": "3.5.0",
"@pulumi/awsx": "0.22.0",
"@pulumi/pulumi": "2.11.2"

**Comment by leezen** [comment]
The first argument is the name of the component resource representing the repository, so including a tag won't have any effect. I believe the way the code as-written in `awsx` doesn't allow for passing in the image name and tag. If you need to control this, you may want to call `@pulumi/docker`'s buildAndPushImage instead which does provide that control.

**Comment by albertocorrales** [comment]
> The first argument is the name of the component resource representing the repository, so including a tag won't have any effect. I believe the way the code as-written in `awsx` doesn't allow for passing in the image name and tag. If you need to control this, you may want to call `@pulumi/docker`'s buildAndPushImage instead which does provide that control.

Thanks @leezen, I had seen the way to tag images using @pulumi/docker, but I was wondering why we can't use custom tags in awsx module. In fact, there is already a dependency between repository and @pulumi/docker https://github.com/pulumi/pulumi-awsx/blob/master/nodejs/awsx/ecr/repository.ts, so I guess it should be easy to give us a way to use custom tags by using awsx module.

**Comment by leezen** [comment]
> I was wondering why we can't use custom tags in awsx module

Unfortunately, support for this wasn't implemented in `awsx`. I'll use this issue to track adding in that support. Happy to accept a PR if you'd like to plumb it through. As you said, it's a matter of exposing what's already in `@pulumi/docker` through this package.

**Comment by mikhailshilkov** [comment]
We'll track this in https://github.com/pulumi/pulumi-awsx/issues/1149 since it's a more modern version of the same request.
