### ISSUE TITLE
Allow to assign tags to the routetables created with the vpc object

### ISSUE THREAD

**Issue by roquesao** [pulumi/pulumi-awsx#588]
In order to tag all the aws resources created in an aws account is needed have the possibility to add custom tags to the routetables created with the vpc object. 
It works with vpc and subnets but it doesn't with the routetables have been created.
thanks in advance.

**Comment by leezen** [comment]
You should be able to accomplish this via a `transformation` that adds to the tags to the resources. See https://www.pulumi.com/docs/intro/concepts/programming-model/#transformations for an example. Please let me know if that helps get you where you need.

**Comment by roquesao** [comment]
Thanks Leezen, I will try, but it would be nice to have some property to set them more straightforward in order to have different tags than the subnets, ej:

 new awsx.ec2.Vpc('cloud-pulumi', {
    cidrBlock: vpcCidr,
    subnets: subnets,
    tags: tags,
    routeTableTags : xx
  });

I have resolved it using aws sdk but I will try via transformation.
