### ISSUE TITLE
Is there a way to get EC2 Instances associated with a Cluster/Autoscaling Group?

### ISSUE THREAD

**Issue by mdhornet90** [pulumi/pulumi-awsx#591]
What the title says. I'm running a barebones cluster of one EC2 instance that I'm hoping to dynamically attach a custom domain to via Route53, but there's no clear way to programmatically probe the cluster or associated autoscaling group. Additionally, I'm constrained by the fact that I can't use an ALB to accomplish this (too cheap to pay for a NAT gateway so the instance can communicate with the internet).

Assuming I'm not barking up the wrong tree, what's a good algorithm for figuring this out? But if I _am_ barking up the wrong tree, what's the recommended alternative?

**Comment by mdhornet90** [comment]
I actually figured out a workaround that let me target an EC2 box in a public subnet using the ALB, but I'm still curious to hear if there's a good algorithm for determining boxes belonging to a cluster or autoscaling group.

**Comment by leezen** [comment]
One way to do this would be to call the AWS SDK to determine the set of instances in the ASG. However, that doesn't seem "right" to me that in instances in an ASG by definition can come and go, so really having an ALB (or some stable mechanism to direct traffic) is really what you want here.
