### ISSUE TITLE
move aws.apigateway.x.* to this repo

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-awsx#60]
This will be the repo we want for complex large-scale components.  'aws' will be for raw resources, or simple extensions (liek serverless) of raw resources.

Tagging @lukehoban

**Comment by CyrusNajmabadi** [comment]
This has been done.  however, i'm keeping this issue around to track removing the same API from pulumi/aws.  See: https://github.com/pulumi/pulumi-aws/pull/453

**Comment by ekrengel** [comment]
@CyrusNajmabadi isnt this complete?

**Comment by CyrusNajmabadi** [comment]
Indeed.  Fixed with https://github.com/pulumi/pulumi-aws/pull/508.  Thanks.
