### ISSUE TITLE
Wrongfully adds "*/*" to binary media type on apigateway.API update

### ISSUE THREAD

**Issue by jorgechiapello** [pulumi/pulumi-awsx#604]
When I create an API using `new apigateway.API('name', { swaggerString: swaggerFile })` and I define no value for `binaryMediaType` then the resource will be created correctly. 

So far, so good.

When updating, Pulumi detects a diff in the `binaryMediaType` of the RestApi resource although nothing changed and adds the value "*/*" to the array, stating that everything should be treated as binary types.

I need to explicitly state that no values should go there to avoid this:

```
new apigateway.API('name', { 
      swaggerString: swaggerFile,
      restApiArgs: {
        binaryMediaTypes: [],
      },
 })
```

**Comment by stack72** [comment]
@leezen is this something we should remove the default on? Technically that would be a breaking change...

**Comment by leezen** [comment]
I'm not sure why this is only seen on update as I would expect this to be true from the start per https://github.com/pulumi/pulumi-awsx/blob/0223b2c20dc332faaa1fac4db2a09fb102aae7c2/nodejs/awsx/apigateway/api.ts#L560

**Comment by leezen** [comment]
As we haven't heard back in a while regarding a repro, I'm going to close this for now.
