### ISSUE TITLE
Unable to add path to HTTP healthcheck for NLB target group

### ISSUE THREAD

**Issue by adrianleonmorell** [pulumi/pulumi-awsx#605]
Hi guys, I'm trying to add HTTP healtchecks to a NLB target group but I'm unable to add the path property. This is apparently possible using the AWS console
![image](https://user-images.githubusercontent.com/17031755/101342545-045ce480-3883-11eb-82e3-c9ca9af82b85.png)

This is what I'm trying with pulumi:
![image](https://user-images.githubusercontent.com/17031755/101342338-b5af4a80-3882-11eb-9094-d942ae76bc9a.png)
but the parameter path is of type never.

Is there something I'm missing? Can you guide my in the right direction?
Thanks in advance

**Comment by leezen** [comment]
Thanks for reporting this. This looks to be a bug in the library where it hasn't been updated to keep up with the surface area of the underlying NLB API.

**Comment by adrianleonmorell** [comment]
Hi @leezen, do you know if this will be released soon? Thank you, for the quick feedback.

**Comment by leezen** [comment]
@adrianleonmorell I'll work on cutting a release today

**Comment by adrianleonmorell** [comment]
Thanks @leezen

**Comment by leezen** [comment]
@adrianleonmorell In case you didn't see, 0.23.0 is now available.

**Comment by adrianleonmorell** [comment]
Hi @leezen I have being trying to create the NLB using awsx 0.23.0 and I have found 2 things:
1- The type for the timeout property for the healthchecks is set to never for the NLB so it's always created with 6 seconds
2- The matcher property is allowed but I get a runtime error if something different of "200-399" is specified (not a big deal for me since my healthchecks return 200 or 503)

This is the code sample I'm using
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const vpc = new awsx.ec2.Vpc(`test-vpc`, {
  numberOfAvailabilityZones: 2,
  subnets: [
    {
      type: "private",
      name: `private-subnet`,
    },
  ],
  tags: { Name: `test-vpc` },
});

const nlb = new awsx.lb.NetworkLoadBalancer("test-nlb", {
  vpc: vpc,
  subnets: vpc.privateSubnetIds,
  external: false,
});

nlb.createListener("test-listener", {
  port: 8080,
  protocol: "TCP",
  targetGroup: {
    port: 80,
    protocol: "TCP",
    healthCheck: {
      protocol: "HTTP",
      port: "80",
      path: "/health",
      healthyThreshold: 2,
      unhealthyThreshold: 2,
      interval: 10,
      matcher: "200",
    },
  },
});
```

This is the error I get
![image](https://user-images.githubusercontent.com/17031755/105060390-9f4b0000-5a78-11eb-8f60-374849824bd1.png)

Dependencies
![image](https://user-images.githubusercontent.com/17031755/105060571-d8837000-5a78-11eb-93af-b4a2ec1068da.png)

Thanks in advance

**Comment by adrianleonmorell** [comment]
Hi @leezen, forget my last comment. It seems that AWS doesn't allow custom values for the target group timeout, success codes and interval. This is what happened when trying to create a tg for a NLB on the AWS Console:
![image](https://user-images.githubusercontent.com/17031755/105167424-fdc7bb00-5b18-11eb-9173-b56aa9c2d1a5.png)
