### ISSUE TITLE
Replace default AmazonEC2ContainerServiceFullAccess to AmazonECS_FullAccess

### ISSUE THREAD

**Issue by ahanoff** [pulumi/pulumi-awsx#610]
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/managed-policy-transition.html
Amazon is going to deprecate AmazonEC2ContainerServiceFullAccess policy

https://github.com/pulumi/pulumi-awsx/blob/2506065d78d21f88fea54d28f240c8e27d2fae3c/nodejs/awsx/ecs/taskDefinition.ts#L152

**Comment by ahanoff** [comment]
Waiting for https://github.com/pulumi/pulumi-aws/pull/1273 to be merged first

**Comment by ahanoff** [comment]
hi @leezen, I would like to fix this issue, but I have couple of questions:

- peer dependency @pulumi/aws package accepts multiple versions: ^1.0.0, ^2.0.0, or ^3.0.0. New ECS policies were added in [3.22.0 release](https://github.com/pulumi/pulumi-aws/blob/master/CHANGELOG.md#3220-2020-12-22). Shall it be added in 1.0.0 and 2.0.0 as well? 🤔 
- how do you usually deal with peer dependencies locally? Via yarn link? 🤔 

thanks in advance

**Comment by leezen** [comment]
Thanks for offering to help here!

Generally speaking, we had that peer dependency set to try to maintain backwards compatibility with the previous version of the `aws` provider. Until now, I don't know of any real breaking changes in the `@pulumi/aws` API that would've broken this library. We've made some tweaks such as changing some of the types for `tags` to update this library to work with 3.0, but those were actually backwards compatible changes with @pulumi/aws@2.x.  However, with the change above, I think we'll have to take a breaking change here as well and force this onto `^3.22.0`

Locally, this package installs peer dependencies when you're developing against it https://github.com/pulumi/pulumi-awsx/blob/master/Makefile#L12

**Comment by koliyo** [comment]
This is being deprecated on January 29, https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_managed_policies.html#AmazonEC2ContainerServiceFullAccess

Wrong year in document, the sent out mail says 2021

**Comment by leezen** [comment]
https://github.com/pulumi/pulumi-awsx/pull/624

**Comment by stack72** [comment]
Closed via #624
