### ISSUE TITLE
crosswalk for API gateway always adds {proxy+}

### ISSUE THREAD

**Issue by geekyme** [pulumi/pulumi-awsx#634]
Example code: 

```
new awsx.apigateway.API("api", {
      routes: [
        {
          path: "/renewals/{id}/",
          method: "GET",
          target: {
            type: "http_proxy",
            uri: lb.loadBalancer.dnsName.apply(
              (url) => `http://${url}:4001/renewals/{id}/`
            ),
            connectionType: "VPC_LINK",
            connectionId: vpcLink.id,
          },
        },
        {
          path: "/payment-methods/",
          method: "GET",
          target: {
            type: "http_proxy",
            uri: lb.loadBalancer.dnsName.apply(
              (url) => `http://${url}:4002/payment-methods/`
            ),
            connectionType: "VPC_LINK",
            connectionId: vpcLink.id,
          },
        },
        {
          path: "/insurers/",
          method: "GET",
          target: {
            type: "http_proxy",
            uri: lb.loadBalancer.dnsName.apply((url) => `http://${url}:4002/`),
            connectionType: "VPC_LINK",
            connectionId: vpcLink.id,
          },
          authorizers: [
            awsx.apigateway.getRequestLambdaAuthorizer({
              headers: ["Authorization"],
              handler: authorizer(userPoolId, "insurers"),
            }),
          ],
        },
      ],
      stageName: "prod",
    });
```

It generates:

<img width="197" alt="Screenshot 2021-02-03 at 1 17 34 PM" src="https://user-images.githubusercontent.com/977460/106701988-920a4580-6622-11eb-8d74-7e9c293fa23f.png">

I don't need the {proxy+} routes, how do I turn those off?

**Comment by geekyme** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html. I see there's an option for 'Configure as proxy resource'. How can I turn that off?

**Comment by geekyme** [comment]
@stack72 I think this is the problem - https://github.com/pulumi/pulumi-awsx/blob/0223b2c20dc332faaa1fac4db2a09fb102aae7c2/nodejs/awsx/apigateway/api.ts#L1256-L1259

**Comment by geekyme** [comment]
Minimal reproduction:

```
const api = new awsx.apigateway.API("api", {
    routes: [
      {
        path: "/",
        method: "GET",
        target: {
          type: "http",
          uri: "https://jsonplaceholder.typicode.com/todos/1",
        },
      },
    ],
    stageName: "prod",
    restApiArgs: {},
  });
```

Results in:

<img width="606" alt="Screenshot 2021-02-04 at 9 04 21 PM" src="https://user-images.githubusercontent.com/977460/106896495-9753b700-672c-11eb-8458-2f25eda5f097.png">

Expected behavior:

1. Proxy shouldn't be automatically created. Should have an option for this.
2. HTTP method should respect what was provided.

**Comment by leezen** [comment]
The HTTP method issue is currently a limitation of the library and "by design" per https://github.com/pulumi/pulumi-awsx/blob/0223b2c20dc332faaa1fac4db2a09fb102aae7c2/nodejs/awsx/apigateway/api.ts#L225

You have a couple options for getting the behavior you want: you could either include a resource transformation to the `API` resource to modify the API `body` property or you could construct the API via the provider directly https://www.pulumi.com/docs/reference/pkg/aws/apigateway/
