### ISSUE TITLE
Type errors when creating VPC resource with values obtained from Stack Reference 

### ISSUE THREAD

**Issue by muhannad0** [pulumi/pulumi-awsx#642]
Hi there!

I'm trying to use the method `awsx.ec2.Vpc.fromExistingIds` to create a vpc resource that will used to create Security Groups and EC2 instances. I'm getting the values for `vpcId`, `privateSubnetIds` and `publicSubnetIds` from stack reference of an existing main networking stack.

However, I'm running into a type error for the arguments `privateSubnetIds` and `publicSubnetIds` when trying to create the VPC resource this way;
`Type 'Output<any>' is not assignable to type 'Input<string>[] | undefined'.`

I double checked the type of output values I'm getting from the stack reference, and it's a string array when I run the Pulumi program.

Sample output of stack reference values:
```
<snipped>
Outputs:
  + pub: [
  +     [0]: "subnet-0hfb71653df899cf"
  +     [1]: "subnet-0tg6hu0fc94aac64"
    ]
  + pvt: [
  +     [0]: "subnet-0b1356yhddcf110"
  +     [1]: "subnet-01c09dd2jj3813893"
    ]
  + vpc: "vpc-0fa7fdg8a3c"

Resources:
    1 unchanged

Duration: 4s
```

Here's the code I'm working with:

```js
const infra = new pulumi.StackReference(`${infraStack}/${env}`)

export const vpcId = infra.getOutput(`${awsRegion}:vpcId`)

export const publicSubnetIds = infra.getOutput(`${awsRegion}:publicSubnetIds`)

export const privateSubnetIds = infra.getOutput(`${awsRegion}:privateSubnetIds`)

export const mainVpc = awsx.ec2.Vpc.fromExistingIds("main-vpc", {
  privateSubnetIds,
  publicSubnetIds,
  vpcId,
})
```

I've tried modifying the output type within an apply like this, but then the type is set as `pulumi.Output<string[]>` which is not accepted as valid.

```js
export const publicSubnetIds = infra.getOutput(`${awsRegion}:publicSubnetIds`)
  .apply(subnets => subnets as string[])
```

Appreciate any help in getting this to work as it would be great to not have to pass in config values each time to create the VPC resource across different stacks. 

Thanks!

**Comment by lblackstone** [comment]
It looks like https://github.com/pulumi/pulumi-awsx/issues/522 has a working solution for this.
