### ISSUE TITLE
errorDocument not configurable in StaticRoute

### ISSUE THREAD

**Issue by williamoverton** [pulumi/pulumi-awsx#646]
I am running a react app and which to serve this via a StaticRoute, however my app needs all traffic to go to /index.html

This means I need to set the error document for the s3 bucket which seems to be missing. However in the changelog it states that this functionality was added: https://github.com/pulumi/pulumi-awsx/blob/master/CHANGELOG.md#0184-2019-05-14

I am not able to find this anywhere in the code though,

## Expected behavior
errorDocument should be specifiable for StaticRoutes

## Current behavior
It is not possible to hose single page apps via StaticRoutes

## Context (Environment)
Can not run React app via StaticRoute

**Comment by leezen** [comment]
This is configurable via the `staticRoutesBucket` property on `API`
