### ISSUE TITLE
Support application cookie stickiness policy for AWS ALB

### ISSUE THREAD

**Issue by amichel** [pulumi/pulumi-awsx#653]
AWS Application Load Balancers support Application Cookie Stickiness, based on cookie generated by application, instead of auto-generated cookie injected by ALB.
This feature is supported in Terraform provider, but not in pulumi-aws for NodeJS 
[](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/app_cookie_stickiness_policy)

## Affected feature
LoadBalancerCookieStickinessPolicy resource as well as ApplicationTargetGroup stickiness args should support this feature

**Comment by leezen** [comment]
Based on the above, I assume you're actually referencing to `@pulumi/awsx` so transferring the issue there.

**Comment by leezen** [comment]
In `awsx`, you can still access the load balancer's name via `alb.loadBalancer.name`, so I believe you should still be able to construct a `AppCookieStickinessPolicy` resource using that. Does that work for you or are you trying to achieve something else?

**Comment by danielrbradley** [comment]
This is resolved by the additional arguments available when constructing default target groups in the 1.0.0-beta versions. Additional target groups can be created directly using the aws TargetGroup resource.
