### ISSUE TITLE
ECS FargateService replaces containers when optionals are omitted

### ISSUE THREAD

**Issue by tonyhb** [pulumi/pulumi-awsx#669]
If you omit optional keys in your `FargateService` definition then launch your services, re-running `pulumi up` next time will generate a diff and replace containers, even without changes.

The existing state in Pulumi is stored with defaults (eg `essential: true`, `mountPoints: []`) but the applied preview doesn't have these defaults... therefore everything is replaced, every time.

## Expected behavior
Optional defaults are applied before the diff and do not replace services.

## Current behavior
Optional defaults aren't applied and show as a diff, so services are replaced with no changes.

## Steps to reproduce

1. Create a minimal fargate service:
``` 
const svc = new awsx.ecs.FargateService(`foo-bar`, {
    cluster,
    desiredCount: 1,
    assignPublicIp: false,
    subnets: isolatedSubnets.apply(subnets => subnets.map(s => s.id)),
    taskDefinitionArgs: {
      containers: {
        nginx: {
          image: "nginx",
          environment: [
          ],
          cpu: 512,
           memory: 2048,
          startTimeout: 10,
          healthCheck: {
            interval: 5,
            retries: 10,
            command: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ],
          },
        },
      }
    },
  });
```
2. Run up more than once.
3. Notice that the diff breaks things

## Context (Environment)
Services are needlessly torn down.

## Affected feature
ECS in AWSX

**Comment by tonyhb** [comment]
Also, if you add a `portMappings: [apiListener]` where `apiListener` is:

```js
  const apiListener = alb.createListener("api", {
    vpc,
    protocol: "HTTPS",
  });
```

Then there's another default diff:

```{containerPort: 80, hostPort: 80}```
```{containerPort: 80, hostPort: 80, protocol: "tcp"}```

**Comment by blampe** [comment]
This might be due to https://github.com/pulumi/pulumi-aws/issues/1985

**Comment by ixti** [comment]
I think it's also related to: https://github.com/pulumi/pulumi/issues/11332

**Comment by t0yv0** [comment]
We've made some improvements in https://github.com/pulumi/pulumi-awsx/releases/tag/v2.14.0 that pull in an AWS provider with a fix for https://github.com/pulumi/pulumi-aws/issues/1985 

Unfortunately I cannot repro the issue as on latest the above code does not type-check anymore (subnets cannot be specified).

Closing this as stale but please open a new issue with a repro if you are still affected by replacements here.
