### ISSUE TITLE
Can't create LB using VPC imported from another stack

### ISSUE THREAD

**Issue by gunar** [pulumi/pulumi-awsx#670]
I'm having trouble trying to use a VPC that was imported from another stack to create a LB. I've pretty much exhausted your docs and I'm not sure how else to proceed. Thanks in advance for any help you might be able to provide.

## Expected behavior
The LB should be created with the VPC imported from the other stack. 

## Current behavior

Getting an error during preview:

```
 * error creating application Load Balancer: ValidationError: At least two subnets in two different Availability Zones must be specified
```

## Steps to reproduce

```ts
// This works — creating the VPC and using it in the same stack works (but is not what I need)
const vpc = new awsx.ec2.Vpc("vpc", { numberOfNatGateways: 0, });
const lb = new awsx.lb.ApplicationLoadBalancer("api", {
  external: true,
  vpc: vpc,
});

// This doesn't work (implicit subnet)
const env = pulumi.getStack();
const networking = new pulumi.StackReference(`acme/networking/${env}`);
const vpc = awsx.ec2.Vpc.fromExistingIds("vpc", { vpcId: networking.getOutput("vpcId"), });
const lb = new awsx.lb.ApplicationLoadBalancer("api", {
  external: true,
  vpc: vpc,
});

// And neither does this (explicit subnet)
const env = pulumi.getStack();
const networking = new pulumi.StackReference(`acme/networking/${env}`);
const vpc = awsx.ec2.Vpc.fromExistingIds("vpc", {
  privateSubnetIds: networking.getOutput("privateSubnetIds") as unknown as undefined, // <- lol I'm trying
  publicSubnetIds: networking.getOutput("publicSubnetIds") as unknown as undefined, // <- lol I'm trying
  vpcId: networking.getOutput("vpcId"),
});
const lbApi = new awsx.lb.ApplicationLoadBalancer("api", {
  external: true,
  vpc: vpc,
  subnets: vpc.publicSubnetIds,
});

```

**Comment by gunar** [comment]
Thanks for moving this to the right place @mikhailshilkov.

This is currently a blocker for me at my work so any help is extremely welcome.

**Comment by leezen** [comment]
@gunar If you were to do something along the lines of `networking.getOutput("publicSubnetIds").apply(console.log)` do you actually get back the array of subnet IDs you expect? It'd be good to validate that the construction of the `Vpc` resource is happening correctly.

**Comment by gunar** [comment]
@leezen This is what I get back:
```
Diagnostics:
  pulumi:pulumi:Stack (application-staging):
    [ 'subnet-05177a8cf1e7e2d70', 'subnet-0915cf5dbaa6837c8' ]
```

Which does match the ids of the two public subnets Pulumi has created for me:

![image](https://user-images.githubusercontent.com/7684574/117361730-521d5d80-aeb2-11eb-8d9e-9c425e2ef7f7.png)

**Comment by leezen** [comment]
Thanks for confirming. And those two subnets are in different AZs? The error message you posted earlier appears to be coming from AWS.

**Comment by muhannad0** [comment]
Hey everyone. Just want to add that the suggested workaround in #522 does correctly create a Vpc object with the respective subnets.

 However, the resulting resource object is not really usable with other resources such as `awsx.ecs.Cluster` or `awsx.lb.ApplicationLoadBalancer`. Because `vpc` argument expects it to be a type of `awsx.ec2.Vpc` whereas the resource created returns type of `Output<awsx.ec2.Vpc>`.
 
 I wonder if there has been any ideas shared within the team to handle this case better, rather than explicitly plugging in the subnets everywhere it needs to go (for instance load balancer, ECS cluster, Fargate service)

**Comment by stack72** [comment]
@danielrbradley i believe the new LB implementation supports this setup right?
