### ISSUE TITLE
Expose `enableExecuteCommand` to awsx.ecs.Service

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-awsx#671]
https://www.pulumi.com/docs/reference/pkg/aws/ecs/service/#enableexecutecommand_nodejs

`enableExecuteCommand` was recently made available in `aws.ecs.Service` - it would be great to also have that exposed in `awsx`! (Perhaps enabled by default?)

**Comment by deevus** [comment]
Also should apply to `FargateService` as long as `platformVersion: 1.4.0`

**Comment by blampe** [comment]
This appears to have been added in #676. Any idea when that will be released?

**Comment by blampe** [comment]
I tried playing around with this in `0.30.1-alpha.1625144438` and ran into the absence of an `executeCommandConfiguration` option on the Cluster. This is essential for setting up logging/auditing around the exec command.

In the mean time I expect to drop down into pulumi-aws since it's available there: https://www.pulumi.com/docs/reference/pkg/aws/ecs/cluster/#executecommandconfiguration_nodejs.

**Comment by Blitz2145** [comment]
Yup, would also appreciate a release made with #676 in it, we've just worked around it for now. Might be even better to have these arg types inherit from their pulumi-aws counterparts where possible, try to avoid duplication.

**Comment by d4nyll** [comment]
`enableExecuteCommand` has been implemented in [0.31.0](https://github.com/pulumi/pulumi-awsx/blob/527f9cd0bddadeba0760a749779392a81bdd9c0d/CHANGELOG.md#0310-2021-08-04).

**Comment by blampe** [comment]
Confirming this has been working well, thanks!
