### ISSUE TITLE
subnet cidr blocks are calculated incorrectly in vpc

### ISSUE THREAD

**Issue by btobolaski** [pulumi/pulumi-awsx#674]
I'm attempting to create a vpc using awsx.ec2.Vpc with an unequal cidr space. Instead of being created, I get an error due to the cidr calculations.

## Steps to reproduce

Using this code: 
```
const vpc = new awsx.ec2.Vpc("dev", {
    cidrBlock: "10.100.0.0/16",
    numberOfAvailabilityZones: 4,
    subnets: [
        { type: "public", cidrMask: 27 },
        { type: "private", cidrMask: 20 }
    ]
});
```
1. attempt to apply it `pulumi up`

Expected: a vpc is created
Actual: 
an error is generated:

```
Diagnostics:
  aws:ec2:Subnet (dev-private-0):
    error: aws:ec2/subnet:Subnet resource 'dev-private-0' has a problem: "10.100.0.64/20" is not a valid IPv4 CIDR block; did you mean "10.100.0.0/20"?. Examine values at 'Subnet.CidrBlock'.
```

**Comment by shed909** [comment]
I've just run into this one as well. Is it being looked at?

**Comment by stack72** [comment]
Hi @btobolaski 

So we have fixed this specific bug in the new version of AWSx - that is currently v1.0.0-beta.2 - I would be interested to see if this covers your use case

We are not going to be back porting fixes to the "classic" (existing TypeScript) implementation of AWSX
