### ISSUE TITLE
Support configuring circuit breaker for FargateService

### ISSUE THREAD

**Issue by chrisportela** [pulumi/pulumi-awsx#675]
The awsx FargateService doesn't let you use the Circuit Breaker configuration of the lower level FargateService in the aws module. It's not being exposed as one of the args you can pass so your only option is switching to the aws one if you want circuit breakers.

From what I remember it should be as simple as adding the option to the awsx version of the FargateService args and then passing it through to the underlying aws one.

**Comment by lukehoban** [comment]
We likely need to update the interfaces in AWSX to match the latest from AWS.

**Comment by albertocorrales** [comment]
We need to enable circuit breaker for FargateService. I hope this support is added soon.

**Comment by albertocorrales** [comment]
Hi @lukehoban, when are you planning to release this? I see in latest version of @pulumi/asmx is not available yet.
