### ISSUE TITLE
Specify list of Elastic IPs to use for NAT Gateways

### ISSUE THREAD

**Issue by almson** [pulumi/pulumi-awsx#685]
Problem: I need the NAT Gateway EIPs to stay constant.

## Affected feature

I'd like the Vpc class to take a list of EIP IDs to use when creating NAT gateways.

**Comment by aaronhayes** [comment]
@almson  any chance you have a workaround? 
Have the same requirements, need to allocate static IP address to egress traffic as one of our API providers limits access via IP addresses

**Comment by almson** [comment]
@aaronhayes Sure, here's the golden workaround: clone awsx and edit it to accept a list of eips. (Bonus points for posting a PR.)

**Comment by aaronhayes** [comment]
@almson  Oh that will actually work for me. Didn't know it allocates static EIPs. I initially wanted to use previously allocated addresses, but can get the automatically allocated EIPs whitelisted thanks 😄

**Comment by jkodroff** [comment]
I have faced this exact scenario at my previous job as a consultant.

I tested this code, and I think it should solve your problem without the need to fork or wait for a PR to change `awsx.Vpc`:

```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

const eipAllocationIds = [
  'eipalloc-0606851b14cb56c07',
  // etc
];

const vpc = new awsx.ec2.Vpc('try-pulumi', {
  numberOfAvailabilityZones: eipAllocationIds.length,
  numberOfNatGateways: 0
});

for (let i = 0; i < eipAllocationIds.length; i++) {
  vpc.privateSubnets.then(subnets => {
    const natGateway = new aws.ec2.NatGateway(`my-nat-gateway-{i}`, {
      subnetId: subnets[i].subnet.id,
      allocationId: eipAllocationIds[i]
    });

    subnets[i].createRoute(`nat-gateway-{i}`, {
      destinationCidrBlock: '0.0.0.0/0',
      natGatewayId: natGateway.id
    });
  });
}
```

**Comment by almson** [comment]
@jkodroff Shouldn't the NAT gateways be in public subnets?

**Comment by stack72** [comment]
@jkodroff i believe your new implementation of VPC allows a user to bring their own EIPs right?

**Comment by jkodroff** [comment]
@danielrbradley This can be closed. We now have this capability in AWSX 1.0: https://www.pulumi.com/registry/packages/awsx/api-docs/ec2/vpc/#elastic_ip_allocation_ids_python
