### ISSUE TITLE
awsx.elasticloadbalancingv2.NetworkLoadBalancer keeps replacing subnet when using subnetMappings

### ISSUE THREAD

**Issue by emiioan** [pulumi/pulumi-awsx#690]
Hello,

It seems that when creating a NLB with pre allocated EIP by using **subnetMappings** argument, at each pulumi up, will detect a subnet change and replaces the NLP, which should be the case as there were no changes.

The workaround is to add **subnets** argument also and this way will not detect any change. But this will came in conflict when you want to launch a fresh stack as you need to provide either **subnets** argument or **subnetMappings** argument. 

We tried  {ignoreChanges: ["subnetMappings"]} but it seems that it does not count, it will not ignore changes to subnets.

Here is the sample code:

```
// Create Network LoadBalancer
const nlb_sftp = new awsx.elasticloadbalancingv2.NetworkLoadBalancer(`sftp-nlb-${az}`, {
    name: `sftp-nlb-${az}`,
    vpc: vpcx,
    // Uncomment this after the stack is up for pulumi update (the NLB won't be replaced)
    //subnets: [selectedSubnet],
    external: true,
    // remember to revert for the final release
    enableDeletionProtection: false,
    //ipAddressType: "ipv4",
    subnetMappings: [
        {
            subnetId: NLBSubnet,
            allocationId: eipallocId,
        }
    ]
 });
```

This is the details pulumi change:

```        +-aws:lb/loadBalancer:LoadBalancer: (replace)
            [id=arn:aws:elasticloadbalancing:eu-central-1:1111111111111:loadbalancer/net/sftp-nlb-DE/b293c8bcd4cdd899]
            [urn=urn:pulumi:stack-de::sftp-de::awsx:lb:NetworkLoadBalancer$aws:lb/loadBalancer:LoadBalancer::sftp-nlb-DE]
            [provider=urn:pulumi:stack-de::sftp-de::pulumi:providers:aws::default_4_12_0::cb502d09-0cda-4902-92a7-feccceb92beb]
          ~ subnets: [
              - [0]: "subnet-0e2b99df9908f35d9"
            ]
        ++aws:lb/loadBalancer:LoadBalancer: (create-replacement)
            [id=arn:aws:elasticloadbalancing:eu-central-1:111111111111:loadbalancer/net/sftp-nlb-DE/b293c8bcd4cdd899]
            [urn=urn:pulumi:stack-de::sftp-de::awsx:lb:NetworkLoadBalancer$aws:lb/loadBalancer:LoadBalancer::sftp-nlb-DE]
            [provider=urn:pulumi:stack-de::sftp-de::pulumi:providers:aws::default_4_12_0::cb502d09-0cda-4902-92a7-feccceb92beb]
          ~ subnets: [
              - [0]: "subnet-0e2b99df9908f35d9"
            ]
```

Are we doing something wrong or do you suggest or plan to have a fix in a new release?

**Comment by leezen** [comment]
It looks like the issue is happening here where the `LoadBalancer` constructor explicitly sets `subnets`: https://github.com/pulumi/pulumi-awsx/blob/9c29338c18a694c8e7240231f99fbfdacfc861af/nodejs/awsx/lb/loadBalancer.ts#L51

As a result, `subnets` always gets set.
