### ISSUE TITLE
API Gateway adds */* to Binary Media Types despite specifying otherwise

### ISSUE THREAD

**Issue by mcfadyeni** [pulumi/pulumi-awsx#697]
When using awsx.apigateway.API and specifying an empty array under restApiArgs.binaryMediaTypes, the path \*/\* is incorrectly added on deploy.
  
Seems to be similar to https://github.com/pulumi/pulumi-cloud/issues/725.

## Steps to reproduce
1. Create an API with awx.apigateway.API, specifying [] (a.k.a none) under restApiArgs.binaryMediaTypes.
2. Create some routes on the API with Swagger configurations (using .data).
3. Deploy the API, observing that no Binary Media Types are set (as expected).
4. Change some route configurations and redeploy, observing that a diff of `[diff: ~binaryMediaTypes,body]` is found and \*/\* is added to Binary Media Types (incorrect).

Expected: The API to have no binary media types specified.
Actual: A path of \*/\* gets incorrectly added to the API Binary Media Types, despite specifying otherwise.

**Comment by mikhailshilkov** [comment]
@mcfadyeni I'm trying to reproduce this issue and I'm getting the following.

The diff on step 4 shows that the `binaryMediaTypes` is about to be removed:

```
~ aws:apigateway/restApi:RestApi: (update)
    [id=be4uhla6l1]
    [urn=urn:pulumi:dev::aws-ts::aws:apigateway:x:API$aws:apigateway/restApi:RestApi::example]
    [provider=urn:pulumi:dev::aws-ts::pulumi:providers:aws::default_4_18_0::01c0d8cd-3277-4de7-95c6-0a5adda75c79]
  ~ binaryMediaTypes: [
      - [0]: "*/*"
    ]
```

This is because the resource state has an empty array as input but an array with the single value as output:

```json
{
    "type": "aws:apigateway/restApi:RestApi",
    "inputs": {
        "binaryMediaTypes": [],
        "body": "...",
        "minimumCompressionSize": -1,
        "name": "example"
    },
    "outputs": {
        "apiKeySource": "HEADER",
        "arn": "arn:aws:apigateway:eu-central-1::/restapis/be4uhla6l1",
        "binaryMediaTypes": [
            "*/*"
        ],
...
```

If that's what you see, it looks like the `*/*` value is added by the underlying provider.

**Comment by mcfadyeni** [comment]
@mikhailshilkov Yes, I see that as well. In addition, the auto-generated Swagger string for the API has an incorrect x-amazon-apigateway-binary-media-types entry of [*/*], and manually overriding in the RestAPI body does nothing.

I will see about bringing this up over at the [pulumi / pulumi-aws](https://github.com/pulumi/pulumi-aws) provider repo, as having to reset the Binary Media Types manually on every deploy is getting tedious.

Thanks for your help.

**Comment by jamest-pin** [comment]
I'm still having random issues with this. Seems like a tricky problem to resolve. Doing this fixed my cors issues, and also some of the issues "invalid patch path /binaryMediaTypes/" but not all of them.
```yaml
binaryMediaTypes: # requires aws-apigateway plugin to be 2.1.0 or above
        - "*"
```
I still sometimes get errors creating a new fresh api gateway.
