### ISSUE TITLE
Unable to add success codes to HTTP healthcheck for ALB target group

### ISSUE THREAD

**Issue by profsmallpine** [pulumi/pulumi-awsx#703]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd like an option to change not just the path but the advanced parameters as well.

![Screen Shot 2021-09-29 at 2 18 24 PM](https://user-images.githubusercontent.com/7328006/135342432-64775d39-b4d5-4190-83f2-a89708ca8001.png)

**Comment by danielrbradley** [comment]
Hi @profsmallpine this should now be resolved in the latest 1.0.0-beta release of the library. All the advanced fields on the load balancer's default target group can be overridden, and additional target groups are just created using the `pulumi-aws` TargetGroup resource directly - which exposes all options.
