### ISSUE TITLE
Cannot add new private subnets to existing VPC

### ISSUE THREAD

**Issue by maghau** [pulumi/pulumi-awsx#718]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We have an `awsx.ec2.vpc` component in which we manually add subnets to in order to have better control over the subnet CIDR blocks and also for extending the VPC with new subnets over time.

When we try to add new private subnets with NAT Gateway routes, this fails due to what seems to us the original NAT routes getting new ID's due to changes in index. I cannot find any `ignoreChanges` pattern that prevents this from happening.

The only way I get this to work is to delete all NAT Gateway bound routes in the VPC in an external script, then do a `pulumi refresh`, and at last run `pulumi up` to create all NAT Gateway routes all over. 

We are not to keen on doing this in our production environment since we expect a lot of traffic to fail in this short period of time.

### Steps to reproduce

1. Clone the demo repo @ [https://github.com/easee/awsx-vpc-nat-routes](https://github.com/easee/awsx-vpc-nat-routes)
2. Run `pulumi up`.
   You should now have three public subnets, three private subnets, and three NAT Gateways.
3. In `index.ts`, uncomment the block of new private subnets at line 70 => 93
4. Run `pulumi up`.
   The preview should at this stage indicate that Pulumi wants to delete and re-create the NAT routes in one or more of the existing private subnets. This is not expected. It looks as if there is some indexing going on in the underlying code that causes the ID of the original NAT routes to change.
5. Accept the changes in the preview and try to deploy.
   We now observe that the update fails as the existing subnets already have a route to `0.0.0.0/0` via NAT Gateways.

Expected: We should have been able to add new private subnets.
Actual: Pulumi tries to recreate the NAT Gateway bound routes for the existing private subnets. The update fails.

**Comment by danielrbradley** [comment]
Hello, this should now be resolved in v2.2.0. We've added additional subnet strategies and layout options to provide better control over subnet placement include when adding or removing them from existing VPCs.

For full changes see:
- https://github.com/pulumi/pulumi-awsx/pull/1153
