### ISSUE TITLE
Support for ECS Fargate Windows containers

### ISSUE THREAD

**Issue by nivinjoseph** [pulumi/pulumi-awsx#720]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

AWS recently introduced support for ECS Fargate windows containers. 

https://aws.amazon.com/about-aws/whats-new/2021/10/aws-fargate-amazon-ecs-windows-containers/

Currently when using the awsx.ecs.FargateService and awsx.ecs.FargateTaskDefinition classes, Pulumi creates a linux cluster even if "os": "windows" is specified. I suppose this is because Fargate used to be linux only. However this is no longer the case. This could even be considered a bug at this point.

Please advise.

### Affected area/feature

awsx.ecs

**Comment by mikhailshilkov** [comment]
@nivinjoseph Thank you for finding this out! If you could open a PR to fix this issue, that would be greatly appreciated!

**Comment by nivinjoseph** [comment]
For starters, the underlying terraform provider needs to support this. I believe this might have been added recently based on the following issue and merged PR.

https://github.com/hashicorp/terraform-provider-aws/issues/21706
https://github.com/hashicorp/terraform-provider-aws/pull/22016

Once the provider is upgraded, then we need to add support for this potentially in the pulumi.aws.ecs module first before exposing it in the pulumi.awsx.ecs since the later uses the former under the hood.

**Comment by dustinbrooks** [comment]
Providers have been updated, would like to take advantage of this.

**Comment by danielrbradley** [comment]
This should now be available in the 1.0.0-beta releases. All underlying provider properties should now be available on the component.
