### ISSUE TITLE
Investigate master build/test failures

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-awsx#722]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Tests have consistently been failing:
https://github.com/pulumi/pulumi-awsx/runs/4878611515?check_suite_focus=true

**Comment by leezen** [comment]
No longer an issue
