### ISSUE TITLE
Allow minor upgrades of @pulumi/aws peer dependency

### ISSUE THREAD

**Issue by Lepozepo** [pulumi/pulumi-awsx#729]
https://github.com/pulumi/pulumi-awsx/blob/cb8beeb4c9d1d002839356883e145edf46307dd2/nodejs/awsx/package.json#L22

Any chance we could patch peer dependencies to allow any version of `pulumi/aws`?

**Comment by danielrbradley** [comment]
Yes, I think this should actually be using the `^` to allow minor releases above the named version rather than `~` which only allows patches.

**Comment by Lepozepo** [comment]
@danielrbradley yup, definitely not critical but would be nice to have a `^` instead

**Comment by iyefrat** [comment]
Hey, I would like to second the request in this issue. It looks like a `^` was used in previous versions, what was the reason for the change?

**Comment by danielrbradley** [comment]
This was fixed in 0.40.0 and is also fixed in the latest 1.0.0-beta.x releases. It was temporarily pinned due to an upstream bug https://github.com/pulumi/pulumi-aws/issues/1660 which required a workaround.
