### ISSUE TITLE
Ability to tie Fargate service to a load-balancer/listener/target-group without creating new listeners.

### ISSUE THREAD

**Issue by nikagamkrelidze** [pulumi/pulumi-awsx#746]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It's needed to allow to associate Fargate services with existing load-balancer/listener/target-group combination.
Currently, if we wanna put a Fargate service in a target group, we need to create a target group and derive a lb listener from it, like following (as seen [here](https://pulumi.awsworkshop.io/additional-content/110_deploying_containers_to_ecs/20_creating_a_loadbalanced_service.html)):

```
import * as pulumi from "@pulumi/pulumi";
import * as awsx from "@pulumi/awsx";

const cluster = new awsx.ecs.Cluster("cluster");

const alb = new awsx.elasticloadbalancingv2.ApplicationLoadBalancer(
    "app-lb", { external: true, securityGroups: cluster.securityGroups });
const atg = alb.createTargetGroup(
    "app-tg", { port: 80, deregistrationDelay: 0 });
const web = atg.createListener("web", { port: 80 });

const appService = new awsx.ecs.FargateService("app-svc", {
    cluster,
    taskDefinitionArgs: {
        container: {
            image: "nginx",
            portMappings: [ web ],
        },
    },
    desiredCount: 1,
});
```
If I wanna reuse an existing listener, I can't tie it to a newly created target-group though. I don't want the listener to be derived from my target group, it should be able to forward requests to multiple target groups.

However, in a AWS Console, we can specify an existing target group without creating a new listener:

![ezgif-1-8909d61263](https://user-images.githubusercontent.com/1589614/159511043-b77cbc3d-29e3-4430-8cbe-619b732f1e29.png)

This seems to be a property of a Service but I'm unable to find anything similar in [current documentation](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/awsx/ecs/).

### Affected area/feature

Here are my dependencies which I'm using for my project:

```
"dependencies": {
    "@pulumi/aws": "4.38.1",
    "@pulumi/awsx": "0.33.0",
    "@pulumi/pulumi": "3.26.1"
}
```

**Comment by guineveresaenger** [comment]
hi @nikagamkrelidze - thank you for this issue! We value feedback and insights on what you need.

We are working on some Fargate updates in #734 and this may actually be fixed in that change 🤞

**Comment by danielrbradley** [comment]
Hi @nikagamkrelidze as part of the 1.0.0 beta release we've redesigned the loadbalancing abstraction. This should remove the auto-creation of the listener. Instead you should be able to bring your own target groups and just define the listeners you want as part of the load balancing component.

Please give it a try and let me know if the new design doesn't meet your use-case.
