### ISSUE TITLE
Provide a way to change `handler` config for lambdas created with `apigateway`

### ISSUE THREAD

**Issue by thepabloaguilar** [pulumi/pulumi-awsx#757]
## Issue details

Hello, I'm using `awsx` to deploy some lambdas through an API Gateway, so far so good because I can just do something like:

> Btw, I'm using `aws.lambda.CallbackFunction`

```js
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

let endpoint = new awsx.apigateway.API("example", {
    routes: [{
        path: "/",
        method: "GET",
        eventHandler: new aws.lambda.CallbackFunction("test", {
            memorySize: 256,
            callback: async (event) => {
                return {
                    statusCode: 200,
                    body: "<h1>Hello world!</h1>",
                };
            },
        }),
    }],
})
```

By default the lambda handler config will be: ____index.handler__
But I want to use a New Relic lambda layer to collect metrics and logs, in order to do that I need to set the handler config to __newrelic-lambda-wrapper.handler__, the NR layer will wrapper the ____index.handler__.

More information about NR config [here](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own#console).

Is there a way to do that?

**Comment by danielrbradley** [comment]
Any class that extends `aws.lambda.Function` can be used here (such as CallbackFunction). Is it that there's functionality missing from CallbackFunction that you're wanting?

**Comment by thepabloaguilar** [comment]
Hey @danielrbradley, yes. I'd like to be able to overwrite de `handler` path!

**Comment by danielrbradley** [comment]
As far as I know, if you want to customise these kinds of internal parts then you will need to package the lambda function code yourself and pass it into the `aws.lambda.Function` `code` property. https://www.pulumi.com/registry/packages/aws/api-docs/lambda/function/#example-usage
