### ISSUE TITLE
ECS port mapping workaround is no longer needed

### ISSUE THREAD

**Issue by mwcampbell** [pulumi/pulumi-awsx#779]
It appears that [this ECS port mapping workaround](https://github.com/pulumi/pulumi-awsx/blob/master/sdk/nodejs/classic/ecs/container.ts#L166) is no longer needed, because the underlying Terraform provider issue has been fixed for a while.

**Comment by stack72** [comment]
@danielrbradley I don't believe we need to do anything here as this was in the old implementation right?

**Comment by danielrbradley** [comment]
Yup, this defaulting no longer exists in the 1.0.0-beta versions
