### ISSUE TITLE
`awsx.lb.NetworkTargetGroupArgs` is missing the recommended setting `connectionTermination`.

### ISSUE THREAD

**Issue by alexframe** [pulumi/pulumi-awsx#783]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

NLB Target groups have a setting called [`connectionTermination`](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#deregistration-delay) which is a recommended setting.

![image](https://user-images.githubusercontent.com/8746552/165416916-7403d5a2-8ded-4fe6-aca8-aa42ff0c48b5.png)

This is not an option on the `awsx.lb.NetworkTargetGroupArgs` however, it _is_ an option on the [`aws.lb.TargetGroup`](https://github.com/pulumi/pulumi-aws/blob/fa0378aa0fda4125690b9187b439be0a84b5dfa7/sdk/nodejs/lb/targetGroup.ts#L109-L112).

I believe that `connectionTermination` should be added to `awsx`, as this is a recommended setting and we cannot currently configure it.

It also does not have the [`preserveClientIp`](https://github.com/pulumi/pulumi-aws/blob/fa0378aa0fda4125690b9187b439be0a84b5dfa7/sdk/nodejs/lb/targetGroup.ts#L141-L144) setting.

### Affected area/feature

I believe this needs to be added to the [`awsx.lb.NetworkTargetGroupArgs`](https://github.com/pulumi/pulumi-awsx/blob/9ca5fa1e349057f63b2b411bc8072f716f8ca6eb/sdk/nodejs/classic/lb/network.ts#L320)

**Comment by stack72** [comment]
Hi @alexframe 

So we have added this specific feature to the new version of AWSx - that is currently v1.0.0-beta.2 - I would be interested to see if this covers your use case

We are not going to be back porting fixes to the "classic" (existing TypeScript) implementation of AWSX
