### ISSUE TITLE
Consider defaulting FargateService to non-public

### ISSUE THREAD

**Issue by Blitz2145** [pulumi/pulumi-awsx#801]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It might be a better default from a security perspective to set `assignPublicIp: false` on `awsx.ecs.FargateService`. We currently override this option almost everywhere in our code using awsx. Breaking change for next major if it makes sense.

### Affected area/feature

`awsx.ecs.FargateService`

**Comment by guineveresaenger** [comment]
Thank you for bringing up this concern - we'll take a look.
