### ISSUE TITLE
awsx ApplicationLoadBalancer.createTargetGroup needs to expose loadBalancingAlgorithmType

### ISSUE THREAD

**Issue by Matthew-Myers** [pulumi/pulumi-awsx#822]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

the args of type `ApplicationTargetGroupArgs` of function `ApplicationLoadBalancer.createTargetGroup` does not accept the field `loadBalancingAlgorithmType` like `aws.lb.TargetGroup` does, while explicitly being an `ApplicationTargetGroup` which is the only type of target group that can take the `loadBalancingAlgorithmType`.  This results in the created `ApplicationTargetGroups` forcing the developer to use round_robin load balancing.

We need the ability to choose the `loadBalancingAlgorithmType` for ApplicationTargetGroups

### Affected area/feature
`awsx ApplicationTargetGroup`

**Comment by stack72** [comment]
Hi @Matthew-Myers 

Please can you let us know what version of awsx you are using?

**Comment by Matthew-Myers** [comment]
I'll take a look tomorrow. Appreciate the support!

**Comment by Matthew-Myers** [comment]
Hey 1 year update.

Updating the package did work and solved the issue.

Closing this out
