### ISSUE TITLE
Incorrect version of the Go SDK is downloaded as the "latest".

### ISSUE THREAD

**Issue by caje731** [pulumi/pulumi-awsx#838]
### What happened?

v1.0.0-beta.2 was released a couple of days ago, but I cannot get it downloaded.

### Steps to reproduce

Follow the standard installation instructions from the README:
```
$ go get github.com/pulumi/pulumi-awsx/sdk
```

### Expected Behavior

Go downloads `v1.0.0-beta.2` of the package.

### Actual Behavior

[v1.0.0-testplsignore.0](https://pkg.go.dev/github.com/pulumi/pulumi-awsx/sdk?tab=versions) is being downloaded instead.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by yann-soubeyrand** [comment]
Hello, I think this is the same issue as https://github.com/pulumi/pulumi-eks/issues/703: the tag sdk/v1.0.0-beta.2 is missing.

**Comment by danielrbradley** [comment]
Thanks, this should now be fixed - I've just pushed the missing tag and removed the tag from testing
