### ISSUE TITLE
Installing the Pulumi AWS Crosswalk plugin on Linux fails

### ISSUE THREAD

**Issue by pgermishuys** [pulumi/pulumi-awsx#840]
### What happened?

Installing the Pulumi AWS Crosswalk Plugin fails to complete the installation

### Steps to reproduce

1. Attempt to install the Pulumi AWS Crosswalk Plugin (e.g. `pulumi plugin install resource awsx v1.0.0-beta.2`)
```
> pulumi plugin install resource awsx v1.0.0-beta.2
[resource plugin awsx-1.0.0-beta.2] installing
Downloading plugin: 232.95 KiB / 232.95 KiB [=======================] 100.00% 0s
/usr/bin/env: ‘bash\r’: No such file or directory
error: installing [resource plugin awsx-1.0.0-beta.2] from : installing plugin dependencies: exit status 127
```

### Expected Behavior

The installation to complete without errors

### Actual Behavior

Installation of the plugin fails with 
```
/usr/bin/env: ‘bash\r’: No such file or directory
error: installing [resource plugin awsx-1.0.0-beta.2] from : installing plugin dependencies: exit status 127
```

### Versions used

```
CLI
Version      3.32.1
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.4.0
awsx    1.0.0-beta.2
dotnet  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in dotnet (/usr/bin/dotnet v6.0.300)

Backend
Name           pulumi.com
URL            https://app.pulumi.com/{redacted}
User           {redacted}
Organizations  {redacted}, {redacted}

NAME                       VERSION
Axiom.Platform.Pulumi.Aws  0.1.0
Pulumi.Aws                 5.4.0
Pulumi.Awsx                1.0.0-beta.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
@pgermishuys This issue _should_ be fixed in beta 3, which we are probably releasing today - we are changing the packaging mechanism. Could you see if beta3 fixes your issue and comment on this issue?

Thanks!

**Comment by pgermishuys** [comment]
Will do @jkodroff, will let you know once the release it out.

**Comment by jkodroff** [comment]
@pgermishuys beta 3 is a bad release, so please ignore that one. Could you give this a try with beta 4 (to be released either today or tomorrow) and let me know if it works for you?

**Comment by pgermishuys** [comment]
@jkodroff I noticed that the beta 4 has a release tagged and attempted to install it, but unfortunately I couldn't install it and am getting the following
```
➜ pulumi plugin install resource awsx 1.0.0-beta.4
[resource plugin awsx-1.0.0-beta.4] installing
error: [resource plugin awsx-1.0.0-beta.4] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v1.0.0-beta.4-windows-amd64.tar.gz
```

**Comment by jkodroff** [comment]
@pgermishuys To clarify:

1. Can you confirm that you're running on WSL and it's attempting to download the Windows binary? (If not, please correct.)
2. Do you have this problem with any other providers? e.g. Does it happen with (to pick a random provider): `pulumi plugin install resource tls 3.4.0`?

**Comment by durist** [comment]
I have the same problem (I filed issue https://github.com/pulumi/pulumi/issues/9608)

I'm on Debian linux, I can install tls 3.4.0 but get a 403 when trying to install awsx 1.0.0-beta.4.

**Comment by pgermishuys** [comment]
@jkodroff I am getting the same problem downloading the crosswalk plugin on both windows and linux (under wsl)
e.g.
**Powershell on Windows**
```
➜ pulumi plugin install resource awsx 1.0.0-beta.3
[resource plugin awsx-1.0.0-beta.3] installing
error: [resource plugin awsx-1.0.0-beta.3] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v1.0.0-beta.3-windows-amd64.tar.gz
```
**Ubuntu on WSL**
```
> pulumi plugin install resource awsx v1.0.0-beta.3
[resource plugin awsx-1.0.0-beta.3] installing
error: [resource plugin awsx-1.0.0-beta.3] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v1.0.0-beta.3-linux-amd64.tar.gz
```

I can install the **tls** provider on both platforms as well as the previous versions (e.g. v1.0.0-beta.2) of the crosswalk (awsx) provider, the previous versions just have the issue mentioned in the start of this issue.

**Powershell on Windows**
```
> pulumi plugin install resource tls 3.4.0
[resource plugin tls-3.4.0] installing
Downloading plugin: 13.17 MiB / 13.17 MiB [=========================] 100.00% 1s
```

**Ubuntu on WSL**
```
➜ pulumi plugin install resource tls 3.4.0
[resource plugin tls-3.4.0] installing
Downloading plugin: 13.03 MiB / 13.03 MiB [=========================] 100.00% 0s
```

**Comment by danielrbradley** [comment]
Hi, there's a new beta.5 release just been published which I'm hoping will resolve these issues. Beta 2 and before depended on `node` being available on your PATH but with beta 3 we started moving to producing native binaries with zero dependencies. Beta 3 and 4 had some issues with the specific names required for the provider distribution which should now be resolved in beta 5.

**Comment by durist** [comment]
That works for me, thanks!

**Comment by pgermishuys** [comment]
Confirmed that this works on my end as well! Thank you all so much for the quick response in getting this resolved!
