### ISSUE TITLE
Support Linux ARM64 plugin binaries.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-awsx#846]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When using a devcontainer on an ARM Mac with awsx v1.0.x, the plugin installation fails because there is no Linux ARM plugin binary available.

**Comment by dswartz-altana** [comment]
Love this package, but consequently, many of our development environments have now come to depend on this.
