### ISSUE TITLE
new awsx.lb.ApplicationLoadBalancer() causes go panic

### ISSUE THREAD

**Issue by christopher-haueter** [pulumi/pulumi-awsx#873]
### What happened?

This code

```
const albx = new awsx.lb.ApplicationLoadBalancer("albx", {});
```

causes a panic:

```
panic: fatal: An assertion has failed: Expected string 'awsx:x:elasticloadbalancingv2:ApplicationLoadBalancer' to be a name (([A-Za-z0-9_.-][A-Za-z0-9_.-]*\/)*[A-Za-z0-9_.-][A-Za-z0-9_.-]*)

goroutine 79 [running]:
...
```

### Steps to reproduce

See above

### Expected Behavior

The resource should be created.

### Actual Behavior

A panic halted the program.

### Versions used

`pulumi about` fails both in the pulumi root directory and the project directory (we're using `yarn` workspaces).

Here's an excerpt from `package.json`:
```
  "dependencies": {
    "@pulumi/aws": "^5.8.0",
    "@pulumi/awsx": "^v1.0.0-beta.9",
    "@pulumi/pulumi": "^3.33.2"
  },
```

Also:
```
❯ node -v
v16.15.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by DanHulton** [comment]
For those similarly-affected, you can roll back to an older version of pulumi by first uninstalling your current version, then downloading the installer script:

```bash
curl https://get.pulumi.com > pulumi.sh
chmod a+x pulumi.sh
```

Then installing the second-most recent version:

```bash
./pulumi.sh --version 3.34.1
```

It will prompt you to update your path, but once you do that, you should be back in business until this bug is fixed.

**Comment by stack72** [comment]
Hi @christopher-haueter 

My apologies this is happening here - we are looking into this immediately, @DanHulton is correct, the same code is working perfectly in v3.34.1 of the Pulumi CLI

Paul

**Comment by stack72** [comment]
Hi @christopher-haueter 

@t0yv0 will cut v3.35.1 of Pulumi CLI to fix this issue

Paul

**Comment by lukehoban** [comment]
Pulumi v3.35.1 is available with the fix for this.

https://github.com/pulumi/pulumi/blob/master/CHANGELOG.md#3351-2022-06-24

**Comment by christopher-haueter** [comment]
Thanks for the update @lukehoban!
