### ISSUE TITLE
Version 0.40.0 isn't available for CLI (403 error)

### ISSUE THREAD

**Issue by kkgthb** [pulumi/pulumi-awsx#874]
### What happened?

I tried to use this YAML with `pulumi up`:

```yaml
resources:
  the-default-vpc:
    type: awsx:ec2:DefaultVpc
```

Got this error:

```
    error: error resolving type of resource the-default-vpc: internal error loading package "awsx": no resource plugin 'pulumi-resource-awsx' found in the workspace or on your 
$PATH, install the plugin using `pulumi plugin install resource awsx`
```

So I ran `pulumi plugin install resource awsx` and then got this error:

```
[resource plugin awsx-0.40.0] installing
error: [resource plugin awsx-0.40.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-awsx-v0.40.0-linux-amd64.tar.gz
```

I visited that URL in my web browser, and indeed it's not available to the public.

I don't want to code Pulumi w/ a framework -- I just want to use its CLI & YAML.

### Steps to reproduce

See "what happened"

### Expected Behavior

I expected to have the installer work and then to have my `pulumi up` work.

### Actual Behavior

I can't install the Pulumi CLI AWSX plugin because its TAR file isn't publicly available on the internet

### Versions used

CLI
Version      3.35.3
Go Version   go1.17.11
Go Compiler  gc

Host
OS       ubuntu
Version  20.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @kkgthb 

Sorry about the misleading error here. V0.40.0 is a nodejs package only and is therefore only on npm. The binary based version for use with yaml will be in v1.0.0-beta.9

Pulumi plugin install resource awsx v1.0.0-beta.9

Should be the magic incantation for you :)

Paul

**Comment by kkgthb** [comment]
Hi @stack72 , thanks for the fast reply.

Sadly, that brings up a new problem:

```
Diagnostics:
  pulumi:providers:aws (default_5_4_0):
    error: no resource plugin 'pulumi-resource-aws' found in the workspace at version v5.4.0 or on your $PATH, install the plugin using `pulumi plugin install resource aws v5.4.0`
```

```
pulumi plugin install resource aws v5.40
[resource plugin aws-5.40.0] installing
error: [resource plugin aws-5.40.0] downloading from : 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-aws-v5.40.0-linux-amd64.tar.gz
```

**Comment by stack72** [comment]
You have a typo in installing the aws plugin ;)

*usually* these plugins are installed by the language packages themselves so I apologise for the inconvenience here

**Comment by stack72** [comment]
I have just checked this out and it works as expected - if this is still causing issues then let me know and we can look at it
