### ISSUE TITLE
ECS Task Definition - Container Name is Incorrectly Set Causing Undeployable ECS Service

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-awsx#882]
### What happened?

When executing an ECS task in connection with an ECS service and an ALB, the task definition's `name` field must match the ECS service's load balancer `containerName` field. When constructing a `fargateTaskDefinition` with a single container, the `normalizeFargateTaskDefinitionContainers` function incorrectly sets the container's name to be `container` and not the actual value provided by the user.

When attempting to create a task definition using:
```typescript
var taskDef = new awsx.ecs.FargateTaskDefinition("task", {
    container: {
        image: "nginx:latest",
        portMappings: [{
            hostPort: 80,
            containerPort: 80,
        }],
        name: "test-container",
    }
});
```

the result is the ECS task definition is actually given a name of "container" rather than the requested "test-container".

![image](https://user-images.githubusercontent.com/25461821/179813421-2ca7f617-5896-4510-8e9e-fcb982a0de6b.png)

### Steps to reproduce

Execute the following code to reproduce the error:
```typescript
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

var lb = new awsx.lb.ApplicationLoadBalancer("lb");
var taskDef = new awsx.ecs.FargateTaskDefinition("task", {
    container: {
        image: "nginx:latest",
        portMappings: [{
            hostPort: 80,
            containerPort: 80,
        }],
        name: "test-container",
    }
});

var cluster = new aws.ecs.Cluster("cluster");
var service = new awsx.ecs.FargateService("service", {
    cluster: cluster.arn,
    platformVersion: "LATEST",
    desiredCount: 1,
    loadBalancers: [{
        targetGroupArn: lb.defaultTargetGroup.arn,
        containerName: "test-container",
        containerPort: 80
    }],
    taskDefinition: taskDef.taskDefinition.arn,
});
```

### Expected Behavior

ALB, ECS Service, ECS Task Definition, and ECS Cluster are all successfully created.

### Actual Behavior

ECS Service fails to create due to the improperly named container in the task definition.

![image](https://user-images.githubusercontent.com/25461821/179814065-0f1158c2-dcec-4446-9ce4-4dbed199cbcd.png)

### Versions used

awsx - 1.0.0-beta.9

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by phillipedwards** [comment]
Here's a workaround using the `containers` field of the FargateTaskDefintion, instead of the `container` field:

```
ar lb = new awsx.lb.ApplicationLoadBalancer("lb");
var taskDef = new awsx.ecs.FargateTaskDefinition("task", {
    containers: {
        "test-container": {
            image: "nginx:latest",
            portMappings: [{
                hostPort: 80,
                containerPort: 80,
            }],
        }
    }
});

var cluster = new aws.ecs.Cluster("cluster");
var service = new awsx.ecs.FargateService("service", {
    cluster: cluster.arn,
    platformVersion: "LATEST",
    desiredCount: 1,
    loadBalancers: [{
        targetGroupArn: lb.defaultTargetGroup.arn,
        containerName: "test-container",
        containerPort: 80
    }],
    taskDefinition: taskDef.taskDefinition.arn,
});
```

**Comment by viveklak** [comment]
FYI @danielrbradley.
