### ISSUE TITLE
Support for Log Query metric

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-awsx#888]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I need to be able to support a type for log query metrics that result in the following json: 
```json
        {
            "height": 4,
            "width": 24,
            "y": "10",
            "x": 0,
            "type": "log",
            "properties": {
                "query": "SOURCE '/ecs/logfile' | fields @timestamp, @message | filter message like /(Exception|error|critical)/ | sort @timestamp desc | stats count(*) as Count by bin(10m)",
                "region": "us-west-2",
                "title": "Error and Exception Count",
                "view": "timeSeries",
                "stacked": false
            }
          },
```

### Affected area/feature
Classic Cloud Watch Monitoring.

**Comment by rshade** [comment]
I tried adding the following locally: 
`
export interface LogWidgetJson extends WidgetJson {
    type: pulumi.Input<"log">;
    x: pulumi.Input<number>;
    y: pulumi.Input<number>;
    width: pulumi.Input<number>;
    height: pulumi.Input<number>;
    properties: Record<string, any>;
}`
and got the following error message: 
`Input<"log"> is not assignable to type Input<"alarm" | "metric" | "text">`

**Comment by lukehoban** [comment]
@rshade Any chance you have a complete example for this?

**Comment by lukehoban** [comment]
For example - the following works - which I *think* might be what you need based on what's mentioned above?

```
import * as wjson from "@pulumi/awsx/cloudwatch/widgets_json";

const w: wjson.WidgetJson = {
    "height": 4,
    "width": 24,
    "y": 10,
    "x": 0,
    "type": <"alarm" | "metric" | "text">"log",
    "properties": {
        "query": "SOURCE '/ecs/logfile' | fields @timestamp, @message | filter message like /(Exception|error|critical)/ | sort @timestamp desc | stats count(*) as Count by bin(10m)",
        "region": "us-west-2",
        "title": "Error and Exception Count",
        "view": "timeSeries",
        "stacked": false
    },
}
```

**Comment by stack72** [comment]
As per an internal conversation with @rshade, he's going to look at what is needed here
