### ISSUE TITLE
`subnetSpecs` in `ec2.Vpc` module doesn't support setting of tags.

### ISSUE THREAD

**Issue by DavidHe1127** [pulumi/pulumi-awsx#889]
## Issue details

`subnetSpecs` in `awsx.ec2.Vpc` doesn't support setting of tags while `VpcEndpointSpec` does.
See [docs](https://www.pulumi.com/registry/packages/awsx/api-docs/ec2/vpc/#subnetspec)  

### Affected version

`1.0.0-beta.9`

**Comment by stack72** [comment]
Thanks for this great feedback @DavidHe1127 

 we will get this added :)

Paul
