### ISSUE TITLE
Pulumi auto adds CIDR "0.0.0.0/0" to public aws application load balancer security group

### ISSUE THREAD

**Issue by mjerdely** [pulumi/pulumi-awsx#893]
### What happened?

When the security group for the ALB is created, my list of allowed ingress CIDRs is present along with CIDR "0.0.0.0/0".
Running `pulumi refresh` and `pulumi up` corrects the issue but this security hole shouldn't happen in the first place.

### Steps to reproduce

Create public ALB with the new security group

### Expected Behavior

Only CIDR 192.168.0.0/16 should have access ingress access

### Actual Behavior

CIDR 192.168.0.0/16 and 0.0.0.0/0 have ingress access
The Pulumi Web Console shows the security group without the 0.0.0.0/0 reference

### Versions used

CLI          
Version      3.37.2
Go Version   go1.17.12
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/usr/bin/node' version='v16.16.0'

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
I'm going to move this to awsx, there's a chance awsx is doing something odd itself but if not providers team are best placed to also comment on the underlying aws resource behavior as well.

**Comment by mjerdely** [comment]
Sorry, made a mistake. The Security Group is from @pulumi/aws whereas the application load balancer which uses the security group is in awsx. The code I originally attached also shows this.

**Comment by jkodroff** [comment]
@mjerdely A few quick questions:

* Are you using v0.x of AWSX, or the 1.0 beta?
* If using the 1.0 beta, are you using the `aws` or `aws-classic` namespace?
* A minimal Pulumi program to reproduce would also be helpful to clear up any ambiguity, but not strictly necessary. (I see that you mention attached code but I don't see it on this issue).

Thanks!

**Comment by mjerdely** [comment]
- For awsx, using v0.40.0
- I have attached a slighty obfuscated copy of the load balancer file renamed from .ts to .txt
[github-error.txt](https://github.com/pulumi/pulumi-awsx/files/9312358/github-error.txt)

**Comment by guineveresaenger** [comment]
Hi @mjerdely - we did address this [in 1.x version of this provider](https://github.com/pulumi/pulumi-awsx/releases/tag/v1.0.0-beta.2). Please let us know if you need upgrade assistance. 🙇‍♀️

**Comment by mjerdely** [comment]
> Hi @mjerdely - we did address this [in 1.x version of this provider](https://github.com/pulumi/pulumi-awsx/releases/tag/v1.0.0-beta.2). Please let us know if you need upgrade assistance. bowing_woman

Can you please clarify the recommended version to use?
The current "latest" version tag is only applied to [v0.40.0](https://github.com/pulumi/pulumi-awsx/releases/tag/v0.40.0) whereas all of the 1.x versions are tagged as "Pre-release".

Is there a recommendation on which version of awsx to use?
