### ISSUE TITLE
Confusing UX with port mappings and target ports

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-awsx#894]
### What happened?

A community user filed an issue stating that they were getting the following error:

```
failed creating ECS Task Definition (example-d5811273): ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match
```

This seems to be caused by confusing inputs in the `FargateService` definition

### Steps to reproduce

Define a FargateService and specify both the `host_port` _and_ `target_group`. This is an example in Python, but it should be reproducible in all languages:

```
"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx

cluster = aws.ecs.Cluster("example")

lb = awsx.lb.ApplicationLoadBalancer(
    "example",
)

service = awsx.ecs.FargateService(
    "example",
    cluster=cluster.arn,
    desired_count=2,
    task_definition_args=awsx.ecs.FargateServiceTaskDefinitionArgs(
        container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
            image="danjellz/http-server",
            cpu=512,
            memory=128,
            essential=True,
            port_mappings=[
                awsx.ecs.TaskDefinitionPortMappingArgs(
                    host_port=8080,
                    container_port=8080,
                    target_group=lb.default_target_group,
                )
            ],
        )
    ),
)

pulumi.export("cluster_name", cluster.name)
pulumi.export("task_def", service.task_definition)
```

Defining in this way throws the above error about `awsvpc` networking and that both ports much match. If you examine the state at this point, you'll see this:

```
 + container_definitions   : (json) [
      +     [0]: {
              + cpu             : 512
              + essential       : true
              + image           : "danjellz/http-server"
              + logConfiguration: {
                  + logDriver: "awslogs"
                  + options  : {
                      + awslogs-group        : "example-c8ddb5e"
                      + awslogs-region       : "us-west-2"
                      + awslogs-stream-prefix: "container"
                    }
                }
              + memory          : 128
              + name            : "container"
              + portMappings    : [
              +     [0]: {
                      + containerPort: 8080
                      + hostPort     : 80
                    }
                ]
            }
        ]
```

This seems to be defined here: https://github.com/pulumi/pulumi-awsx/blob/0327b8d0384587da89e6f879431e405045b87f46/awsx/ecs/containers.ts#L52 

The logic to decide that if a hostPort is set **and** and a target group is set, the targetGroup default port takes precedence, which is set to port `80`

The problem here is that in order to then change the port, you'll need to now define a targetGroup yourself, which becomes very involved.

It really should be possible to just define the hostPort and it modify the default target group

### Expected Behavior

Setting the host port actually updates all the related resources

### Actual Behavior

An error

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
FYI @danielrbradley

**Comment by danielrbradley** [comment]
I don't think it's possible to make the port mapping modify the default target group, however the two improvements I could see helping here are:

1. Remove the implicit behaviour where we change the port number - this should highlight if there's a discrepency and fail fast.
2. Add a top-level option to the load ballancer to change just the default target group port as this is likely a common scenario.

**Comment by denolfe** [comment]
This one took me a couple of hours to troubleshoot. Finding this issue helped me find the cause.

**Comment by aaronkao** [comment]
I just hit this error as well
