### ISSUE TITLE
Inconsistencies in capitalisation of types in python

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-awsx#896]
### What happened?

To create a VPC with a single NATGateway you could have something like this:

```python
myvpc = awsx.ec2.Vpc(f"{myname}-vpc",
    cidr_block= my_vpc_cidr_block,
    number_of_availability_zones = my_number_of_availability_zones,
    enable_dns_hostnames=True,
    nat_gateways=awsx.ec2.vpc.NatGatewayConfigurationArgs(strategy =awsx.ec2.vpc.NatGatewayStrategy.SINGLE ), 
)
```

The resource name `Vpc` has a capital `V` but the package path to `NatGatewayConfigurationArgs` has a lower case `vpc` which is confusing, especially as it doesn't say anything like this in the docs

### Steps to reproduce

See above code sample

### Expected Behavior

Consistency between `Vpc` and `vpc`

### Actual Behavior

See above code sample

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
The lowercase version is coming from the filename. The uppercase is the classname. In your example above you can just remove the `.vpc` section:

```python
nat_gateways=awsx.ec2.NatGatewayConfigurationArgs(strategy=awsx.ec2.NatGatewayStrategy.SINGLE ), 
```

**Comment by pierskarsenbarg** [comment]
Can we add something to the docs as the page's path is `ec2 -> vpc -> NatGatewayConfigurationArgs` and if the type is just `awsx.ec2.NatGatewayConfigurationArgs` then it’s not immediately obvious.
