### ISSUE TITLE
No Java Example code

### ISSUE THREAD

**Issue by nagkumar** [pulumi/pulumi-awsx#904]
### What happened?

Pl. do write java sample code to use awsx

### Steps to reproduce

No awsx examples at all https://github.com/pulumi/examples

more so for java

### Expected Behavior

java examples should be shown even in the website 

https://www.pulumi.com/docs/guides/crosswalk/aws/

example currently shown is only in typescript 

### Actual Behavior

no examples

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @nagkumar 

Thanks for opening the issue here - I am tracking a list of things internally for a 1.0 launch later this year and docs on other parts of the system are included. I am going to close this out as a duplicate

Paul
