### ISSUE TITLE
ECR awsx repository URL not accessible

### ISSUE THREAD

**Issue by badaljain** [pulumi/pulumi-awsx#915]
### What happened?

https://www.pulumi.com/docs/guides/crosswalk/aws/ecr/

The example says that the repo url should be accessible as `repo.url`.. In the latest pulumi version the url property doesn't exist

### Steps to reproduce

```
import * as awsx from "@pulumi/awsx";

// Create a repository.
const repo = new awsx.ecr.Repository("my-repo");

// And publish its URL, so we can push to it if we'd like.
export const url = repo.url;
```

### Expected Behavior

url should be accessible or docs should be updated

### Actual Behavior

url property doesn;t exist

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
As reported, I don't see the url as a direct output for the component. @danielrbradley would you be able to check if this was a transcription error while updating the guides to 1.0.0-betax?

**Comment by thomas11** [comment]
This seems to have been fixed in the meantime. I could run the repro:

```
pulumi up --yes
...
Updating (dev)

     Type                           Name               Status
 +   pulumi:pulumi:Stack            awsx-repo-url-dev  created (8s)
 +   └─ awsx:ecr:Repository         my-repo            created (6s)
 +      ├─ aws:ecr:Repository       my-repo            created (1s)
 +      └─ aws:ecr:LifecyclePolicy  my-repo            created (0.63s)

Outputs:
    url: "616138583583.dkr.ecr.us-west-2.amazonaws.com/my-repo-74a8481"
```
