### ISSUE TITLE
VPC: Tags are not applied

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-awsx#922]
### What happened?

When creating an AWSX VPC, tags are not applied to dependent resources.

### Steps to reproduce

```python
"""A Python Pulumi program"""

import pulumi_awsx as awsx

vpc = awsx.ec2.Vpc(
    "david-awsx-question",
    awsx.ec2.VpcArgs(
        subnet_specs=[
            awsx.ec2.SubnetSpecArgs(
                type=awsx.ec2.SubnetType.PUBLIC,
                tags={
                    "ingress": "HECK YEAH, BUDDY!",
                },
            ),
            awsx.ec2.SubnetSpecArgs(
                type=awsx.ec2.SubnetType.PRIVATE,
            ),
        ],
        tags={
            "createdby": "jkodroff",
        },
    )
)
```

### Expected Behavior

* `createdby` should (probably) be applied to all resources. It only seems to appear on the VPC itself.
* `ingress` should (definitely) be applied to the public subnets, and it is not.

### Actual Behavior

See above

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkodroff** [comment]
@danielrbradley Should `tags` at the highest level be applied to all resources, or just the VPC?

**Comment by viveklak** [comment]
Assigning @danielrbradley and @roothorp. Pulled it into milestone to surface this for planning and prioritization. Please feel free to drop the milestone tag afterwards.

**Comment by thutto** [comment]
Just ran into this today trying at add the `type` tag back that existed in the v0.x TS version of awsx vpc.

Are there any updates or suggested work arounds for adding tags to a subnet in v1.x

**Comment by thomas-anderson-bsl** [comment]
> Just ran into this today trying to add the `type` tag back that existed in the v0.x TS version of awsx vpc.
> 
> Are there any updates or suggested work arounds for adding tags to a subnet in v1.x
> 
> I believe the change would be to add the specs tags here along with the `Name`. https://github.com/pulumi/pulumi-awsx/blob/master/awsx/ec2/vpc.ts#L163

Agree fully with @thutto analysis and proposed solution. This particular bug is biting me right now because I need private and public subnets to be tagged appropriately to use [AWS Load Balancer Controller](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/subnet_discovery/).

**Comment by thomas-anderson-bsl** [comment]
For reference, here's the Pulumi I've written:

```
        vpc: awsx.ec2.Vpc = awsx.ec2.Vpc(
            "testtest-vpc",
            subnet_specs=[
                awsx.ec2.SubnetSpecArgs(
                    type=awsx.ec2.SubnetType.PRIVATE,
                    tags={"kubernetes.io/role/internal-elb": "1"},
                    name="private-sn",
                    cidr_mask=20,
                ),
                awsx.ec2.SubnetSpecArgs(
                    type=awsx.ec2.SubnetType.PUBLIC,
                    tags={"kubernetes.io/role/elb": "1"},
                    name="public-sn",
                    cidr_mask=22,
                ),
            ],
        )
```

and here's an example the tags on the public subnet that was created:
![image](https://user-images.githubusercontent.com/26250869/213346374-4f686c90-a5aa-417b-858b-9a796b83ceb0.png)

**Comment by jaxxstorm** [comment]
I've reopened this. I'm surprised the tags aren't added after adding `...args.tags` and not sure how to resolve

**Comment by thomas-anderson-bsl** [comment]
@jaxxstorm I've opened a PR #974 to address this issue, please let me know if you (or any other maintainer) have any feedback. Thanks!

**Comment by dstockhammer** [comment]
This is happening again with v2.5.0
