### ISSUE TITLE
pulumi-awsx fails NPM validation

### ISSUE THREAD

**Issue by NakulK48** [pulumi/pulumi-awsx#924]
### What happened?

When I install `pulumi-awsx` locally and run `npm test --workspaces` I get the following error:

```
$ npm test --workspaces

> @charm-tx/pulumi-aws@0.2.1 test
> tsc --noEmit

../node_modules/@pulumi/awsx/classic/ec2/vpcTopology.d.ts:4:174 - error TS2304: Cannot find name 'AvailabilityZoneDescription'.

4 export declare function create(resource: pulumi.Resource | undefined, vpcName: string, vpcCidr: string, ipv6CidrBlock: pulumi.Output<string> | undefined, availabilityZones: AvailabilityZoneDescription[], numberOfNatGateways: number, assignGeneratedIpv6CidrBlock: pulumi.Input<boolean>, subnetArgsArray: VpcSubnetArgs[]): VpcTopologyDescription;
                                                                                                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in ../node_modules/@pulumi/awsx/classic/ec2/vpcTopology.d.ts:4
```

### Steps to reproduce

Run with the following `tsconfig.json`:

```
{
  "compilerOptions": {
    "target": "es2022",
    "module": "esnext",
    "moduleResolution": "node16",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "sourceMap": true,
    "pretty": true
  },
  "exclude": ["node_modules"]
}

```

and the `package.json`
```
{
  "name": "<name>",
  "version": "0.2.1",
  "type": "module",
  "scripts": {
    "prepublishOnly": "tsc",
    "test": "tsc --noEmit"
  },
  "module": "./lib/index.js",
  "files": [
    "lib/"
  ],
  "exports": {
    ".": "./lib/index.js",
    "./*": "./lib/*.js"
  },
  "typesVersion": {
    "*": {
      "*": [
        "./lib/*"
      ]
    }
  },
  "dependencies": {
    "@pulumi/aws": "^5.16.0",
    "@pulumi/awsx": "1.0.0-beta.7",
    "@pulumi/docker": "^3.4.1",
    "zod": "^3.19.1"
  }
}
```

### Expected Behavior

The test should pass

### Actual Behavior

The test fails

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
We use yarn classic for this repository. Do you get the same error after restoring packages via yarn? If not this is probably related to npm ignoring the `yarn.lock` and restoring incorrect package versions.

**Comment by NakulK48** [comment]
The package we're writing which pulls in the `awsx` dependency is an NPM package and I don't think it's going to work with Yarn commands. Indeed:

```
error Workspaces can only be enabled in private projects.
```

**Comment by danielrbradley** [comment]
Oh, sorry ignore the yarn comment - that's just for internal building - import from NPN should work fine.

Does this problem persist when using the latest version - 1.0.0-beta.11? Also, what version is your `pulumi/aws` dependency actually resolving to?

**Comment by NakulK48** [comment]
Yes, this occurs with `1.0.0-beta.11` - it pulls in `@pulumi/aws` version `5.16.0`

**Comment by danielrbradley** [comment]
Ah it looks like it might be due to the whole vpcTopology being an internal construct previously though this type hasn't had it's annotation removed. 

A quick workaround here is to add `"skipLibCheck": "true"` to your `tsconfig.json`

**Comment by NakulK48** [comment]
Yup, that's working as a workaround - though of course it would be better to check everything fully

**Comment by NakulK48** [comment]
Thanks for resolving this so quickly! Will it go into the next beta version?

**Comment by danielrbradley** [comment]
Yup - this will be released in the next beta version.
