### ISSUE TITLE
Move off the deprecated `getAwsSubnetIds` get function in favor of `getAwsSubnets`

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-awsx#925]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Currently, the user is displayed a warning message for any operation that details the fact that a deprecated getFunction is being used. Eg-

`warning: aws:ec2/getSubnetIds:getSubnetIds verification warning: The aws_subnet_ids data source has been deprecated and will be removed in a future version. Use the aws_subnets data source instead.`

### Affected area/feature
Migrate to the non-deprecated getFunction.

**Comment by danielrbradley** [comment]
What version of the package are you using when you get this error and which resource or function are you calling in AWSx to get this error?

**Comment by phillipedwards** [comment]
@danielrbradley I thought I was on 1.0.0...latest however I think I might have actually been on the old, classic version. I'll close out for now and re-open if needed.
