### ISSUE TITLE
Assertion error when using existing `role_arn` for `awsx.ecs.FargateTaskDefinition`

### ISSUE THREAD

**Issue by magreenbaum** [pulumi/pulumi-awsx#933]
### What happened?

Using Python, I'm unable to create or update an existing `awsx.ecs.FargateTaskDefinition` with an existing `task_role` using the `task_role` parameter.  

### Steps to reproduce

`runtime_role.arn` is from a previously created IAM Role. 

```
        task_definition = awsx.ecs.FargateTaskDefinition(
            resource_name="test-run-taskdef",
            opts=pulumi.ResourceOptions(parent=self),
            task_role=awsx.awsx.DefaultRoleWithPolicyArgs(
                role_arn=runtime_role.arn
            ),
            container=awsx.ecs.TaskDefinitionContainerDefinitionArgs(
                command=command,
                image=image.image_uri,
                cpu=task_cpu,
                memory=task_memory,
                essential=True,
                environment=[
                    awsx.ecs.TaskDefinitionKeyValuePairArgs(name=k, value=v)
                    for k, v in schedule.env.items()
                ],
            ),
        )
```

### Expected Behavior

The specified IAM role arn is attached as the task role to the task definition that is created.

### Actual Behavior

```
AssertionError: Unexpected type; expected a value of type `<class 'pulumi_aws.iam.role.Role'>` but got a value of type `<class 'dict'>` at resource `test-run-taskdef`, property `task_role`: {'roleArn': <pulumi.output.Output object at 0x1124b6470>}
```

### Output of `pulumi about`

```
CLI
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Host
OS       darwin
Version  12.6.1
Arch     arm64
```

### Additional context

The task definition resource gets created fine with a default role if not specifying `task_role`. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by WillDaSilva** [comment]
Seems related to:
- https://github.com/pulumi/pulumi-awsx/issues/929

**Comment by squaremo** [comment]
Thanks for posting this clear explanation of the problem you're experiencing @magreenbaum :+1:
It really does seem a similar shape problem to #929 -- thanks for bringing that up @WillDaSilva. Enough similar that I am hopeful a resolution there would point the way here, or vice versa.

**Comment by WillDaSilva** [comment]
This has been resolved by https://github.com/pulumi/pulumi/issues/11416
