### ISSUE TITLE
Docs for `FargateService` say "Defaults to 0" but it actually defaults to 1

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-awsx#941]
It appears that when we fixed the default, we did not update the docs.

> Number of instances of the task definition to place and keep running. Defaults to 0. Do not specify if using the DAEMON scheduling strategy.

https://github.com/pulumi/pulumi-awsx/blob/c7a75bc774ac65aa613880fdcd7c817455d896ee/awsx/ecs/fargateService.ts

Aside - I tried to fix myself, but wasn't able to trace through where the doc strings came from.  Fixing in the schema didn't work, and there's not docs in `schema-types.ts`.

**Comment by ekini** [comment]
The docs are for "v1.0.0-beta.7 published on Wednesday, May 25, 2022 by Pulumi" version, whereas the latest is v1.0.0-beta.11.

**Comment by danielrbradley** [comment]
This will require an override in the schema generation process as we inherit all the docs from the underlying AWS provider.
