### ISSUE TITLE
AWSx crashes if NODE_OPTIONS is set by IDE

### ISSUE THREAD

**Issue by ajmueller** [pulumi/pulumi-awsx#955]
### What happened?

Following the [Container Service on AWS](https://www.pulumi.com/templates/container-service/aws/) documentation, I'm unable to get the template working out of the box.

### Steps to reproduce

1. Visit [Container Service on AWS](https://www.pulumi.com/templates/container-service/aws/).
2. Follow the steps to create a new instance of the template (create a directory, initialize with `pulumi new container-aws-typescript`) using the default values for every prompt.
3. Run `pulumi up`.

### Expected Behavior

All relevant resources are deployed with Pulumi.

### Actual Behavior

I get the following error output:

```shell
Type                      Name                               Plan       Info
 +   pulumi:pulumi:Stack       container-typescript-template-dev  create     14 messages
     └─ pulumi:providers:awsx  default_1_0_0                                 1 error


Diagnostics:
  pulumi:providers:awsx (default_1_0_0):
    error: could not read plugin [/Users/alex/.pulumi/plugins/resource-awsx-v1.0.0/pulumi-resource-awsx] stdout: EOF

  pulumi:pulumi:Stack (container-typescript-template-dev):
    node:internal/modules/package_json_reader:4
    const internalModuleReadJSON = function (f) { return require('fs').internalModuleReadJSON(f); };
                                                                       ^
    TypeError: require(...).internalModuleReadJSON is not a function
        at internalModuleReadJSON (node:internal/modules/package_json_reader:4:68)
        at Object.read (node:internal/modules/package_json_reader:21:42)
        at readPackage (node:internal/modules/cjs/loader:296:36)
        at readPackageScope (node:internal/modules/cjs/loader:329:19)
        at trySelf (node:internal/modules/cjs/loader:444:40)
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:24)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at Module._preloadModules (node:internal/modules/cjs/loader:1280:12)
        at loadPreloadModules (node:internal/bootstrap/pre_execution:482:5)
```

### Output of `pulumi about`

```shell
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.21.1
awsx    1.0.0
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

This project is written in nodejs: executable='/Users/alex/.nvm/versions/node/v16.18.1/bin/node' version='v16.18.1'

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ajmueller
User           ajmueller
Organizations  ajmueller, atomicfi

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.48.0
@types/node     14.18.34
typescript      4.9.3
@pulumi/aws     5.21.1
@pulumi/awsx    1.0.0

Pulumi locates its logs in /var/folders/q3/k7n69f4n7dq4vlwnvqd4stkm0000gn/T/ by default
```

### Additional context

This was initially brought up by me in pulumi/templates#469 thinking that it might be related, but it didn't seem to be, so I've split it off in to this issue.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Note for possible future implementers ... we could add some configuration to the plugin to specify that `NODE_OPTIONS` should be unset or set to an empty string.

E.g. add a `PulumiPlugin.yaml` with:
```yaml
env:
  NODE_OPTIONS: ""
```

The engine could be updated to apply these environment variables before starting the plugin.

**Comment by cnunciato** [comment]
Thanks @ajmueller for reporting this and @Frassle and @danielrbradley for getting to the bottom of it!

**Comment by ajmueller** [comment]
Thank you all for the quick help!
