### ISSUE TITLE
Golang VPC resource hangs forever when used as pulumi.Parent

### ISSUE THREAD

**Issue by rodrigobrim** [pulumi/pulumi-awsx#964]
### What happened?

With golang SDK, the update/preview stales forever when I set the VPC resource (*awsx.Vpc) as pulumi.Parent.

### Steps to reproduce

```
vpc, _ := ec2x.NewVpc(
    ctx,
    name,
    &ec2x.VpcArgs{
	CidrBlock:                 &cidrBlock,
	NumberOfAvailabilityZones: &numberOfAvailabilityZones,
    },
)

return kms.NewKey(
    ctx,
    name,
    Args,
    pulumi.Parent(vpc),
)
```

### Expected Behavior

Stack updated.

### Actual Behavior

Update/preview hangs forever.

### Output of `pulumi about`

```
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.21.1
awsx        1.0.0
docker      3.2.0
eks         0.42.7
go          unknown
kubernetes  3.20.2

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.18.2 linux/amd64'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hey @rodrigobrim, thanks for the issue! I've had a go at reproducing this but haven't been able to manage. I'm using the following code, and it's creating fine with a `pulumi up`.

```go
	pulumi.Run(func(ctx *pulumi.Context) error {
		vpc, err := ec2.NewVpc(ctx, "roo-test", &ec2.VpcArgs{
			CidrBlock:                 pulumi.StringRef("172.16.8.0/24"),
			NumberOfAvailabilityZones: pulumi.IntRef(2),
		})
		if err != nil {
			return err
		}

		key, err := kms.NewKey(ctx, "roo-test", nil, pulumi.Parent(vpc))
		if err != nil {
			return err
		}

		ctx.Export("key", key)

		return nil
	})
```

Does this differ greatly from your implementation? I can see that you are trying to return the result of `kms.NewKey()`, but I don't know where you're returning it to. If you're trying to export it (as a stack output), you can use `ctx.Export()`.

Hopefully this helps - let me know if I can offer more assistance here!

**Comment by rodrigobrim** [comment]
Hi @roothorp. Thank you again!

I'll double-check it and reply with my code specificities.

**Comment by mikhailshilkov** [comment]
Since we haven't heard back, I'll go ahead and close this issue as stale. Please open a new issue if the problem still persists and provide the details for us to reproduce it. Thank you!
