### ISSUE TITLE
Load Balancer fails to find Subnets by Id with custom provider

### ISSUE THREAD

**Issue by thutto** [pulumi/pulumi-awsx#968]
### What happened?

When attempting to consume an existing VPC/Subnet with the 1.0.1 version of AWSx lb.ApplicationLoadBalancer resource with a custom provider that is not in the default region it fails to find the subnet with the following error.

> Error: failed to register new resource alb-w [awsx:lb:ApplicationLoadBalancer]: 2 UNKNOWN: invocation of aws:ec2/getSubnet:getSubnet returned an error: invoking aws:ec2/getSubnet:getSubnet: 1 error occurred:
    	* no matching EC2 Subnet found

### Steps to reproduce

_I have reduced to just the code needed to reproduce. The full version of this would be multi region and the VPC would not be created within the same stack._

index.ts
```typescript
import { Provider }from "@pulumi/aws";
import {ec2, lb}  from "@pulumi/awsx";

const usWest = new Provider("usWest", { region: "us-west-2" });

const vpcWest = new ec2.Vpc(
  "west-vpc",
  {
    subnetSpecs: [
      {
        type: ec2.SubnetType.Public,
      },
    ],
    numberOfAvailabilityZones: 2,
    natGateways: {
      strategy: ec2.NatGatewayStrategy.None,
    },
  },
  { providers: { aws: usWest } }
);

const albWest = new lb.ApplicationLoadBalancer(
  `alb-w`,
  {
    subnetIds: vpcWest.publicSubnetIds,
  },
  { providers: { aws: usWest } }
);
```
Pulumi.awsx-bug.yaml
```yaml
config:
  aws:region: us-east-1
```

### Expected Behavior

When providing a custom provider this will be passed into all resources that need it. This would result in AWSx being able to find the resources that are not in the default region.

### Actual Behavior

The custom provider does not appear to be used when finding the Subnet so it cannot be used outside of the default region.

### Output of `pulumi about`

❯ pulumi about
CLI
Version      3.49.0
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.23.0
awsx    1.0.1
docker  3.6.1
nodejs  unknown

Host
OS       darwin
Version  12.6
Arch     arm64

This project is written in nodejs: executable='/Users/travishutto/Library/Caches/fnm_multishells/57610_1671116203456/bin/node' version='v18.12.1'

Current Stack: pulumi-provider-bug

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::pulumi:pulumi:Stack::pulumi-provider-bug-pulumi-provider-bug
pulumi:providers:aws                                 urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::pulumi:providers:aws::usWest
pulumi:providers:awsx                                urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::pulumi:providers:awsx::default_1_0_1
pulumi:providers:pulumi                              urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::pulumi:providers:pulumi::default
awsx:ec2:Vpc                                         urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc::west-vpc
aws:ec2/vpc:Vpc                                      urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::west-vpc
aws:ec2/internetGateway:InternetGateway              urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::west-vpc
aws:ec2/subnet:Subnet                                urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::west-vpc-public-1
aws:ec2/subnet:Subnet                                urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::west-vpc-public-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::west-vpc-public-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::west-vpc-public-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::west-vpc-public-1
aws:ec2/route:Route                                  urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::west-vpc-public-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::west-vpc-public-2
aws:ec2/route:Route                                  urn:pulumi:pulumi-provider-bug::pulumi-provider-bug::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::west-vpc-public-2

Found no pending operations associated with pulumi-provider-bug

Backend
Name           TravisHuttosMBP.attlocal.net
URL            file://~
User           travishutto
Organizations

Dependencies:
NAME            VERSION
@pulumi/aws     5.23.0
@pulumi/awsx    1.0.1
@pulumi/pulumi  3.49.0
@types/node     14.18.34

### Additional context

I am able to create an ALB with an existing VPC/Subnet in v0.40.x and I believe this issue may be here.
https://github.com/pulumi/pulumi-awsx/blob/master/awsx/lb/applicationLoadBalancer.ts#L62

When fetching the Subnets it does not appear to retain the context of the custom provider.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Have identified the likely culprit here and have opened a PR to hopefully address the issue: 
- #969

**Comment by thutto** [comment]
Great! Thank you for your time and help.
