### ISSUE TITLE
Stack transformations not applied - auto tagging

### ISSUE THREAD

**Issue by SteffenBoThomsen** [pulumi/pulumi-awsx#979]
### What happened?

Auto tags registered using this [guide](https://www.pulumi.com/blog/automatically-enforcing-aws-resource-tagging-policies/) are not applied to `awsx.ec2.Vpc`.

### Steps to reproduce

A really simple test stack to reproduce:

**index.ts**

```ts
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as awsx from "@pulumi/awsx";

// A slimmed down version of auto tagging as listed in the example guide
pulumi.runtime.registerStackTransformation((args) => {
    // aws:ec2/subnet:Subnet is just used as an example here, it is a problem with all sub resources of awsx.ec2.Vpc
    if (args.type === 'aws:ec2/subnet:Subnet' || args.type === 'aws:s3/bucket:Bucket') {
        args.props["tags"] = { ...args.props["tags"], test: 'TEST' };
        return { props: args.props, opts: args.opts };
    }
    return undefined;
});

// Create an AWS resource (S3 Bucket)
const bucket = new aws.s3.Bucket("my-bucket");

const vpc = new awsx.ec2.Vpc('test');

// Export the name of the bucket
export const bucketName = bucket.id;
export const vpcId = vpc.vpcId;
```

### Expected Behavior

I would expect the diff output to contain:

```txt
            + aws:ec2/subnet:Subnet: (create)
                [urn=urn:pulumi:test::test-autotags::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::test-public-2]
                [provider=urn:pulumi:test::test-autotags::pulumi:providers:aws::default_5_16_2::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
                assignIpv6AddressOnCreation            : false
                availabilityZone                       : "eu-west-1b"
                cidrBlock                              : "10.0.96.0/20"
                enableDns64                            : false
                enableResourceNameDnsARecordOnLaunch   : false
                enableResourceNameDnsAaaaRecordOnLaunch: false
                ipv6Native                             : false
                mapPublicIpOnLaunch                    : true
                tags                                   : {
                    Name      : "test-public-2"
                    SubnetType: "Public",
                    test      : "TEST"
                }
                vpcId                                  : output<string>
```

In the same way as the s3.Bucket

```txt
    + aws:s3/bucket:Bucket: (create)
        [urn=urn:pulumi:test::test-autotags::aws:s3/bucket:Bucket::my-bucket]
        [provider=urn:pulumi:test::test-autotags::pulumi:providers:aws::default_5_27_0::04da6b54-80e4-46f7-96ec-b56ff0331ba9]
        acl         : "private"
        bucket      : "my-bucket-1181bda"
        forceDestroy: false
        tags        : {
            test      : "TEST"
        }
```

### Actual Behavior

The test tag is not applied on the awsx.ec2.Vpc Subnet. When using the full example from the guide, no resources of the aws.ec2.Vpc are tagged.

### Output of `pulumi about`

```txt
CLI          
Version      3.51.1
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.27.0
awsx    1.0.1
docker  3.6.1
nodejs  unknown

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v18.6.0'
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
Thanks for the straight-forward example -- I was able to reproduce this bug in about five minutes flat!

 1. `pulumi new aws-typescript`
 1. I pasted the example code given into index.ts
 1. (I added a `console.log(args.type)` to confirm the type in the condition was correct)
 2. `pulumi up`
 3. I went to the AWS console and confirm that the S3 bucket has the tag `test: TEST`, but any of the subnets created does not.
 4. Additionally, if I change `TEST` to `TEST1`, the diff in `pulumi preview` does not show anything other than the bucket having a change to tags

**Comment by SteffenBoThomsen** [comment]
> but any of the subnets created does not

Just to clarify, this is for all sub resources of the awsx.ec2.Vpc, not just Subnets. Just made the slimmed down example, so i didn't have to paste all the resources from the [auto tagging guide](https://github.com/joeduffy/aws-tags-example/blob/dd890654aa24f4e7731fce1d5737951f98df060a/autotag-ts/taggable.ts#L9).

**Comment by cniessigma** [comment]
Any update on this? I am running into the same issue and it's growing incredibly frustrating. I need to add a tag to a Subnet via a transformation and no matter what I do it's not picking it up for whatever reason.

**Comment by estyrke** [comment]
I can add that the same issue exists in the Python runtime.

**Comment by ghostsquad** [comment]
I'm running into a similar issue, in that I need to be able to inject specific tags to the public/private subnets so the aws-loadbalancer-controller can auto discover them.

**Comment by flostadler** [comment]
Hey folks, sorry you're running into this. It's a known issue that `transformations` (resource and stack) don't work with multi language components (like awsx): https://github.com/pulumi/pulumi/issues/6948

The good news is that this is fixed now. The new resource `transforms` support this: https://www.pulumi.com/blog/resource-transforms/

Here's an example for the VPC component:
```
import * as pulumi from "@pulumi/pulumi";
import * as awsx from "@pulumi/awsx";

const myTags = { test: "TEST" };

pulumi.runtime.registerResourceTransform(args => {
    if (args.type === "aws:ec2/subnet:Subnet") {
        const tags = pulumi.output(args.props.tags || {});
        args.props.tags = tags.apply(t => ({ ...t, ...myTags }));
        return { props: args.props, opts: args.opts };
    }
    return undefined;
});

const vpc = new awsx.ec2.Vpc("test");
```

I'm closing this issue in the meantime, but please do not hesitate to open a new one if you run into other issues around this!
