### ISSUE TITLE
Unable to deploy ALB to custom VPC

### ISSUE THREAD

**Issue by jimjoes** [pulumi/pulumi-awsx#981]
### What happened?

The documentation [here](https://www.pulumi.com/docs/guides/crosswalk/aws/elb/) provides the following code:
```
const vpc = new awsx.ec2.Vpc("web-vpc", { ... });

// Creates an ALB associated with our custom VPC.
const alb = new awsx.lb.ApplicationLoadBalancer("web-traffic", { vpc });
```

However, the ApplicationLoadBalancerArgs type doesn't allow the vpc property:

```
Argument of type '{ vpc: awsx.ec2.Vpc; }' is not assignable to parameter of type 'ApplicationLoadBalancerArgs'.
  Object literal may only specify known properties, and 'vpc' does not exist in type 'ApplicationLoadBalancerArgs'.
```

<img width="820" alt="Untitled 2" src="https://user-images.githubusercontent.com/61049336/214862498-8ec85196-f3ab-4235-8e6c-7e3354ed1b3d.png">

### Expected Behavior

I should be able to specify a custom vpc to deploy a loadbalancer into.

### Steps to reproduce

input the code as per the documentation.

### Output of `pulumi about`

CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

Current Stack: dev

TYPE                                                 URN
pulumi:pulumi:Stack                                  urn:pulumi:dev::analytics-api::pulumi:pulumi:Stack::analytics-api-dev
pulumi:providers:aws                                 urn:pulumi:dev::analytics-api::pulumi:providers:aws::default_5_16_2
pulumi:providers:awsx                                urn:pulumi:dev::analytics-api::pulumi:providers:awsx::default_1_0_1
awsx:ecr:Repository                                  urn:pulumi:dev::analytics-api::awsx:ecr:Repository::dev-authoring-tool-repository
aws:ecr/repository:Repository                        urn:pulumi:dev::analytics-api::awsx:ecr:Repository$aws:ecr/repository:Repository::dev-authoring-tool-repository
aws:ecr/lifecyclePolicy:LifecyclePolicy              urn:pulumi:dev::analytics-api::awsx:ecr:Repository$aws:ecr/lifecyclePolicy:LifecyclePolicy::dev-authoring-tool-repository
awsx:ec2:Vpc                                         urn:pulumi:dev::analytics-api::awsx:ec2:Vpc::dev-authoring-tool-vpc
pulumi:providers:pulumi                              urn:pulumi:dev::analytics-api::pulumi:providers:pulumi::default
aws:ec2/vpc:Vpc                                      urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc::dev-authoring-tool-vpc
aws:ec2/subnet:Subnet                                urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::dev-authoring-tool-vpc-private-3
aws:ec2/internetGateway:InternetGateway              urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::dev-authoring-tool-vpc
aws:ec2/subnet:Subnet                                urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::dev-authoring-tool-vpc-private-1
aws:ec2/subnet:Subnet                                urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::dev-authoring-tool-vpc-private-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::dev-authoring-tool-vpc-private-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::dev-authoring-tool-vpc-private-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::dev-authoring-tool-vpc-private-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::dev-authoring-tool-vpc-private-2
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::dev-authoring-tool-vpc-private-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::dev-authoring-tool-vpc-private-2
aws:efs/fileSystem:FileSystem                        urn:pulumi:dev::analytics-api::aws:efs/fileSystem:FileSystem::dev-authoring-tool-storage
aws:efs/accessPoint:AccessPoint                      urn:pulumi:dev::analytics-api::aws:efs/accessPoint:AccessPoint::dev-authoring-tool-storage-access-point
aws:ecs/cluster:Cluster                              urn:pulumi:dev::analytics-api::aws:ecs/cluster:Cluster::dev-authoring-tool-cluster
aws:ec2/subnet:Subnet                                urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::dev-authoring-tool-vpc-public-2
aws:ec2/subnet:Subnet                                urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::dev-authoring-tool-vpc-public-3
aws:ec2/subnet:Subnet                                urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::dev-authoring-tool-vpc-public-1
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::dev-authoring-tool-vpc-public-2
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::dev-authoring-tool-vpc-public-3
aws:ec2/routeTable:RouteTable                        urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable::dev-authoring-tool-vpc-public-1
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::dev-authoring-tool-vpc-public-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::dev-authoring-tool-vpc-public-2
aws:ec2/route:Route                                  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::dev-authoring-tool-vpc-public-2
aws:ec2/route:Route                                  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::dev-authoring-tool-vpc-public-1
aws:ec2/route:Route                                  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/route:Route::dev-authoring-tool-vpc-public-3
aws:ec2/routeTableAssociation:RouteTableAssociation  urn:pulumi:dev::analytics-api::awsx:ec2:Vpc$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet$aws:ec2/routeTable:RouteTable$aws:ec2/routeTableAssociation:RouteTableAssociation::dev-authoring-tool-vpc-public-1
awsx:ecr:Image                                       urn:pulumi:dev::analytics-api::awsx:ecr:Image::dev-authoring-tool-img
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:dev::analytics-api::aws:ec2/securityGroup:SecurityGroup::dev-authoring-tool-alb-security-group
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:dev::analytics-api::aws:ec2/securityGroup:SecurityGroup::dev-authoring-tool-task-security-group
aws:ec2/securityGroup:SecurityGroup                  urn:pulumi:dev::analytics-api::aws:ec2/securityGroup:SecurityGroup::dev-authoring-storage-security-group
awsx:lb:ApplicationLoadBalancer                      urn:pulumi:dev::analytics-api::awsx:lb:ApplicationLoadBalancer::dev-authoring-tool-lb
aws:lb/targetGroup:TargetGroup                       urn:pulumi:dev::analytics-api::awsx:lb:ApplicationLoadBalancer$aws:lb/targetGroup:TargetGroup::dev-authoring-tool-lb

Found no pending operations associated with dev

Backend        
Name           Jamess-MacBook-Pro-2.local
URL            file:///Users/jameshunter/src/theinnovatecrowd-platform/.pulumi/apps/authoring
User           jameshunter
Organizations  

Pulumi locates its logs in /var/folders/hh/h8crj51d24q7dbnk4bwpxwl00000gn/T/ by default
warning: Failed to get information about the project runtime: unknown method About for service pulumirpc.LanguageRuntime
warning: Failed to get information about the Pulumi program's dependencies: unknown method GetProgramDependencies for service pulumirpc.LanguageRuntime

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
Absolutely right, that is not a field of ApplicationLoadBalancer. Oops! Thanks for pointing this out.

**Comment by rveitch** [comment]
> Absolutely right, that is not a field of ApplicationLoadBalancer. Oops! Thanks for pointing this out, we'll have to rework that section.

Does that mean that custom VPC's are actually no longer supported?

**Comment by evanrbowers** [comment]
I'm also running into this issue.  Specifying the subnetIds does not appear to work as it conflicts with the vpc being used.

**Comment by flostadler** [comment]
The docs are fixed: https://www.pulumi.com/docs/iac/clouds/aws/guides/elb/#creating-a-load-balancer-in-a-custom-vpc
They now show this example:
```ts
import * as awsx from "@pulumi/awsx";

// Allocate (or get) a custom VPC.
const vpc = new awsx.ec2.Vpc("vpc");

// Create a load balancer in the default VPC listening on port 80.
const alb = new awsx.lb.ApplicationLoadBalancer("lb", {
    listener: {
        port: 80,
    },

    // Associate the load balancer with the VPC's `public` or `private` subnet.
    subnetIds: vpc.publicSubnetIds,
});

// Export the resulting URL so that it's easy to access.
export const endpoint = alb.loadBalancer.dnsName;
```
