### ISSUE TITLE
Not possible to set env vars in `awsx.ecr.Image`

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-awsx#988]
### What happened?

I'm trying to set the env vars needed on an image for a multi stage build.

The typing on `env` is `Input[Mapping[str, Input[str]]] | None`

But I need to add two env vars

```
env=[
                     {"DOCKER_BUILDKIT", "1"},
                     {"DOCKER_DEFAULT_PLATFORM", "linux/amd64"},
,
```

### Expected Behavior

Env vars are a list

### Steps to reproduce

Try build an image like so:

```
self.image = awsx.ecr.Image(
                f"{name}-image",
                args=args.arguments,
                repository_url=self.repository.url,
                path=args.path,
                dockerfile=args.dockerfile,
                env=[
                     {"DOCKER_BUILDKIT", "1"},
                     {"DOCKER_DEFAULT_PLATFORM", "linux/amd64"},
                ],
                opts=pulumi.ResourceOptions(parent=self.repository),
            )
```

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
> Env vars are a list
> ...
> The typing on env is `Input[Mapping[str, Input[str]]] | None`

A `Mapping` is a dict in Python.  So I would expect you need to pass:

```py
                env= {
                     "DOCKER_BUILDKIT": "1",
                     "DOCKER_DEFAULT_PLATFORM": "linux/amd64",
                },
```

Not entirely sure why this isn't a typechecking error at (a) the `mypy`/`pylance` level (b) at runtime at the Pulumi level.  But pretty sure the code above is not type-correct for the API definition.

**Comment by jaxxstorm** [comment]
yep, user error
