### ISSUE TITLE
What happened to apigateway?

### ISSUE THREAD

**Issue by hamuk** [pulumi/pulumi-awsx#989]
### What happened?

I'm currently upgrading from 0.x to 1.0 and it seems apigateway has been removed with no replacement? 

I have replaced my reference with the classic namespace for just apigateway but in the readme it says classic will be removed in the next major release. 

Are there plans to bring apigateway back? Also can it be added to the readme in the notable change section?

### Expected Behavior

awsx.apigateway should exist/have a replacement

### Steps to reproduce

Try use awsx.apigateway in 1.0

### Output of `pulumi about`

CLI          
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Host     
OS       darwin
Version  13.0.1
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @hamuk, sorry for the confusion. 

If you’re currently using v0.x and want to upgrade to v1.x you can either:
1. Change references from @pulumi/awsx to @pulumi/awsx/classic to maintain existing behaviour, or
2. Refactor to replace the classic components with the new top-level components. This may require additional code changes and resource re-creation.

For users with existing pre-v1 infra, we're typically suggesting (1).

There's a note about this and links to further docs in the [1.0 announcement](https://www.pulumi.com/blog/crosswalk-for-aws-1-0/#migration-from-awsx-0x-to-10).

Hope that helps!

**Comment by hamuk** [comment]
I have fixed it for now by changing the reference to @pulumi/awsx/classic but as I said the readme says classic will be removed in the next major release, are there plans to migrate apigateway to awsx 1.x? It doesn't mention it anywhere in the readme/docs that I can see?

**Comment by thomas11** [comment]
Hey @hamuk, the next major release is a ways off so you have time. The way forward then would be option (2), use the new [ApiGateway component](https://www.pulumi.com/docs/guides/crosswalk/aws/api-gateway/). Components didn't exist yet when awsx classic was released.

**Comment by hamuk** [comment]
Ah OK apologies, I didn't realise ApiGateway had been moved out into it's own package. I'll be honest it's a bit confusing having different pulumi packages for various parts of AWS with similar names and now there are "top level components" as well but I think I get it now

Many thanks
